// Retained fleet for one-time migration; plans are product configuration.
import type {Vehicle,Plan} from "../types";
export const INITIAL_PLANS: Plan[] = [
  {
    id: "plan-starter",
    name: "Starter Fleet",
    code: "STARTER",
    description: "Ideal for small independent operators with up to 5 vehicles.",
    status: "ACTIVE",
    price: 9500,
    monthlyPrice: 9500,
    annualPrice: 95000,
    billingInterval: "MONTHLY",
    trialDurationDays: 14,
    isPublic: true,
    sortOrder: 1,
    currency: "KES",
    maxVehicles: 5,
    maxMembers: 3,
    allowCustomDomain: false,
    allowDoubleEntryLedger: false,
    allowOwnerSettlements: false,
    allowPublicWebsite: true,
    allowMpesaDaraja: true,
    version: 1,
    features: ["fleet.vehicle.create", "booking.create", "website.enabled"],
  },
  {
    id: "plan-growth",
    name: "Growth Operator",
    code: "GROWTH",
    description: "For expanding fleets requiring owner settlements, ledger accounting, and custom domains.",
    status: "ACTIVE",
    price: 24500,
    monthlyPrice: 24500,
    annualPrice: 245000,
    billingInterval: "MONTHLY",
    trialDurationDays: 14,
    isPublic: true,
    sortOrder: 2,
    currency: "KES",
    maxVehicles: 25,
    maxMembers: 10,
    allowCustomDomain: true,
    allowDoubleEntryLedger: true,
    allowOwnerSettlements: true,
    allowPublicWebsite: true,
    allowMpesaDaraja: true,
    version: 1,
    features: [
      "fleet.vehicle.create",
      "booking.create",
      "website.enabled",
      "website.custom_domain",
      "finance.ledger",
      "settlements.manage",
      "reports.advanced",
    ],
  },
  {
    id: "plan-enterprise",
    name: "Enterprise Multi-Branch",
    code: "ENTERPRISE",
    description: "High-scale commercial operations with multi-branch management and API access.",
    status: "ACTIVE",
    price: 65000,
    monthlyPrice: 65000,
    annualPrice: 650000,
    billingInterval: "MONTHLY",
    trialDurationDays: 30,
    isPublic: true,
    sortOrder: 3,
    currency: "KES",
    maxVehicles: 150,
    maxMembers: 50,
    allowCustomDomain: true,
    allowDoubleEntryLedger: true,
    allowOwnerSettlements: true,
    allowPublicWebsite: true,
    allowMpesaDaraja: true,
    version: 1,
    features: [
      "fleet.vehicle.create",
      "booking.create",
      "website.enabled",
      "website.custom_domain",
      "finance.ledger",
      "settlements.manage",
      "reports.advanced",
      "api.access",
      "compliance.advanced",
    ],
  },
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: "veh-01",
    tenantId: "tenant-nairobi",
    registrationPlate: "KDF 450T",
    make: "Toyota",
    model: "Land Cruiser Prado TX-L",
    year: 2022,
    category: "4x4 Offroad",
    color: "Pearl White",
    vin: "JTEBX71J2N8941029",
    odometer: 48520,
    fuelLevel: 85,
    dailyRate: 18500,
    lifecycleStatus: "ACTIVE",
    availabilityStatus: "AVAILABLE",
    transmission: "Automatic",
    seats: 7,
    fuelType: "Diesel",
    features: ["Sunroof", "Leather Seats", "Diff Lock", "Apple CarPlay", "Roof Rails", "Tow Bar"],
    imageUrl: "https://images.unsplash.com/photo-1594502184342-2e12f877aa73?auto=format&fit=crop&w=800&q=80",
    currentLocation: "Westlands HQ Hub",
    isPublishedToWebsite: true,
    ownerId: "owner-kiprono",
    activeOwnershipId: "own-01",
    insuranceExpiryDate: "2027-02-15",
    inspectionExpiryDate: "2027-04-10",
    lastServiceMileage: 45000,
    nextServiceMileage: 55000,
    createdAt: "2025-03-15T00:00:00Z",
    updatedAt: "2026-08-20T00:00:00Z",
  },
  {
    id: "veh-02",
    tenantId: "tenant-nairobi",
    registrationPlate: "KDG 892M",
    make: "Toyota",
    model: "RAV4 Adventure AWD",
    year: 2023,
    category: "SUV",
    color: "Lunar Rock Gray",
    vin: "JTMBFREV9P0184910",
    odometer: 28400,
    fuelLevel: 95,
    dailyRate: 11000,
    lifecycleStatus: "ACTIVE",
    availabilityStatus: "ON_RENT",
    transmission: "Automatic",
    seats: 5,
    fuelType: "Hybrid",
    features: ["AWD System", "Reverse Camera", "Lane Assist", "Wireless Charger", "Eco Mode"],
    imageUrl: "https://images.unsplash.com/photo-1581540222194-0def2dda95b8?auto=format&fit=crop&w=800&q=80",
    currentLocation: "On Road - Nairobi/Naivasha",
    isPublishedToWebsite: true,
    ownerId: "owner-internal",
    activeOwnershipId: "own-02",
    insuranceExpiryDate: "2027-06-20",
    inspectionExpiryDate: "2027-08-15",
    lastServiceMileage: 25000,
    nextServiceMileage: 35000,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2026-08-20T00:00:00Z",
  },
  {
    id: "veh-03",
    tenantId: "tenant-nairobi",
    registrationPlate: "KDH 112L",
    make: "Mercedes-Benz",
    model: "E300 AMG Line",
    year: 2022,
    category: "Luxury",
    color: "Obsidian Black",
    vin: "WDD2130832B941029",
    odometer: 34100,
    fuelLevel: 90,
    dailyRate: 28000,
    lifecycleStatus: "ACTIVE",
    availabilityStatus: "RESERVED",
    transmission: "Automatic",
    seats: 5,
    fuelType: "Petrol",
    features: ["Panoramic Roof", "Burmester Audio", "Ambient Lighting", "Chauffeur Ready", "Rear Entertainment"],
    imageUrl: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80",
    currentLocation: "JKIA VIP Lounge Depot",
    isPublishedToWebsite: true,
    ownerId: "owner-mama-ngina",
    activeOwnershipId: "own-03",
    insuranceExpiryDate: "2027-01-10",
    inspectionExpiryDate: "2027-03-30",
    lastServiceMileage: 30000,
    nextServiceMileage: 40000,
    createdAt: "2025-04-15T00:00:00Z",
    updatedAt: "2026-08-20T00:00:00Z",
  },
  {
    id: "veh-04",
    tenantId: "tenant-nairobi",
    registrationPlate: "KDB 340A",
    make: "Toyota",
    model: "Premio F-EX",
    year: 2020,
    category: "Sedan",
    color: "Silver Metallic",
    vin: "NZT260-3104921",
    odometer: 72100,
    fuelLevel: 70,
    dailyRate: 5500,
    lifecycleStatus: "ACTIVE",
    availabilityStatus: "MAINTENANCE",
    transmission: "Automatic",
    seats: 5,
    fuelType: "Petrol",
    features: ["Push Start", "Dual Airbags", "Rear Camera", "Fuel Efficient 1.5L"],
    imageUrl: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=800&q=80",
    currentLocation: "Express Auto Works Westlands",
    isPublishedToWebsite: true,
    ownerId: "owner-internal",
    activeOwnershipId: "own-04",
    insuranceExpiryDate: "2026-10-18",
    inspectionExpiryDate: "2026-11-20",
    lastServiceMileage: 70000,
    nextServiceMileage: 75000,
    createdAt: "2025-02-01T00:00:00Z",
    updatedAt: "2026-08-20T00:00:00Z",
  },
  {
    id: "veh-05",
    tenantId: "tenant-nairobi",
    registrationPlate: "KDE 777Q",
    make: "Toyota",
    model: "Land Cruiser 200 V8 ZX",
    year: 2021,
    category: "4x4 Offroad",
    color: "Onyx Black",
    vin: "URJ202-0194821",
    odometer: 51200,
    fuelLevel: 100,
    dailyRate: 32000,
    lifecycleStatus: "ACTIVE",
    availabilityStatus: "AVAILABLE",
    transmission: "Automatic",
    seats: 8,
    fuelType: "Diesel",
    features: ["Crawl Control", "Cool Box", "Rear Screen", "Air Suspension", "Bull Bar", "Snorkel"],
    imageUrl: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
    currentLocation: "Westlands HQ Hub",
    isPublishedToWebsite: true,
    ownerId: "owner-kiprono",
    activeOwnershipId: "own-05",
    insuranceExpiryDate: "2027-05-15",
    inspectionExpiryDate: "2027-07-20",
    lastServiceMileage: 50000,
    nextServiceMileage: 60000,
    createdAt: "2025-05-01T00:00:00Z",
    updatedAt: "2026-08-20T00:00:00Z",
  },
  {
    id: "veh-06",
    tenantId: "tenant-nairobi",
    registrationPlate: "KDC 612P",
    make: "Toyota",
    model: "HiAce Super Custom Luxury Van",
    year: 2021,
    category: "Van/Bus",
    color: "Gold Metallic",
    vin: "TRH214-9841029",
    odometer: 64500,
    fuelLevel: 60,
    dailyRate: 15000,
    lifecycleStatus: "ACTIVE",
    availabilityStatus: "AVAILABLE",
    transmission: "Automatic",
    seats: 10,
    fuelType: "Diesel",
    features: ["Captains Chairs", "Twin Moonroof", "Electric Sliding Doors", "PA System", "Large Luggage Bay"],
    imageUrl: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
    currentLocation: "Westlands HQ Hub",
    isPublishedToWebsite: true,
    ownerId: "owner-internal",
    activeOwnershipId: "own-06",
    insuranceExpiryDate: "2026-12-05",
    inspectionExpiryDate: "2027-02-14",
    lastServiceMileage: 60000,
    nextServiceMileage: 70000,
    createdAt: "2025-02-15T00:00:00Z",
    updatedAt: "2026-08-20T00:00:00Z",
  },
];
