export const SUBSCRIPTION_STATES = [
  "TRIAL",
  "ACTIVE",
  "RENEWAL_DUE",
  "PAST_DUE",
  "GRACE_PERIOD",
  "SUSPENDED",
  "CANCELLED",
  "EXPIRED",
] as const;

export type CanonicalSubscriptionState = (typeof SUBSCRIPTION_STATES)[number];

export const OPERATION_CATEGORIES = [
  "READ_EXISTING_DATA",
  "CREATE_NEW_RESOURCE",
  "UPDATE_EXISTING_RESOURCE",
  "DELETE_RESOURCE",
  "COMPLETE_EXISTING_RENTAL",
  "MANAGE_EXISTING_BOOKING",
  "BILLING_ACCESS",
  "SUBSCRIPTION_MANAGEMENT",
  "DATA_EXPORT",
  "PUBLIC_BOOKING",
  "PLATFORM_SUPPORT_ACTION",
] as const;

export const TENANT_ACCESS_MODES = [
  "FULL",
  "WARNING",
  "RESTRICTED",
  "SUSPENDED",
] as const;

export const VEHICLE_LIFECYCLE_STATUSES = [
  "DRAFT",
  "ACTIVE",
  "IN_SERVICE",
  "OUT_OF_SERVICE",
  "DECOMMISSIONED",
  "SOLD",
] as const;

export const VEHICLE_AVAILABILITY_STATUSES = [
  "AVAILABLE",
  "RESERVED",
  "ON_RENT",
  "MAINTENANCE",
  "INSPECTION_PENDING",
  "BLOCKED",
] as const;

export const BOOKING_STATUSES = [
  "DRAFT",
  "PENDING_CONFIRMATION",
  "CONFIRMED",
  "DISPATCHED_TO_RENTAL",
  "COMPLETED",
  "CANCELLED",
  "NO_SHOW",
] as const;

export const RENTAL_STATES = [
  "PRE_DISPATCH",
  "ACTIVE_ON_ROAD",
  "RETURN_INSPECTED",
  "FINAL_SETTLEMENT_PENDING",
  "CLOSED",
] as const;

export const PAYMENT_METHODS = [
  "MPESA_STK_PUSH",
  "MPESA_PAYBILL",
  "CARD_STRIPE",
  "CARD_PESAPAL",
  "BANK_TRANSFER",
  "CASH",
] as const;

export const LEDGER_ACCOUNT_TYPES = [
  "ASSET",
  "LIABILITY",
  "EQUITY",
  "REVENUE",
  "EXPENSE",
] as const;

export const DEFAULT_CURRENCY = "KES";
export const CANONICAL_MONEY_SCALE = 4; // PostgreSQL NUMERIC(19,4) scale
export const DISPLAY_MONEY_SCALE = 2;

export const PERMISSIONS = {
  // Fleet
  FLEET_READ: "fleet.vehicle.read",
  FLEET_WRITE: "fleet.vehicle.write",
  FLEET_DELETE: "fleet.vehicle.delete",
  // Bookings
  BOOKING_READ: "booking.read",
  BOOKING_CREATE: "booking.create",
  BOOKING_MODIFY: "booking.modify",
  BOOKING_CANCEL: "booking.cancel",
  // Rentals
  RENTAL_DISPATCH: "rental.dispatch",
  RENTAL_RETURN: "rental.return",
  RENTAL_EXTEND: "rental.extend",
  // Finance
  FINANCE_READ: "finance.read",
  FINANCE_INVOICE_CREATE: "finance.invoice.create",
  FINANCE_PAYMENT_RECORD: "finance.payment.record",
  FINANCE_SETTLEMENT_GENERATE: "finance.settlement.generate",
  // Website CMS, Domains & Branding (Sprint 29 & 30: ARCH-001, DEV-008, TEN-001)
  WEBSITE_READ: "website.read",
  WEBSITE_UPDATE: "website.update",
  WEBSITE_MANAGE: "website.manage",
  WEBSITE_PUBLISH: "website.publish",
  WEBSITE_DOMAIN_READ: "website.domain.read",
  WEBSITE_DOMAIN_MANAGE: "website.domain.manage",
  DOMAIN_MANAGE: "domain.manage",
  // Admin & Settings
  SETTINGS_WRITE: "settings.write",
  ROLES_MANAGE: "roles.manage",
} as const;

export * from "./permissions";
export * from "./roles";

export const ERROR_CODES = {
  UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  FORBIDDEN: "AUTH_FORBIDDEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  SESSION_REVOKED: "SESSION_REVOKED",
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
  REFRESH_TOKEN_REUSED: "REFRESH_TOKEN_REUSED",
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  RESET_TOKEN_INVALID: "RESET_TOKEN_INVALID",
  RESET_TOKEN_EXPIRED: "RESET_TOKEN_EXPIRED",
  VERIFICATION_TOKEN_INVALID: "VERIFICATION_TOKEN_INVALID",
  VERIFICATION_TOKEN_EXPIRED: "VERIFICATION_TOKEN_EXPIRED",
  RATE_LIMITED: "RATE_LIMITED",
  // Tenancy Error Codes (Sprint 4: DEV-004, DEV-007)
  TENANT_REQUIRED: "TENANT_REQUIRED",
  TENANT_NOT_FOUND: "TENANT_NOT_FOUND",
  TENANT_ACCESS_DENIED: "TENANT_ACCESS_DENIED",
  TENANT_MEMBERSHIP_INACTIVE: "TENANT_MEMBERSHIP_INACTIVE",
  TENANT_SUSPENDED: "TENANT_SUSPENDED",
  INVALID_TENANT_CONTEXT: "INVALID_TENANT_CONTEXT",
  TENANT_SLUG_CONFLICT: "TENANT_SLUG_CONFLICT",
  TENANT_SLUG_INVALID: "TENANT_SLUG_INVALID",
  TENANT_MISMATCH: "TENANT_MISMATCH_ERROR",
  CROSS_TENANT_VIOLATION: "CROSS_TENANT_VIOLATION_DETECTED",
  // Authorization & RBAC Error Codes (Sprint 5: DEV-005, SEC-005, SEC-007)
  PERMISSION_DENIED: "PERMISSION_DENIED",
  ROLE_NOT_FOUND: "ROLE_NOT_FOUND",
  ROLE_NOT_ASSIGNABLE: "ROLE_NOT_ASSIGNABLE",
  ROLE_PROTECTED: "ROLE_PROTECTED",
  ROLE_NAME_CONFLICT: "ROLE_NAME_CONFLICT",
  INVALID_PERMISSION: "INVALID_PERMISSION",
  LAST_OWNER_REQUIRED: "LAST_OWNER_REQUIRED",
  MEMBERSHIP_INACTIVE: "MEMBERSHIP_INACTIVE",
  PLATFORM_PERMISSION_DENIED: "PLATFORM_PERMISSION_DENIED",
  SUPPORT_ACCESS_REQUIRED: "SUPPORT_ACCESS_REQUIRED",
  SUPPORT_SESSION_EXPIRED: "SUPPORT_SESSION_EXPIRED",
  RESOURCE_ACCESS_DENIED: "RESOURCE_ACCESS_DENIED",
  PRIVILEGE_ESCALATION_DETECTED: "PRIVILEGE_ESCALATION_DETECTED",
  ENTITLEMENT_EXCEEDED: "ENTITLEMENT_EXCEEDED",
  DOUBLE_BOOKING_PREVENTED: "DOUBLE_BOOKING_PREVENTED",
  IMMUTABLE_RECORD_MODIFICATION: "IMMUTABLE_RECORD_MODIFICATION",
  INVALID_STATE_TRANSITION: "INVALID_STATE_TRANSITION",
  MONEY_PRECISION_ERROR: "MONEY_PRECISION_ERROR",
  // Subscription & SaaS Billing Error Codes (Sprint 6: Control Plane SaaS Billing)
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  PLAN_INACTIVE: "PLAN_INACTIVE",
  PLAN_CODE_EXISTS: "PLAN_CODE_EXISTS",
  SUBSCRIPTION_NOT_FOUND: "SUBSCRIPTION_NOT_FOUND",
  SUBSCRIPTION_ALREADY_EXISTS: "SUBSCRIPTION_ALREADY_EXISTS",
  INVALID_SUBSCRIPTION_TRANSITION: "INVALID_SUBSCRIPTION_TRANSITION",
  SUBSCRIPTION_CONCURRENCY_CONFLICT: "SUBSCRIPTION_CONCURRENCY_CONFLICT",
  BILLING_ACCOUNT_NOT_FOUND: "BILLING_ACCOUNT_NOT_FOUND",
  BILLING_INVOICE_NOT_FOUND: "BILLING_INVOICE_NOT_FOUND",
  BILLING_INVOICE_ALREADY_PAID: "BILLING_INVOICE_ALREADY_PAID",
  BILLING_INVOICE_NOT_OPEN: "BILLING_INVOICE_NOT_OPEN",
  INVALID_BILLING_PERIOD: "INVALID_BILLING_PERIOD",
  SUBSCRIPTION_CHANGE_NOT_ALLOWED: "SUBSCRIPTION_CHANGE_NOT_ALLOWED",
  TRIAL_ALREADY_USED: "TRIAL_ALREADY_USED",
  // Subscription Enforcement & Restricted Mode Error Codes (Sprint 8: ENT-001, ARCH-004, DEV-007)
  SUBSCRIPTION_INACTIVE: "SUBSCRIPTION_INACTIVE",
  SUBSCRIPTION_SUSPENDED: "SUBSCRIPTION_SUSPENDED",
  SUBSCRIPTION_EXPIRED: "SUBSCRIPTION_EXPIRED",
  SUBSCRIPTION_GRACE_RESTRICTION: "SUBSCRIPTION_GRACE_RESTRICTION",
  SUBSCRIPTION_PAST_DUE_RESTRICTION: "SUBSCRIPTION_PAST_DUE_RESTRICTION",
  RESTRICTED_MODE_BLOCKED: "RESTRICTED_MODE_BLOCKED",
  PUBLIC_BOOKING_DISABLED: "PUBLIC_BOOKING_DISABLED",
  FEATURE_NOT_INCLUDED: "FEATURE_NOT_INCLUDED",
  ENTITLEMENT_DISABLED: "ENTITLEMENT_DISABLED",
  LIMIT_REACHED: "LIMIT_REACHED",
  USAGE_EXCEEDED: "USAGE_EXCEEDED",
  ADDON_REQUIRED: "ADDON_REQUIRED",
  PLAN_UPGRADE_REQUIRED: "PLAN_UPGRADE_REQUIRED",
  TENANT_RESTRICTED: "TENANT_RESTRICTED",
  PLATFORM_RESTRICTED: "PLATFORM_RESTRICTED",
  // Fleet & Vehicle Owner Error Codes (Sprint 9: DOM-001, DOM-003, DEV-007, BRS-001)
  VEHICLE_NOT_FOUND: "VEHICLE_NOT_FOUND",
  VEHICLE_REGISTRATION_EXISTS: "VEHICLE_REGISTRATION_EXISTS",
  VEHICLE_VIN_EXISTS: "VEHICLE_VIN_EXISTS",
  VEHICLE_INVALID_STATUS_TRANSITION: "VEHICLE_INVALID_STATUS_TRANSITION",
  VEHICLE_NOT_OPERATIONAL: "VEHICLE_NOT_OPERATIONAL",
  VEHICLE_CONCURRENCY_CONFLICT: "VEHICLE_CONCURRENCY_CONFLICT",
  VEHICLE_LIMIT_REACHED: "VEHICLE_LIMIT_REACHED",
  VEHICLE_OWNER_NOT_FOUND: "VEHICLE_OWNER_NOT_FOUND",
  VEHICLE_OWNERSHIP_NOT_FOUND: "VEHICLE_OWNERSHIP_NOT_FOUND",
  VEHICLE_OWNERSHIP_CONFLICT: "VEHICLE_OWNERSHIP_CONFLICT",
  VEHICLE_OWNERSHIP_OVERLAP: "VEHICLE_OWNERSHIP_OVERLAP",
  CROSS_TENANT_RELATIONSHIP_DENIED: "CROSS_TENANT_RELATIONSHIP_DENIED",
  INVALID_REVENUE_SHARE: "INVALID_REVENUE_SHARE",
  VEHICLE_CATEGORY_NOT_FOUND: "VEHICLE_CATEGORY_NOT_FOUND",
  VEHICLE_DOCUMENT_NOT_FOUND: "VEHICLE_DOCUMENT_NOT_FOUND",
  // Pricing & Rate Engine Error Codes (Sprint 11: DEV-007, BRS-001, ARCH-004)
  RATE_PLAN_NOT_FOUND: "RATE_PLAN_NOT_FOUND",
  RATE_PLAN_INACTIVE: "RATE_PLAN_INACTIVE",
  RATE_PLAN_CODE_EXISTS: "RATE_PLAN_CODE_EXISTS",
  PRICING_RULE_INVALID: "PRICING_RULE_INVALID",
  PRICING_RULE_CONFLICT: "PRICING_RULE_CONFLICT",
  NO_APPLICABLE_RATE: "NO_APPLICABLE_RATE",
  INVALID_RENTAL_PERIOD: "INVALID_RENTAL_PERIOD",
  CURRENCY_MISMATCH: "CURRENCY_MISMATCH",
  INVALID_DISCOUNT: "INVALID_DISCOUNT",
  INVALID_TAX_CONFIGURATION: "INVALID_TAX_CONFIGURATION",
  PRICE_CALCULATION_FAILED: "PRICE_CALCULATION_FAILED",
  PRICING_VERSION_CONFLICT: "PRICING_VERSION_CONFLICT",
  CROSS_TENANT_RATE_ASSIGNMENT: "CROSS_TENANT_RATE_ASSIGNMENT",
  PROMO_CODE_NOT_FOUND: "PROMO_CODE_NOT_FOUND",
  PROMO_CODE_EXPIRED: "PROMO_CODE_EXPIRED",
  PROMO_CODE_USAGE_LIMIT_REACHED: "PROMO_CODE_USAGE_LIMIT_REACHED",
  PROMO_CODE_MIN_DAYS_NOT_MET: "PROMO_CODE_MIN_DAYS_NOT_MET",
  PROMO_CODE_MIN_AMOUNT_NOT_MET: "PROMO_CODE_MIN_AMOUNT_NOT_MET",
  // Owner Settlements Error Codes (Sprint 21: DOM-003 §41-45)
  SETTLEMENT_NOT_FOUND: "SETTLEMENT_NOT_FOUND",
  SETTLEMENT_PERIOD_NOT_FOUND: "SETTLEMENT_PERIOD_NOT_FOUND",
  SETTLEMENT_PERIOD_CLOSED: "SETTLEMENT_PERIOD_CLOSED",
  SETTLEMENT_PERIOD_DATE_CONFLICT: "SETTLEMENT_PERIOD_DATE_CONFLICT",
  SETTLEMENT_ALREADY_EXISTS: "SETTLEMENT_ALREADY_EXISTS",
  SETTLEMENT_ALREADY_APPROVED: "SETTLEMENT_ALREADY_APPROVED",
  SETTLEMENT_ALREADY_PAID: "SETTLEMENT_ALREADY_PAID",
  SETTLEMENT_DISPUTED_BLOCKED: "SETTLEMENT_DISPUTED_BLOCKED",
  SETTLEMENT_NOT_CALCULATED: "SETTLEMENT_NOT_CALCULATED",
  SETTLEMENT_NOT_APPROVED: "SETTLEMENT_NOT_APPROVED",
  SETTLEMENT_PAYABLE_NOT_FOUND: "SETTLEMENT_PAYABLE_NOT_FOUND",
  SETTLEMENT_PAYABLE_ALREADY_EXECUTED: "SETTLEMENT_PAYABLE_ALREADY_EXECUTED",
  SETTLEMENT_CONCURRENCY_CONFLICT: "SETTLEMENT_CONCURRENCY_CONFLICT",
  SETTLEMENT_INVALID_TRANSITION: "SETTLEMENT_INVALID_TRANSITION",
  SETTLEMENT_BATCH_FAILED: "SETTLEMENT_BATCH_FAILED",
  // Website CMS & Branding Error Codes (Sprint 29: ARCH-001, DEV-008)
  WEBSITE_NOT_FOUND: "WEBSITE_NOT_FOUND",
  WEBPAGE_NOT_FOUND: "WEBPAGE_NOT_FOUND",
  WEBPAGE_SLUG_EXISTS: "WEBPAGE_SLUG_EXISTS",
  STANDARD_PAGE_CANNOT_BE_DELETED: "STANDARD_PAGE_CANNOT_BE_DELETED",
  DOMAIN_ALREADY_REGISTERED: "DOMAIN_ALREADY_REGISTERED",
  DOMAIN_VERIFICATION_FAILED: "DOMAIN_VERIFICATION_FAILED",
  DOMAIN_NOT_FOUND: "DOMAIN_NOT_FOUND",
  INVALID_CONTENT_BLOCK: "INVALID_CONTENT_BLOCK",
  WEBSITE_UNPUBLISHED: "WEBSITE_UNPUBLISHED",
  CROSS_TENANT_WEBSITE_DENIED: "CROSS_TENANT_WEBSITE_DENIED",
  // Domain Routing & TLS Error Codes (Sprint 30: TEN-001, DEV-009, SEC-001)
  DOMAIN_NOT_ROUTABLE: "DOMAIN_NOT_ROUTABLE",
  DOMAIN_ENTITLEMENT_REQUIRED: "DOMAIN_ENTITLEMENT_REQUIRED",
  CANNOT_DELETE_PLATFORM_SUBDOMAIN: "CANNOT_DELETE_PLATFORM_SUBDOMAIN",
  RESERVED_SUBDOMAIN: "RESERVED_SUBDOMAIN",
  CROSS_TENANT_DOMAIN_DENIED: "CROSS_TENANT_DOMAIN_DENIED",
  INVALID_DOMAIN_FORMAT: "INVALID_DOMAIN_FORMAT",
  DOMAIN_VERIFICATION_RATE_LIMITED: "DOMAIN_VERIFICATION_RATE_LIMITED",
} as const;

export const AUTH_CONFIG = {
  ACCESS_TOKEN_TTL_SEC: 900, // 15 minutes
  REFRESH_TOKEN_TTL_SEC: 604800, // 7 days
  PASSWORD_RESET_TOKEN_TTL_SEC: 3600, // 1 hour
  EMAIL_VERIFICATION_TOKEN_TTL_SEC: 86400, // 24 hours
  MAX_LOGIN_ATTEMPTS_PER_WINDOW: 5,
  RATE_LIMIT_WINDOW_SEC: 300, // 5 minutes
  JWT_ISSUER: "carhire-os-identity",
  JWT_AUDIENCE: "carhire-os-api",
} as const;


export * from "./access";
