// ============================================================================
// CAR HIRE OS — CANONICAL PERMISSION REGISTRY (DEV-005, DOM-003 §8, SEC-005)
// Resource.Action Format with Full Namespace Metadata
// ============================================================================

export interface PermissionDefinition {
  key: string;
  resource: string;
  action: string;
  name: string;
  description: string;
  scope: "TENANT" | "PLATFORM";
  riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
}

// ----------------------------------------------------------------------------
// 1. TENANT-SCOPED PERMISSION REGISTRY
// ----------------------------------------------------------------------------
export const TENANT_PERMISSIONS = {
  // Tenant & Organization
  TENANT_READ: "tenant.read",
  TENANT_UPDATE: "tenant.update",
  TENANT_SETTINGS_READ: "tenant.settings.read",
  TENANT_SETTINGS_UPDATE: "tenant.settings.update",

  // Users & Memberships
  USER_READ: "user.read",
  USER_INVITE: "user.invite",
  USER_UPDATE: "user.update",
  USER_REMOVE: "user.remove",

  // Roles & Access Control
  ROLE_READ: "role.read",
  ROLE_CREATE: "role.create",
  ROLE_UPDATE: "role.update",
  ROLE_DELETE: "role.delete",
  ROLE_ASSIGN: "role.assign",

  // Branch & Locations
  BRANCH_READ: "branch.read",
  BRANCH_CREATE: "branch.create",
  BRANCH_UPDATE: "branch.update",
  BRANCH_DELETE: "branch.delete",

  // Fleet & Vehicles
  VEHICLE_READ: "vehicle.read",
  VEHICLE_CREATE: "vehicle.create",
  VEHICLE_UPDATE: "vehicle.update",
  VEHICLE_DELETE: "vehicle.delete",
  VEHICLE_STATUS_OVERRIDE: "vehicle.status_override",

  // Vehicle Owners & Partnerships
  VEHICLE_OWNER_READ: "vehicle_owner.read",
  VEHICLE_OWNER_CREATE: "vehicle_owner.create",
  VEHICLE_OWNER_UPDATE: "vehicle_owner.update",
  VEHICLE_OWNER_DELETE: "vehicle_owner.delete",
  VEHICLE_OWNERSHIP_MANAGE: "vehicle_ownership.manage",

  // Drivers
  DRIVER_READ: "driver.read",
  DRIVER_CREATE: "driver.create",
  DRIVER_UPDATE: "driver.update",
  DRIVER_DELETE: "driver.delete",
  DRIVER_ASSIGN: "driver.assign",

  // Customers & Corporate Accounts
  CUSTOMER_READ: "customer.read",
  CUSTOMER_CREATE: "customer.create",
  CUSTOMER_UPDATE: "customer.update",
  CUSTOMER_DELETE: "customer.delete",
  CUSTOMER_VERIFY: "customer.verify",
  CUSTOMER_BLOCK: "customer.block",

  // Pricing & Rate Engine (Sprint 11: DEV-005, DEV-007, BRS-001)
  PRICING_READ: "pricing.read",
  PRICING_CREATE: "pricing.create",
  PRICING_UPDATE: "pricing.update",
  PRICING_ACTIVATE: "pricing.activate",
  PRICING_ARCHIVE: "pricing.archive",
  PRICING_CALCULATE: "pricing.calculate",
  PRICING_PROMO_MANAGE: "pricing.promo.manage",
  PRICING_RATE_PLAN_READ: "pricing.rate_plan.read",
  PRICING_RATE_PLAN_MANAGE: "pricing.rate_plan.manage",
  PRICING_OVERRIDE_APPLY: "pricing.override.apply",

  // Agents, Leads & Quotes
  AGENT_READ: "agent.read",
  AGENT_MANAGE: "agent.manage",
  LEAD_READ: "lead.read",
  LEAD_MANAGE: "lead.manage",
  QUOTE_CREATE: "quote.create",
  QUOTE_READ: "quote.read",

  // Leads, Quotes & CRM Pipeline (Sprint 33)
  CRM_LEAD_READ: "crm.lead.read",
  CRM_LEAD_CREATE: "crm.lead.create",
  CRM_LEAD_UPDATE: "crm.lead.update",
  CRM_LEAD_ASSIGN: "crm.lead.assign",
  CRM_LEAD_QUALIFY: "crm.lead.qualify",
  CRM_LEAD_CONVERT: "crm.lead.convert",
  CRM_LEAD_DELETE: "crm.lead.delete",
  CRM_QUOTE_READ: "crm.quote.read",
  CRM_QUOTE_CREATE: "crm.quote.create",
  CRM_QUOTE_UPDATE: "crm.quote.update",
  CRM_QUOTE_SEND: "crm.quote.send",
  CRM_QUOTE_ACCEPT: "crm.quote.accept",
  CRM_QUOTE_CONVERT: "crm.quote.convert",
  CRM_TASK_MANAGE: "crm.task.manage",
  CRM_ACTIVITY_CREATE: "crm.activity.create",
  CRM_SETTINGS_MANAGE: "crm.settings.manage",

  // Bookings
  BOOKING_READ: "booking.read",
  BOOKING_CREATE: "booking.create",
  BOOKING_UPDATE: "booking.update",
  BOOKING_CONFIRM: "booking.confirm",
  BOOKING_CANCEL: "booking.cancel",
  BOOKING_SUBSTITUTE_VEHICLE: "booking.substitute_vehicle",

  // Rentals
  RENTAL_READ: "rental.read",
  RENTAL_CREATE: "rental.create",
  RENTAL_UPDATE: "rental.update",
  RENTAL_START: "rental.start",
  RENTAL_EXTEND: "rental.extend",
  RENTAL_COMPLETE: "rental.complete", // legacy broad permission; staged return commands use granular permissions below
  RENTAL_INCIDENT_REPORT: "rental.incident_report",
  RENTAL_RETURN_SCHEDULE: "rental.return_schedule",
  RENTAL_RETURN_RECEIVE: "rental.return_receive",
  RENTAL_RETURN_INSPECTION_LINK: "rental.return_inspection_link",
  RENTAL_FINAL_CALCULATE: "rental.final_calculate",
  RENTAL_FINAL_SETTLE: "rental.final_settle",
  RENTAL_FINAL_COMPLETE: "rental.final_complete",

  // Inspections & Damages
  INSPECTION_READ: "inspection.read",
  INSPECTION_CREATE: "inspection.create",
  INSPECTION_SIGN: "inspection.sign",
  INSPECTION_COMPLETE: "inspection.complete",
  INSPECTION_VOID: "inspection.void",
  INSPECTION_AMEND: "inspection.amend",
  INSPECTION_PERFORM: "inspection.perform",
  DAMAGE_READ: "damage.read",
  DAMAGE_RECORD: "damage.record",
  DAMAGE_ASSESS: "damage.assess",
  DAMAGE_UPDATE: "damage.update",
  DAMAGE_RESOLVE: "damage.resolve",
  EVIDENCE_READ: "inspection.evidence.read",
  EVIDENCE_CREATE: "inspection.evidence.create",

  // Maintenance & Compliance
  MAINTENANCE_READ: "maintenance.read",
  MAINTENANCE_CREATE: "maintenance.create",
  MAINTENANCE_UPDATE: "maintenance.update",
  MAINTENANCE_SCHEDULE: "maintenance.schedule",
  MAINTENANCE_START: "maintenance.start",
  MAINTENANCE_COMPLETE: "maintenance.complete",
  MAINTENANCE_VERIFY: "maintenance.verify",
  MAINTENANCE_PROVIDER_MANAGE: "maintenance.provider.manage",
  COMPLIANCE_READ: "compliance.read",
  COMPLIANCE_UPLOAD: "compliance.upload",
  COMPLIANCE_VERIFY: "compliance.verify",
  COMPLIANCE_OVERRIDE: "compliance.override",

  // Contracts
  CONTRACT_READ: "contract.read",
  CONTRACT_GENERATE: "contract.generate",
  CONTRACT_SIGN: "contract.sign",

  // Payments & Refunds
  PAYMENT_READ: "payment.read",
  PAYMENT_RECORD: "payment.record",
  PAYMENT_VOID: "payment.void",
  PAYMENT_INITIATE: "payment.initiate",
  PAYMENT_VERIFY: "payment.verify",
  PAYMENT_ALLOCATE: "payment.allocate",
  PAYMENT_RECONCILIATION_READ: "payment.reconciliation.read",
  PAYMENT_RECONCILIATION_RUN: "payment.reconciliation.run",
  PAYMENT_RECONCILIATION_RESOLVE: "payment.reconciliation.resolve",
  REFUND_READ: "refund.read",
  REFUND_CREATE: "refund.create",
  REFUND_APPROVE: "refund.approve",

  // Invoices & Operational Finance
  INVOICE_READ: "invoice.read",
  INVOICE_CREATE: "invoice.create",
  INVOICE_ISSUE: "invoice.issue",
  INVOICE_VOID: "invoice.void",
  CREDIT_NOTE_READ: "credit_note.read",
  CREDIT_NOTE_CREATE: "credit_note.create",
  CREDIT_NOTE_ISSUE: "credit_note.issue",
  CREDIT_NOTE_VOID: "credit_note.void",
  EXPENSE_READ: "expense.read",
  EXPENSE_CREATE: "expense.create",
  EXPENSE_SUBMIT: "expense.submit",
  EXPENSE_APPROVE: "expense.approve",
  EXPENSE_REJECT: "expense.reject",
  EXPENSE_VOID: "expense.void",
  DEPOSIT_READ: "deposit.read",
  DEPOSIT_APPLY: "deposit.apply",
  FINANCE_READ: "finance.read",
  RECEIVABLES_READ: "receivables.read",

  // General Ledger & Double-Entry Accounting (Sprint 20)
  LEDGER_ACCOUNT_READ: "ledger.account.read",
  LEDGER_ACCOUNT_MANAGE: "ledger.account.manage",
  LEDGER_READ: "ledger.read",
  LEDGER_JOURNAL_POST: "ledger.journal.post",
  LEDGER_JOURNAL_REVERSE: "ledger.journal.reverse",
  LEDGER_MANUAL_JOURNAL_CREATE: "ledger.manual_journal.create",
  LEDGER_MANUAL_JOURNAL_APPROVE: "ledger.manual_journal.approve",
  LEDGER_TRIAL_BALANCE_READ: "ledger.trial_balance.read",

  // Settlements
  SETTLEMENT_READ: "settlement.read",
  SETTLEMENT_CALCULATE: "settlement.calculate",
  SETTLEMENT_APPROVE: "settlement.approve",
  SETTLEMENT_PAY: "settlement.pay",
  SETTLEMENT_DISPUTE: "settlement.dispute",
  SETTLEMENT_PERIOD_MANAGE: "settlement.period.manage",
  SETTLEMENT_BATCH_GENERATE: "settlement.batch.generate",
  SETTLEMENT_STATEMENT_EXPORT: "settlement.statement.export",

  // Website CMS, Branding & Public Storefront (Sprint 29: ARCH-001, DEV-008)
  WEBSITE_READ: "website.read",
  WEBSITE_UPDATE: "website.update",
  WEBSITE_MANAGE: "website.manage",
  WEBSITE_PUBLISH: "website.publish",
  WEBSITE_DOMAIN_MANAGE: "website.domain.manage",
  DOMAIN_MANAGE: "domain.manage",

  // Media, Reports & Analytics
  MEDIA_READ: "media.read",
  MEDIA_UPLOAD: "media.upload",
  MEDIA_MANAGE: "media.manage",
  MEDIA_REGENERATE: "media.regenerate",
  MEDIA_PUBLIC_PUBLISH: "media.public.publish",
  MEDIA_DELETE: "media.delete",

  REPORT_READ: "report.read",
  REPORT_EXPORT: "report.export",
  ANALYTICS_READ: "analytics.read",

  // Secure Files & Enterprise Documents (Sprint 27)
  FILE_READ: "file.read",
  FILE_UPLOAD: "file.upload",
  FILE_ARCHIVE: "file.archive",
  FILE_DELETE: "file.delete",
  DOCUMENT_READ: "document.read",
  DOCUMENT_UPLOAD: "document.upload",
  DOCUMENT_REPLACE: "document.replace",
  DOCUMENT_SENSITIVE_READ: "document.sensitive.read",
  DOCUMENT_VERIFY: "document.verify",

  // Notifications & Integrations
  NOTIFICATION_MANAGE: "notification.manage",
  INTEGRATION_MANAGE: "integration.manage",

  // Audit
  AUDIT_READ: "audit.read",

  // Subscription & SaaS Billing (Tenant scope)
  SUBSCRIPTION_READ: "subscription.read",
  SUBSCRIPTION_CANCEL: "subscription.cancel",
  SUBSCRIPTION_UPGRADE: "subscription.upgrade",
  BILLING_READ: "billing.read",
  ENTITLEMENT_READ: "entitlement.read",
} as const;

// ----------------------------------------------------------------------------
// 2. PLATFORM-SCOPED PERMISSION REGISTRY
// ----------------------------------------------------------------------------
export const PLATFORM_PERMISSIONS = {
  // Platform Tenant Management
  PLATFORM_TENANT_READ: "platform.tenant.read",
  PLATFORM_TENANT_PROVISION: "platform.tenant.provision",
  PLATFORM_TENANT_SUSPEND: "platform.tenant.suspend",
  PLATFORM_TENANT_DELETE: "platform.tenant.delete",

  // Platform User Management
  PLATFORM_USER_READ: "platform.user.read",
  PLATFORM_USER_MANAGE: "platform.user.manage",

  // Platform Plan & Billing Control (Sprint 6: Control Plane SaaS Billing)
  PLATFORM_PLAN_READ: "platform.plan.read",
  PLATFORM_PLAN_CREATE: "platform.plan.create",
  PLATFORM_PLAN_UPDATE: "platform.plan.update",
  PLATFORM_PLAN_ARCHIVE: "platform.plan.archive",
  PLATFORM_PLAN_MANAGE: "platform.plan.manage",
  PLATFORM_SUBSCRIPTION_READ: "platform.subscription.read",
  PLATFORM_SUBSCRIPTION_CREATE: "platform.subscription.create",
  PLATFORM_SUBSCRIPTION_UPDATE: "platform.subscription.update",
  PLATFORM_SUBSCRIPTION_SUSPEND: "platform.subscription.suspend",
  PLATFORM_SUBSCRIPTION_REACTIVATE: "platform.subscription.reactivate",
  PLATFORM_SUBSCRIPTION_CANCEL: "platform.subscription.cancel",
  PLATFORM_BILLING_READ: "platform.billing.read",
  PLATFORM_BILLING_MANAGE: "platform.billing.manage",
  PLATFORM_BILLING_ADJUST: "platform.billing.adjust",
  PLATFORM_BILLING_RECORD_PAYMENT: "platform.billing.record_payment",

  // Platform Feature Registry & Entitlement Control (Sprint 7: Entitlement Engine)
  PLATFORM_FEATURE_READ: "platform.feature.read",
  PLATFORM_FEATURE_MANAGE: "platform.feature.manage",
  PLATFORM_ENTITLEMENT_READ: "platform.entitlement.read",
  PLATFORM_ENTITLEMENT_OVERRIDE: "platform.entitlement.override",
  PLATFORM_ENTITLEMENT_RESTRICT: "platform.entitlement.restrict",

  // Platform Support & Audited Impersonation
  PLATFORM_SUPPORT_SESSION_START: "platform.support.session_start",
  PLATFORM_SUPPORT_SESSION_END: "platform.support.session_end",
  PLATFORM_SUPPORT_ACCESS: "platform.support.access",

  // Platform Domains & Infrastructure (Sprint 37)
  PLATFORM_DOMAIN_READ: "platform.domain.read",
  PLATFORM_DOMAIN_MANAGE: "platform.domain.manage",

  // Platform Provider Diagnostics & Payments (Sprint 37)
  PLATFORM_PAYMENT_READ: "platform.payment.read",
  PLATFORM_PAYMENT_RECONCILE: "platform.payment.reconcile",

  // Platform Notification Delivery & Retries (Sprint 37)
  PLATFORM_NOTIFICATION_READ: "platform.notification.read",
  PLATFORM_NOTIFICATION_RETRY: "platform.notification.retry",

  // Platform Background Queues & DLQ (Sprint 37)
  PLATFORM_JOB_READ: "platform.job.read",
  PLATFORM_JOB_RETRY: "platform.job.retry",

  // Platform Reports & Configuration (Sprint 37)
  PLATFORM_REPORT_EXPORT: "platform.report.export",
  PLATFORM_CONFIG_MANAGE: "platform.config.manage",

  // Platform Audit & Observability
  PLATFORM_AUDIT_READ: "platform.audit.read",
  PLATFORM_ANALYTICS_READ: "platform.analytics.read",
  PLATFORM_COMPLIANCE_READ: "platform.compliance.read",
} as const;

export type TenantPermissionKey = (typeof TENANT_PERMISSIONS)[keyof typeof TENANT_PERMISSIONS];
export type PlatformPermissionKey = (typeof PLATFORM_PERMISSIONS)[keyof typeof PLATFORM_PERMISSIONS];
export type PermissionKey = TenantPermissionKey | PlatformPermissionKey;

// ----------------------------------------------------------------------------
// 3. CANONICAL PERMISSION DEFINITIONS METADATA
// ----------------------------------------------------------------------------
export const ALL_PERMISSION_DEFINITIONS: PermissionDefinition[] = [
  // Tenant
  {
    key: TENANT_PERMISSIONS.TENANT_READ,
    resource: "tenant",
    action: "read",
    name: "View Organization Details",
    description: "Read workspace metadata, profile, and active parameters",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.TENANT_UPDATE,
    resource: "tenant",
    action: "update",
    name: "Update Organization Details",
    description: "Update workspace contact info, address, and profile settings",
    scope: "TENANT",
    riskLevel: "HIGH",
  },
  {
    key: TENANT_PERMISSIONS.TENANT_SETTINGS_READ,
    resource: "tenant_settings",
    action: "read",
    name: "View Tenant Settings",
    description: "View VAT, M-Pesa, GPS, fuel and security deposit defaults",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.TENANT_SETTINGS_UPDATE,
    resource: "tenant_settings",
    action: "update",
    name: "Update Tenant Settings",
    description: "Modify financial rates, M-Pesa credentials, and operational policies",
    scope: "TENANT",
    riskLevel: "CRITICAL",
  },

  // Users & Memberships
  {
    key: TENANT_PERMISSIONS.USER_READ,
    resource: "user",
    action: "read",
    name: "View Workspace Members",
    description: "View list of users and active memberships within the tenant",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.USER_INVITE,
    resource: "user",
    action: "invite",
    name: "Invite Workspace Members",
    description: "Invite new team members and assign initial roles",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.USER_UPDATE,
    resource: "user",
    action: "update",
    name: "Update Member Profile",
    description: "Edit team member status or membership attributes",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.USER_REMOVE,
    resource: "user",
    action: "remove",
    name: "Remove Workspace Member",
    description: "Revoke team member access and remove membership",
    scope: "TENANT",
    riskLevel: "HIGH",
  },

  // Roles
  {
    key: TENANT_PERMISSIONS.ROLE_READ,
    resource: "role",
    action: "read",
    name: "View Roles & Permissions",
    description: "Read system and custom tenant roles and permission grants",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.ROLE_CREATE,
    resource: "role",
    action: "create",
    name: "Create Custom Role",
    description: "Create new custom tenant roles with selected permissions",
    scope: "TENANT",
    riskLevel: "HIGH",
  },
  {
    key: TENANT_PERMISSIONS.ROLE_UPDATE,
    resource: "role",
    action: "update",
    name: "Update Custom Role",
    description: "Modify role name, description, and permission assignments",
    scope: "TENANT",
    riskLevel: "HIGH",
  },
  {
    key: TENANT_PERMISSIONS.ROLE_DELETE,
    resource: "role",
    action: "delete",
    name: "Delete Custom Role",
    description: "Deactivate or delete unassigned custom roles",
    scope: "TENANT",
    riskLevel: "HIGH",
  },
  {
    key: TENANT_PERMISSIONS.ROLE_ASSIGN,
    resource: "role",
    action: "assign",
    name: "Assign Roles to Members",
    description: "Assign or revoke roles on tenant memberships",
    scope: "TENANT",
    riskLevel: "CRITICAL",
  },

  // Fleet & Vehicles
  {
    key: TENANT_PERMISSIONS.VEHICLE_READ,
    resource: "vehicle",
    action: "read",
    name: "View Vehicles",
    description: "Browse fleet roster, specifications, and availability",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.VEHICLE_CREATE,
    resource: "vehicle",
    action: "create",
    name: "Add New Vehicle",
    description: "Onboard new vehicle to the fleet",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.VEHICLE_UPDATE,
    resource: "vehicle",
    action: "update",
    name: "Update Vehicle",
    description: "Edit vehicle specs, rates, photo, odometer, or status",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.VEHICLE_DELETE,
    resource: "vehicle",
    action: "delete",
    name: "Decommission Vehicle",
    description: "Retire or remove a vehicle from active fleet",
    scope: "TENANT",
    riskLevel: "HIGH",
  },
  {
    key: TENANT_PERMISSIONS.VEHICLE_STATUS_OVERRIDE,
    resource: "vehicle",
    action: "status_override",
    name: "Override Vehicle Status",
    description: "Force operational status override on blocked or maintenance vehicle",
    scope: "TENANT",
    riskLevel: "HIGH",
  },

  // Vehicle Owners
  {
    key: TENANT_PERMISSIONS.VEHICLE_OWNER_READ,
    resource: "vehicle_owner",
    action: "read",
    name: "View Vehicle Owners",
    description: "View list of 3rd-party asset owners and contact profiles",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.VEHICLE_OWNER_CREATE,
    resource: "vehicle_owner",
    action: "create",
    name: "Register Vehicle Owner",
    description: "Onboard new vehicle owner and banking/M-Pesa details",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.VEHICLE_OWNER_UPDATE,
    resource: "vehicle_owner",
    action: "update",
    name: "Update Vehicle Owner",
    description: "Modify owner details, tax pin, and payout coordinates",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.VEHICLE_OWNER_DELETE,
    resource: "vehicle_owner",
    action: "delete",
    name: "Delete Vehicle Owner",
    description: "Archive or delete inactive vehicle owner",
    scope: "TENANT",
    riskLevel: "HIGH",
  },
  {
    key: TENANT_PERMISSIONS.VEHICLE_OWNERSHIP_MANAGE,
    resource: "vehicle_ownership",
    action: "manage",
    name: "Manage Vehicle Ownership Contracts",
    description: "Configure revenue share split, fixed payouts, and agreement terms",
    scope: "TENANT",
    riskLevel: "HIGH",
  },

  // Drivers
  {
    key: TENANT_PERMISSIONS.DRIVER_READ,
    resource: "driver",
    action: "read",
    name: "View Drivers",
    description: "View registered chauffeur and staff driver directory",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.DRIVER_CREATE,
    resource: "driver",
    action: "create",
    name: "Register Driver",
    description: "Add new driver with license and medical certification",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.DRIVER_UPDATE,
    resource: "driver",
    action: "update",
    name: "Update Driver",
    description: "Edit driver details, duty status, and certifications",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.DRIVER_DELETE,
    resource: "driver",
    action: "delete",
    name: "Remove Driver",
    description: "Deactivate or delete driver record",
    scope: "TENANT",
    riskLevel: "HIGH",
  },
  {
    key: TENANT_PERMISSIONS.DRIVER_ASSIGN,
    resource: "driver",
    action: "assign",
    name: "Assign Driver to Bookings/Rentals",
    description: "Dispatch driver to active bookings or chauffeur duties",
    scope: "TENANT",
    riskLevel: "LOW",
  },

  // Customers
  {
    key: TENANT_PERMISSIONS.CUSTOMER_READ,
    resource: "customer",
    action: "read",
    name: "View Customers",
    description: "View customer list, verification records, and rental history",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.CUSTOMER_CREATE,
    resource: "customer",
    action: "create",
    name: "Create Customer",
    description: "Register new customer profile and identity documents",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.CUSTOMER_UPDATE,
    resource: "customer",
    action: "update",
    name: "Update Customer",
    description: "Update customer contacts, address, and license data",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.CUSTOMER_DELETE,
    resource: "customer",
    action: "delete",
    name: "Delete Customer",
    description: "Archive customer account",
    scope: "TENANT",
    riskLevel: "HIGH",
  },
  {
    key: TENANT_PERMISSIONS.CUSTOMER_VERIFY,
    resource: "customer",
    action: "verify",
    name: "Verify Customer Identity",
    description: "Approve customer DL/ID verification status",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.CUSTOMER_BLOCK,
    resource: "customer",
    action: "block",
    name: "Blacklist / Restrict Customer",
    description: "Block customer from creating new reservations",
    scope: "TENANT",
    riskLevel: "HIGH",
  },

  // Bookings
  {
    key: TENANT_PERMISSIONS.BOOKING_READ,
    resource: "booking",
    action: "read",
    name: "View Bookings",
    description: "Read reservations, calendar schedules, and pricing snapshots",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.BOOKING_CREATE,
    resource: "booking",
    action: "create",
    name: "Create Booking",
    description: "Create draft, walk-in, or desk reservations",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.BOOKING_UPDATE,
    resource: "booking",
    action: "update",
    name: "Modify Booking",
    description: "Update dates, vehicle, pricing addons, or customer assignment",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.BOOKING_CONFIRM,
    resource: "booking",
    action: "confirm",
    name: "Confirm Booking",
    description: "Mark booking confirmed after deposit or pre-auth receipt",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.BOOKING_CANCEL,
    resource: "booking",
    action: "cancel",
    name: "Cancel Booking",
    description: "Cancel confirmed or pending booking and trigger refund workflow",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.BOOKING_SUBSTITUTE_VEHICLE,
    resource: "booking",
    action: "substitute_vehicle",
    name: "Substitute Booking Vehicle",
    description: "Perform vehicle substitution on an active or pending reservation",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },

  // Rentals
  {
    key: TENANT_PERMISSIONS.RENTAL_READ,
    resource: "rental",
    action: "read",
    name: "View Active Rentals",
    description: "Monitor on-road fleet contracts and active rental agreements",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.RENTAL_START,
    resource: "rental",
    action: "start",
    name: "Handover & Start Rental",
    description: "Dispatch vehicle, execute handover inspection, and release keys",
    scope: "TENANT",
    riskLevel: "HIGH",
  },
  {
    key: TENANT_PERMISSIONS.RENTAL_EXTEND,
    resource: "rental",
    action: "extend",
    name: "Extend Rental Contract",
    description: "Approve rental date extension and recalculate gross total",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.RENTAL_COMPLETE,
    resource: "rental",
    action: "complete",
    name: "Check-in & Complete Rental",
    description: "Perform return check-in, finalize excess mileage/fuel/damage charges",
    scope: "TENANT",
    riskLevel: "HIGH",
  },
  {
    key: TENANT_PERMISSIONS.RENTAL_INCIDENT_REPORT,
    resource: "rental",
    action: "incident_report",
    name: "Report Rental Incident",
    description: "Record accidents, breakdowns, or traffic infractions",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.RENTAL_RETURN_SCHEDULE,
    resource: "rental",
    action: "return_schedule",
    name: "Schedule Rental Return",
    description: "Move an on-road rental into the formal return workflow",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.RENTAL_RETURN_RECEIVE,
    resource: "rental",
    action: "return_receive",
    name: "Receive Returned Vehicle",
    description: "Capture physical vehicle receipt, return odometer, fuel, time and location",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.RENTAL_RETURN_INSPECTION_LINK,
    resource: "rental",
    action: "return_inspection_link",
    name: "Advance Rental From Return Inspection",
    description: "Link a sealed canonical return inspection and advance the rental into damage assessment",
    scope: "TENANT",
    riskLevel: "HIGH",
  },
  {
    key: TENANT_PERMISSIONS.RENTAL_FINAL_CALCULATE,
    resource: "rental",
    action: "final_calculate",
    name: "Calculate Final Rental Charges",
    description: "Generate the authoritative final charge calculation from sealed rental and return evidence",
    scope: "TENANT",
    riskLevel: "HIGH",
  },
  {
    key: TENANT_PERMISSIONS.RENTAL_FINAL_SETTLE,
    resource: "rental",
    action: "final_settle",
    name: "Settle Rental Deposit / Balance",
    description: "Seal the deposit refund, additional customer balance or zero-balance settlement outcome",
    scope: "TENANT",
    riskLevel: "CRITICAL",
  },
  {
    key: TENANT_PERMISSIONS.RENTAL_FINAL_COMPLETE,
    resource: "rental",
    action: "final_complete",
    name: "Complete Rental Lifecycle",
    description: "Close the rental, booking and contract after sealed settlement and apply final vehicle disposition",
    scope: "TENANT",
    riskLevel: "HIGH",
  },

  // Inspections & Damages
  {
    key: TENANT_PERMISSIONS.INSPECTION_READ,
    resource: "inspection",
    action: "read",
    name: "View Inspection Reports",
    description: "Browse digital inspection sheets, photos, and checklists",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.INSPECTION_CREATE,
    resource: "inspection",
    action: "create",
    name: "Perform Vehicle Inspection",
    description: "Record 15-point inspection, fuel level, and odometer reading",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.INSPECTION_SIGN,
    resource: "inspection",
    action: "sign",
    name: "Capture Signatures",
    description: "Sign handover and return inspection reports",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.DAMAGE_RECORD,
    resource: "damage",
    action: "record",
    name: "Log Vehicle Damage",
    description: "Pin damage zones, upload photos, and classify severity",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.DAMAGE_ASSESS,
    resource: "damage",
    action: "assess",
    name: "Assess Damage Repair Cost",
    description: "Estimate repair cost and assign responsible party",
    scope: "TENANT",
    riskLevel: "HIGH",
  },

  // Maintenance & Compliance
  {
    key: TENANT_PERMISSIONS.MAINTENANCE_READ,
    resource: "maintenance",
    action: "read",
    name: "View Maintenance Records",
    description: "View workshop repair logs and service schedules",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.MAINTENANCE_CREATE,
    resource: "maintenance",
    action: "create",
    name: "Log Maintenance / Service",
    description: "Create workshop job card, cost, and blocked availability",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.MAINTENANCE_COMPLETE,
    resource: "maintenance",
    action: "complete",
    name: "Complete Maintenance",
    description: "Mark vehicle repaired and restore to available roster",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.COMPLIANCE_READ,
    resource: "compliance",
    action: "read",
    name: "View Compliance Documents",
    description: "View insurance, inspection, PSV, and DL expiry tracker",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.COMPLIANCE_UPLOAD,
    resource: "compliance",
    action: "upload",
    name: "Upload Compliance Certificates",
    description: "Upload and update regulatory renewal documents",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.COMPLIANCE_VERIFY,
    resource: "compliance",
    action: "verify",
    name: "Verify Regulatory Documents",
    description: "Approve commercial insurance and inspection certificates",
    scope: "TENANT",
    riskLevel: "HIGH",
  },
  {
    key: TENANT_PERMISSIONS.COMPLIANCE_OVERRIDE,
    resource: "compliance",
    action: "override",
    name: "Emergency Compliance Override",
    description: "Override compliance lock on a vehicle for emergency operations",
    scope: "TENANT",
    riskLevel: "CRITICAL",
  },

  // Contracts
  {
    key: TENANT_PERMISSIONS.CONTRACT_READ,
    resource: "contract",
    action: "read",
    name: "View Rental Agreements",
    description: "View legal rental contracts and terms snapshots",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.CONTRACT_GENERATE,
    resource: "contract",
    action: "generate",
    name: "Generate Rental Agreement",
    description: "Compile official PDF rental contract",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.CONTRACT_SIGN,
    resource: "contract",
    action: "sign",
    name: "Sign Rental Agreement",
    description: "Counter-sign legal rental contract on behalf of tenant",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },

  // Payments & Refunds
  {
    key: TENANT_PERMISSIONS.PAYMENT_READ,
    resource: "payment",
    action: "read",
    name: "View Payments & Transactions",
    description: "View M-Pesa receipts, card transactions, and cash logs",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.PAYMENT_RECORD,
    resource: "payment",
    action: "record",
    name: "Record Manual Payment",
    description: "Record cash, bank transfer, or offline payment",
    scope: "TENANT",
    riskLevel: "HIGH",
  },
  {
    key: TENANT_PERMISSIONS.PAYMENT_VOID,
    resource: "payment",
    action: "void",
    name: "Void Payment Record",
    description: "Void erroneous payment transaction with audit record",
    scope: "TENANT",
    riskLevel: "CRITICAL",
  },
  {
    key: TENANT_PERMISSIONS.PAYMENT_INITIATE,
    resource: "payment",
    action: "initiate",
    name: "Initiate Customer Payment",
    description: "Create a provider payment attempt without treating browser initiation as payment success",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.PAYMENT_VERIFY,
    resource: "payment",
    action: "verify",
    name: "Verify Provider Payment",
    description: "Query or accept authoritative provider evidence and create the verified Payment fact",
    scope: "TENANT",
    riskLevel: "HIGH",
  },
  {
    key: TENANT_PERMISSIONS.PAYMENT_ALLOCATE,
    resource: "payment",
    action: "allocate",
    name: "Allocate Verified Payment",
    description: "Allocate verified money to invoices, deposits or supported obligations",
    scope: "TENANT",
    riskLevel: "HIGH",
  },
  {
    key: TENANT_PERMISSIONS.PAYMENT_RECONCILIATION_READ,
    resource: "payment_reconciliation",
    action: "read",
    name: "View Payment Reconciliation Issues",
    description: "View unmatched, stale or inconsistent provider/payment records",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.PAYMENT_RECONCILIATION_RUN,
    resource: "payment_reconciliation",
    action: "run",
    name: "Run Payment Reconciliation",
    description: "Scan authoritative payment records for allocation and provider discrepancies",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.PAYMENT_RECONCILIATION_RESOLVE,
    resource: "payment_reconciliation",
    action: "resolve",
    name: "Resolve Payment Reconciliation Issue",
    description: "Mark a reviewed reconciliation exception resolved after corrective evidence exists",
    scope: "TENANT",
    riskLevel: "HIGH",
  },
  {
    key: TENANT_PERMISSIONS.REFUND_CREATE,
    resource: "refund",
    action: "create",
    name: "Initiate Refund",
    description: "Initiate security deposit or cancellation refund",
    scope: "TENANT",
    riskLevel: "HIGH",
  },
  {
    key: TENANT_PERMISSIONS.REFUND_APPROVE,
    resource: "refund",
    action: "approve",
    name: "Approve Refund Payout",
    description: "Authorize financial disbursement of refund to customer",
    scope: "TENANT",
    riskLevel: "CRITICAL",
  },

  // Invoices & Expenses
  {
    key: TENANT_PERMISSIONS.INVOICE_READ,
    resource: "invoice",
    action: "read",
    name: "View Invoices",
    description: "View customer billing invoices and tax breakdown",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.INVOICE_CREATE,
    resource: "invoice",
    action: "create",
    name: "Generate Invoices",
    description: "Issue formal customer tax invoices",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.INVOICE_VOID,
    resource: "invoice",
    action: "void",
    name: "Void Invoices",
    description: "Cancel or void issued customer invoice",
    scope: "TENANT",
    riskLevel: "HIGH",
  },
  {
    key: TENANT_PERMISSIONS.EXPENSE_READ,
    resource: "expense",
    action: "read",
    name: "View Operational Expenses",
    description: "Browse fuel, maintenance, insurance, and fleet expenses",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.EXPENSE_CREATE,
    resource: "expense",
    action: "create",
    name: "Record Expense",
    description: "Log operational expense with receipt and vehicle attribution",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.EXPENSE_APPROVE,
    resource: "expense",
    action: "approve",
    name: "Approve Expenses",
    description: "Approve logged operational expenses for ledger posting",
    scope: "TENANT",
    riskLevel: "HIGH",
  },

  // General Ledger & Accounting (Sprint 20)
  {
    key: TENANT_PERMISSIONS.LEDGER_ACCOUNT_READ,
    resource: "ledger",
    action: "account_read",
    name: "View Chart of Accounts",
    description: "Browse chart of accounts, classifications, and account balances",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.LEDGER_ACCOUNT_MANAGE,
    resource: "ledger",
    action: "account_manage",
    name: "Manage Chart of Accounts",
    description: "Create or modify non-system ledger accounts",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.LEDGER_READ,
    resource: "ledger",
    action: "read",
    name: "View General Ledger",
    description: "Browse journal transactions, journal entries, and audit references",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.LEDGER_JOURNAL_POST,
    resource: "ledger",
    action: "journal_post",
    name: "Post Ledger Journals",
    description: "Post source document contracts and automated journals to the ledger",
    scope: "TENANT",
    riskLevel: "HIGH",
  },
  {
    key: TENANT_PERMISSIONS.LEDGER_JOURNAL_REVERSE,
    resource: "ledger",
    action: "journal_reverse",
    name: "Reverse Ledger Journals",
    description: "Issue counter-entry reversal journals for posted transactions",
    scope: "TENANT",
    riskLevel: "CRITICAL",
  },
  {
    key: TENANT_PERMISSIONS.LEDGER_MANUAL_JOURNAL_CREATE,
    resource: "ledger",
    action: "manual_journal_create",
    name: "Draft Manual Journals",
    description: "Create manual adjusting journal entries in DRAFT status",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.LEDGER_MANUAL_JOURNAL_APPROVE,
    resource: "ledger",
    action: "manual_journal_approve",
    name: "Approve Manual Journals",
    description: "Approve and post manual adjusting journals under dual-control",
    scope: "TENANT",
    riskLevel: "CRITICAL",
  },
  {
    key: TENANT_PERMISSIONS.LEDGER_TRIAL_BALANCE_READ,
    resource: "ledger",
    action: "trial_balance_read",
    name: "View Trial Balance & Statements",
    description: "Generate Trial Balance and account general ledger statements",
    scope: "TENANT",
    riskLevel: "LOW",
  },

  // Settlements
  {
    key: TENANT_PERMISSIONS.SETTLEMENT_READ,
    resource: "settlement",
    action: "read",
    name: "View Owner Settlements",
    description: "View revenue share statements and calculated owner payouts",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.SETTLEMENT_CALCULATE,
    resource: "settlement",
    action: "calculate",
    name: "Calculate Owner Settlements",
    description: "Compute gross rental revenues and deduct vehicle expenses",
    scope: "TENANT",
    riskLevel: "HIGH",
  },
  {
    key: TENANT_PERMISSIONS.SETTLEMENT_APPROVE,
    resource: "settlement",
    action: "approve",
    name: "Approve Owner Settlement",
    description: "Authorize formal settlement statement for disbursement",
    scope: "TENANT",
    riskLevel: "CRITICAL",
  },
  {
    key: TENANT_PERMISSIONS.SETTLEMENT_PAY,
    resource: "settlement",
    action: "pay",
    name: "Disburse Settlement Payout",
    description: "Record M-Pesa / Bank payout reference and mark statement paid",
    scope: "TENANT",
    riskLevel: "CRITICAL",
  },

  // Website & Domain
  {
    key: TENANT_PERMISSIONS.WEBSITE_READ,
    resource: "website",
    action: "read",
    name: "View Public Website Setup",
    description: "Preview public booking portal and theme configuration",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.WEBSITE_UPDATE,
    resource: "website",
    action: "update",
    name: "Customize Website & Theme",
    description: "Edit branding, colors, hero headlines, and pages",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.WEBSITE_PUBLISH,
    resource: "website",
    action: "publish",
    name: "Publish Website",
    description: "Publish latest website changes to live public domain",
    scope: "TENANT",
    riskLevel: "HIGH",
  },
  {
    key: TENANT_PERMISSIONS.DOMAIN_MANAGE,
    resource: "domain",
    action: "manage",
    name: "Manage Custom Domains",
    description: "Configure custom CNAME and verify TLS certificates",
    scope: "TENANT",
    riskLevel: "HIGH",
  },

  // Media, Reports & Analytics
  {
    key: TENANT_PERMISSIONS.MEDIA_READ,
    resource: "media",
    action: "read",
    name: "View Media Assets",
    description: "View and access processed media assets, thumbnails, and derivatives",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.MEDIA_UPLOAD,
    resource: "media",
    action: "upload",
    name: "Upload Media & Photos",
    description: "Upload vehicle images, logos, and inspection photos",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.MEDIA_MANAGE,
    resource: "media",
    action: "manage",
    name: "Manage Media Assets",
    description: "Reorder, set primary, and manage vehicle and domain media assets",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.MEDIA_REGENERATE,
    resource: "media",
    action: "regenerate",
    name: "Regenerate Media Derivatives",
    description: "Trigger derivative regeneration across media profiles and versions",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.MEDIA_PUBLIC_PUBLISH,
    resource: "media",
    action: "publish",
    name: "Publish Public Media",
    description: "Publish approved public vehicle and website media assets",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.MEDIA_DELETE,
    resource: "media",
    action: "delete",
    name: "Delete Media Assets",
    description: "Delete uploaded media files and derivatives",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.REPORT_READ,
    resource: "report",
    action: "read",
    name: "View Operational Reports",
    description: "View fleet utilization, revenue, and maintenance summaries",
    scope: "TENANT",
    riskLevel: "LOW",
  },
  {
    key: TENANT_PERMISSIONS.REPORT_EXPORT,
    resource: "report",
    action: "export",
    name: "Export Financial & Fleet Reports",
    description: "Export CSV/PDF reports containing financial and customer data",
    scope: "TENANT",
    riskLevel: "HIGH",
  },
  {
    key: TENANT_PERMISSIONS.ANALYTICS_READ,
    resource: "analytics",
    action: "read",
    name: "View Analytics Dashboards",
    description: "Browse KPI dashboards and real-time operational graphs",
    scope: "TENANT",
    riskLevel: "LOW",
  },

  // Notifications & Integrations
  {
    key: TENANT_PERMISSIONS.NOTIFICATION_MANAGE,
    resource: "notification",
    action: "manage",
    name: "Manage Notification Templates",
    description: "Configure SMS and email templates for booking alerts",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },
  {
    key: TENANT_PERMISSIONS.INTEGRATION_MANAGE,
    resource: "integration",
    action: "manage",
    name: "Manage API & Webhook Integrations",
    description: "Generate API keys and configure external webhooks",
    scope: "TENANT",
    riskLevel: "CRITICAL",
  },

  // Audit
  {
    key: TENANT_PERMISSIONS.AUDIT_READ,
    resource: "audit",
    action: "read",
    name: "View Workspace Audit Trail",
    description: "Inspect immutable audit log of workspace actions and changes",
    scope: "TENANT",
    riskLevel: "MEDIUM",
  },

  // Subscription
  {
    key: TENANT_PERMISSIONS.SUBSCRIPTION_READ,
    resource: "subscription",
    action: "read",
    name: "View SaaS Subscription Status",
    description: "View tenant plan tier, billing cycle, and renewal dates",
    scope: "TENANT",
    riskLevel: "LOW",
  },

  // --------------------------------------------------------------------------
  // PLATFORM PERMISSIONS (Global Scope)
  // --------------------------------------------------------------------------
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_TENANT_READ,
    resource: "platform_tenant",
    action: "read",
    name: "View All Platform Tenants",
    description: "View global tenant roster, health metrics, and plan allocations",
    scope: "PLATFORM",
    riskLevel: "LOW",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_TENANT_PROVISION,
    resource: "platform_tenant",
    action: "provision",
    name: "Provision New Tenant Workspace",
    description: "Create new tenant accounts and seed initial configurations",
    scope: "PLATFORM",
    riskLevel: "HIGH",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_TENANT_SUSPEND,
    resource: "platform_tenant",
    action: "suspend",
    name: "Suspend / Reactivate Tenant",
    description: "Suspend delinquent or non-compliant tenant workspaces",
    scope: "PLATFORM",
    riskLevel: "CRITICAL",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_TENANT_DELETE,
    resource: "platform_tenant",
    action: "delete",
    name: "Delete Tenant Workspace",
    description: "Permanently delete or archive a tenant workspace",
    scope: "PLATFORM",
    riskLevel: "CRITICAL",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_USER_READ,
    resource: "platform_user",
    action: "read",
    name: "View Platform Users",
    description: "View global identity directory and verification states",
    scope: "PLATFORM",
    riskLevel: "LOW",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_USER_MANAGE,
    resource: "platform_user",
    action: "manage",
    name: "Manage Platform Staff & Users",
    description: "Manage global user statuses and platform staff memberships",
    scope: "PLATFORM",
    riskLevel: "CRITICAL",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_PLAN_READ,
    resource: "platform_plan",
    action: "read",
    name: "View SaaS Plans",
    description: "View SaaS pricing tiers, limits, and feature matrices",
    scope: "PLATFORM",
    riskLevel: "LOW",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_PLAN_MANAGE,
    resource: "platform_plan",
    action: "manage",
    name: "Manage SaaS Plans",
    description: "Create or modify SaaS plans, pricing, and vehicle quotas",
    scope: "PLATFORM",
    riskLevel: "HIGH",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_BILLING_READ,
    resource: "platform_billing",
    action: "read",
    name: "View Global SaaS Billing",
    description: "Inspect tenant subscription invoices and recurring revenue",
    scope: "PLATFORM",
    riskLevel: "LOW",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_BILLING_MANAGE,
    resource: "platform_billing",
    action: "manage",
    name: "Manage SaaS Subscriptions",
    description: "Override subscriptions, record manual SaaS payments, or issue credits",
    scope: "PLATFORM",
    riskLevel: "CRITICAL",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_SUPPORT_SESSION_START,
    resource: "platform_support",
    action: "session_start",
    name: "Initiate Audited Support Impersonation",
    description: "Start a scoped, time-bounded support access session into a tenant workspace",
    scope: "PLATFORM",
    riskLevel: "CRITICAL",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_SUPPORT_SESSION_END,
    resource: "platform_support",
    action: "session_end",
    name: "Terminate Support Access Session",
    description: "Revoke active support access session immediately",
    scope: "PLATFORM",
    riskLevel: "HIGH",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_SUPPORT_ACCESS,
    resource: "platform_support",
    action: "access",
    name: "Perform Support Read/Diagnostics",
    description: "Execute scoped diagnostics within an active support session",
    scope: "PLATFORM",
    riskLevel: "HIGH",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_AUDIT_READ,
    resource: "platform_audit",
    action: "read",
    name: "View Global Platform Audit Trail",
    description: "Inspect platform-wide security and administration logs",
    scope: "PLATFORM",
    riskLevel: "MEDIUM",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_ANALYTICS_READ,
    resource: "platform_analytics",
    action: "read",
    name: "View SaaS Executive Analytics",
    description: "View platform MRR, churn, vehicle counts, and growth metrics",
    scope: "PLATFORM",
    riskLevel: "LOW",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_COMPLIANCE_READ,
    resource: "platform_compliance",
    action: "read",
    name: "View Global Compliance Stats",
    description: "Monitor cross-tenant regulatory and verification metrics",
    scope: "PLATFORM",
    riskLevel: "LOW",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_DOMAIN_READ,
    resource: "platform_domain",
    action: "read",
    name: "View All Tenant Domains & SSL",
    description: "Monitor custom domains, verification state, and TLS status",
    scope: "PLATFORM",
    riskLevel: "LOW",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_DOMAIN_MANAGE,
    resource: "platform_domain",
    action: "manage",
    name: "Manage Platform Domains & Routing",
    description: "Manage global domain routing, DNS, and manual SSL certificates",
    scope: "PLATFORM",
    riskLevel: "HIGH",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_PAYMENT_READ,
    resource: "platform_payment",
    action: "read",
    name: "View Platform Gateway Operations",
    description: "Monitor Stripe Connect, M-Pesa Daraja, and Pesapal gateway statuses",
    scope: "PLATFORM",
    riskLevel: "LOW",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_PAYMENT_RECONCILE,
    resource: "platform_payment",
    action: "reconcile",
    name: "Reconcile Platform SaaS Payments",
    description: "Perform manual gateway transaction reconciliation and dispute resolution",
    scope: "PLATFORM",
    riskLevel: "HIGH",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_NOTIFICATION_READ,
    resource: "platform_notification",
    action: "read",
    name: "View Notification Telemetry",
    description: "Inspect cross-tenant SMS, Email, and WhatsApp delivery logs",
    scope: "PLATFORM",
    riskLevel: "LOW",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_NOTIFICATION_RETRY,
    resource: "platform_notification",
    action: "retry",
    name: "Retry Failed Notifications",
    description: "Trigger manual redelivery of failed notifications across providers",
    scope: "PLATFORM",
    riskLevel: "MEDIUM",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_JOB_READ,
    resource: "platform_job",
    action: "read",
    name: "View Background Queues & Dead Letter Jobs",
    description: "Inspect background jobs, outbox event queues, and DLQ errors",
    scope: "PLATFORM",
    riskLevel: "LOW",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_JOB_RETRY,
    resource: "platform_job",
    action: "retry",
    name: "Replay Dead Letter Jobs",
    description: "Trigger retry and redelivery for failed outbox events and jobs",
    scope: "PLATFORM",
    riskLevel: "HIGH",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_REPORT_EXPORT,
    resource: "platform_report",
    action: "export",
    name: "Export Platform SaaS Reports",
    description: "Export global financial, fleet, and tenant metrics to CSV/JSON",
    scope: "PLATFORM",
    riskLevel: "MEDIUM",
  },
  {
    key: PLATFORM_PERMISSIONS.PLATFORM_CONFIG_MANAGE,
    resource: "platform_config",
    action: "manage",
    name: "Manage Platform Global Configuration",
    description: "Configure system maintenance mode, rate limits, and platform parameters",
    scope: "PLATFORM",
    riskLevel: "CRITICAL",
  },
];
