// ============================================================================
// CAR HIRE OS — METRIC REGISTRY (Sprint 34: DOM-003 §46-52)
// Canonical catalogue of all business, operational and financial metrics
// ============================================================================

import type { MetricDefinition, MetricKey } from "@carhire/types";

export class MetricRegistry {
  private static readonly METRICS: Map<MetricKey, MetricDefinition> = new Map([
    // Fleet & Utilization
    [
      "FLEET_TOTAL_VEHICLES",
      {
        key: "FLEET_TOTAL_VEHICLES",
        displayName: "Total Fleet Size",
        description: "Total count of registered vehicles in tenant fleet regardless of lifecycle status",
        sourceDomain: "FLEET",
        formula: "COUNT(vehicles)",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "CURRENT_SNAPSHOT",
        filterDimensions: ["category", "ownershipType", "status"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "FLEET_ACTIVE_VEHICLES",
      {
        key: "FLEET_ACTIVE_VEHICLES",
        displayName: "Active Fleet Vehicles",
        description: "Count of vehicles in ACTIVE status available or currently serving rentals",
        sourceDomain: "FLEET",
        formula: "COUNT(vehicles WHERE status = 'ACTIVE')",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "CURRENT_SNAPSHOT",
        filterDimensions: ["category", "ownershipType"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "FLEET_AVAILABLE_VEHICLES",
      {
        key: "FLEET_AVAILABLE_VEHICLES",
        displayName: "Available Vehicles",
        description: "Vehicles currently ready on lot for immediate reservation or handover",
        sourceDomain: "FLEET",
        formula: "COUNT(vehicles WHERE availabilityStatus = 'AVAILABLE')",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "CURRENT_SNAPSHOT",
        filterDimensions: ["category", "location"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "FLEET_ON_RENT_VEHICLES",
      {
        key: "FLEET_ON_RENT_VEHICLES",
        displayName: "On-Rent Vehicles",
        description: "Vehicles actively on the road with an ongoing rental agreement",
        sourceDomain: "FLEET",
        formula: "COUNT(vehicles WHERE availabilityStatus = 'ON_RENT')",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "CURRENT_SNAPSHOT",
        filterDimensions: ["category", "customerType"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "FLEET_MAINTENANCE_VEHICLES",
      {
        key: "FLEET_MAINTENANCE_VEHICLES",
        displayName: "Maintenance Grounded Vehicles",
        description: "Vehicles currently under scheduled or unscheduled workshop service",
        sourceDomain: "FLEET",
        formula: "COUNT(vehicles WHERE availabilityStatus = 'MAINTENANCE')",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "CURRENT_SNAPSHOT",
        filterDimensions: ["category", "serviceProvider"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "FLEET_UTILIZATION_RATE",
      {
        key: "FLEET_UTILIZATION_RATE",
        displayName: "Fleet Utilization Rate",
        description: "Percentage of total active fleet currently deployed on active rentals",
        sourceDomain: "FLEET",
        formula: "(COUNT(on_rent) / COUNT(active_vehicles)) * 100",
        unit: "PERCENTAGE",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "CURRENT_SNAPSHOT",
        filterDimensions: ["category"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "FLEET_DOWNTIME_HOURS",
      {
        key: "FLEET_DOWNTIME_HOURS",
        displayName: "Fleet Downtime Hours",
        description: "Cumulative hours vehicles were grounded in maintenance or operational blocks",
        sourceDomain: "FLEET",
        formula: "SUM(block_end - block_start) [hours]",
        unit: "DURATION",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "RENTAL_COMPLETED",
        filterDimensions: ["category", "blockReason"],
        freshnessMode: "NEAR_REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],

    // Bookings & Reservations
    [
      "BOOKING_TOTAL_COUNT",
      {
        key: "BOOKING_TOTAL_COUNT",
        displayName: "Total Reservations Created",
        description: "Total count of bookings created within the temporal window",
        sourceDomain: "BOOKINGS",
        formula: "COUNT(bookings WHERE createdAt BETWEEN [from, to))",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "BOOKING_CREATED",
        filterDimensions: ["status", "category", "sourceChannel"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "BOOKING_CONFIRMED_COUNT",
      {
        key: "BOOKING_CONFIRMED_COUNT",
        displayName: "Confirmed Bookings",
        description: "Bookings confirmed with locked availability or paid deposit",
        sourceDomain: "BOOKINGS",
        formula: "COUNT(bookings WHERE status = 'CONFIRMED' AND createdAt BETWEEN [from, to))",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "BOOKING_CREATED",
        filterDimensions: ["category", "customerType"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "BOOKING_COMPLETED_COUNT",
      {
        key: "BOOKING_COMPLETED_COUNT",
        displayName: "Completed Bookings",
        description: "Bookings where rental cycle concluded successfully",
        sourceDomain: "BOOKINGS",
        formula: "COUNT(bookings WHERE status = 'COMPLETED' AND createdAt BETWEEN [from, to))",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "BOOKING_CREATED",
        filterDimensions: ["category"],
        freshnessMode: "NEAR_REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "BOOKING_CANCELLED_COUNT",
      {
        key: "BOOKING_CANCELLED_COUNT",
        displayName: "Cancelled Bookings",
        description: "Bookings cancelled prior to vehicle handover",
        sourceDomain: "BOOKINGS",
        formula: "COUNT(bookings WHERE status = 'CANCELLED' AND createdAt BETWEEN [from, to))",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "BOOKING_CREATED",
        filterDimensions: ["cancellationReason"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "BOOKING_NO_SHOW_COUNT",
      {
        key: "BOOKING_NO_SHOW_COUNT",
        displayName: "No-Show Bookings",
        description: "Bookings abandoned by customer without prior notice",
        sourceDomain: "BOOKINGS",
        formula: "COUNT(bookings WHERE status = 'NO_SHOW' AND createdAt BETWEEN [from, to))",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "BOOKING_CREATED",
        filterDimensions: ["category"],
        freshnessMode: "NEAR_REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "BOOKING_TOTAL_VALUE",
      {
        key: "BOOKING_TOTAL_VALUE",
        displayName: "Contractual Booking Value",
        description: "Sum of contractual gross values from frozen booking pricing snapshots (NOT recognized revenue)",
        sourceDomain: "BOOKINGS",
        formula: "SUM(grossTotal) [grouped by currency]",
        unit: "CURRENCY",
        currencyBehavior: "GROUPED_BY_CURRENCY",
        timeBasis: "BOOKING_CREATED",
        filterDimensions: ["currency", "category", "status"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "BOOKING_AVERAGE_VALUE",
      {
        key: "BOOKING_AVERAGE_VALUE",
        displayName: "Average Booking Value",
        description: "Average contractual gross value per reservation",
        sourceDomain: "BOOKINGS",
        formula: "SUM(grossTotal) / COUNT(bookings)",
        unit: "CURRENCY",
        currencyBehavior: "GROUPED_BY_CURRENCY",
        timeBasis: "BOOKING_CREATED",
        filterDimensions: ["currency", "category"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "BOOKING_CANCELLATION_RATE",
      {
        key: "BOOKING_CANCELLATION_RATE",
        displayName: "Cancellation Rate",
        description: "Percentage of bookings cancelled over total created bookings",
        sourceDomain: "BOOKINGS",
        formula: "(COUNT(cancelled) / COUNT(total_bookings)) * 100",
        unit: "PERCENTAGE",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "BOOKING_CREATED",
        filterDimensions: [],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "BOOKING_NO_SHOW_RATE",
      {
        key: "BOOKING_NO_SHOW_RATE",
        displayName: "No-Show Rate",
        description: "Percentage of confirmed bookings resulting in no-show",
        sourceDomain: "BOOKINGS",
        formula: "(COUNT(no_show) / COUNT(confirmed + no_show)) * 100",
        unit: "PERCENTAGE",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "BOOKING_CREATED",
        filterDimensions: [],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "BOOKING_LEAD_TIME_HOURS",
      {
        key: "BOOKING_LEAD_TIME_HOURS",
        displayName: "Average Booking Lead Time",
        description: "Mean hours elapsed between booking creation and scheduled vehicle pickup",
        sourceDomain: "BOOKINGS",
        formula: "AVG(pickupDateTime - createdAt) [hours]",
        unit: "DURATION",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "BOOKING_CREATED",
        filterDimensions: ["category"],
        freshnessMode: "NEAR_REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],

    // Rentals
    [
      "RENTAL_TOTAL_COUNT",
      {
        key: "RENTAL_TOTAL_COUNT",
        displayName: "Total Rentals Dispatched",
        description: "Rentals handed over and dispatched in window",
        sourceDomain: "RENTALS",
        formula: "COUNT(rentals WHERE startedAt BETWEEN [from, to))",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "RENTAL_START",
        filterDimensions: ["category", "ratePlanId"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "RENTAL_ACTIVE_COUNT",
      {
        key: "RENTAL_ACTIVE_COUNT",
        displayName: "Active On-Road Rentals",
        description: "Current ongoing rentals in ACTIVE_ON_ROAD state",
        sourceDomain: "RENTALS",
        formula: "COUNT(rentals WHERE state = 'ACTIVE_ON_ROAD')",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "CURRENT_SNAPSHOT",
        filterDimensions: ["category"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "RENTAL_COMPLETED_COUNT",
      {
        key: "RENTAL_COMPLETED_COUNT",
        displayName: "Completed Rentals",
        description: "Rentals checked in and closed within the temporal window",
        sourceDomain: "RENTALS",
        formula: "COUNT(rentals WHERE state = 'RETURNED' AND completedAt BETWEEN [from, to))",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "RENTAL_COMPLETED",
        filterDimensions: ["category"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "RENTAL_AVERAGE_DURATION_DAYS",
      {
        key: "RENTAL_AVERAGE_DURATION_DAYS",
        displayName: "Average Rental Duration",
        description: "Average days elapsed between checkout and return for closed rentals",
        sourceDomain: "RENTALS",
        formula: "AVG(completedAt - startedAt) [days]",
        unit: "DURATION",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "RENTAL_COMPLETED",
        filterDimensions: ["category"],
        freshnessMode: "NEAR_REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "RENTAL_EXTENSIONS_COUNT",
      {
        key: "RENTAL_EXTENSIONS_COUNT",
        displayName: "Rental Extensions Approved",
        description: "Total number of extension agreements processed",
        sourceDomain: "RENTALS",
        formula: "COUNT(rental_extensions WHERE status = 'APPROVED')",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "RENTAL_COMPLETED",
        filterDimensions: [],
        freshnessMode: "NEAR_REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "RENTAL_LATE_RETURN_COUNT",
      {
        key: "RENTAL_LATE_RETURN_COUNT",
        displayName: "Late Returns",
        description: "Rentals returned after scheduled dropoff time plus grace period",
        sourceDomain: "RENTALS",
        formula: "COUNT(rentals WHERE actualReturn > scheduledReturn + grace)",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "RENTAL_COMPLETED",
        filterDimensions: [],
        freshnessMode: "NEAR_REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],

    // Financial & Ledger (Authoritative)
    [
      "FINANCE_GROSS_INVOICED",
      {
        key: "FINANCE_GROSS_INVOICED",
        displayName: "Gross Invoiced Total",
        description: "Sum of total amounts invoiced across operational invoices in window",
        sourceDomain: "FINANCE",
        formula: "SUM(invoice.totalAmount WHERE status IN ('ISSUED', 'PAID'))",
        unit: "CURRENCY",
        currencyBehavior: "GROUPED_BY_CURRENCY",
        timeBasis: "INVOICE_DATE",
        filterDimensions: ["currency", "invoiceType", "status"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "reports:financial:view",
        version: 1,
      },
    ],
    [
      "FINANCE_TAX_INVOICED",
      {
        key: "FINANCE_TAX_INVOICED",
        displayName: "Tax & VAT Invoiced",
        description: "Total VAT / statutory taxes invoiced on operational invoices",
        sourceDomain: "FINANCE",
        formula: "SUM(invoice.taxAmount WHERE status IN ('ISSUED', 'PAID'))",
        unit: "CURRENCY",
        currencyBehavior: "GROUPED_BY_CURRENCY",
        timeBasis: "INVOICE_DATE",
        filterDimensions: ["currency"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "reports:financial:view",
        version: 1,
      },
    ],
    [
      "FINANCE_DISCOUNT_TOTAL",
      {
        key: "FINANCE_DISCOUNT_TOTAL",
        displayName: "Commercial Discounts Granted",
        description: "Total promotional and negotiated discounts subtracted on invoices",
        sourceDomain: "FINANCE",
        formula: "SUM(invoice.discountAmount WHERE status IN ('ISSUED', 'PAID'))",
        unit: "CURRENCY",
        currencyBehavior: "GROUPED_BY_CURRENCY",
        timeBasis: "INVOICE_DATE",
        filterDimensions: ["currency"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "reports:financial:view",
        version: 1,
      },
    ],
    [
      "FINANCE_NET_INVOICED_REVENUE",
      {
        key: "FINANCE_NET_INVOICED_REVENUE",
        displayName: "Net Invoiced Revenue",
        description: "Gross invoiced subtotal net of taxes and discounts",
        sourceDomain: "FINANCE",
        formula: "SUM(invoice.subtotal - invoice.discountAmount)",
        unit: "CURRENCY",
        currencyBehavior: "GROUPED_BY_CURRENCY",
        timeBasis: "INVOICE_DATE",
        filterDimensions: ["currency"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "reports:financial:view",
        version: 1,
      },
    ],
    [
      "FINANCE_POSTED_REVENUE",
      {
        key: "FINANCE_POSTED_REVENUE",
        displayName: "General Ledger Posted Revenue",
        description: "Authoritative earned revenue: net credit postings to REVENUE accounts in POSTED journal entries",
        sourceDomain: "LEDGER",
        formula: "SUM(journal_entries.credit - journal_entries.debit WHERE accountType = 'REVENUE')",
        unit: "CURRENCY",
        currencyBehavior: "GROUPED_BY_CURRENCY",
        timeBasis: "JOURNAL_POSTED",
        filterDimensions: ["currency", "accountCode"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "reports:financial:view",
        version: 1,
      },
    ],
    [
      "FINANCE_CASH_RECEIPTS",
      {
        key: "FINANCE_CASH_RECEIPTS",
        displayName: "Verified Cash Receipts",
        description: "Authoritative cash and electronic collections: sum of verified COMPLETED Payments",
        sourceDomain: "FINANCE",
        formula: "SUM(payments.amount WHERE status = 'COMPLETED')",
        unit: "CURRENCY",
        currencyBehavior: "GROUPED_BY_CURRENCY",
        timeBasis: "PAYMENT_VERIFIED",
        filterDimensions: ["currency", "paymentMethod"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "reports:financial:view",
        version: 1,
      },
    ],
    [
      "FINANCE_TOTAL_EXPENSES",
      {
        key: "FINANCE_TOTAL_EXPENSES",
        displayName: "Total Operating Expenses",
        description: "Sum of approved operational expenses and posted debit expense journals",
        sourceDomain: "FINANCE",
        formula: "SUM(expense.amount WHERE status = 'APPROVED')",
        unit: "CURRENCY",
        currencyBehavior: "GROUPED_BY_CURRENCY",
        timeBasis: "INVOICE_DATE",
        filterDimensions: ["currency", "expenseCategory"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "reports:financial:view",
        version: 1,
      },
    ],
    [
      "FINANCE_OUTSTANDING_RECEIVABLES",
      {
        key: "FINANCE_OUTSTANDING_RECEIVABLES",
        displayName: "Outstanding Accounts Receivable",
        description: "Total unpaid balance remaining on all issued invoices",
        sourceDomain: "FINANCE",
        formula: "SUM(invoice.balanceRemaining WHERE status IN ('ISSUED', 'PARTIALLY_PAID'))",
        unit: "CURRENCY",
        currencyBehavior: "GROUPED_BY_CURRENCY",
        timeBasis: "CURRENT_SNAPSHOT",
        filterDimensions: ["currency", "agingBucket"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "reports:financial:view",
        version: 1,
      },
    ],
    [
      "FINANCE_DEPOSITS_HELD",
      {
        key: "FINANCE_DEPOSITS_HELD",
        displayName: "Active Security Deposits Held",
        description: "Total value of customer security deposits currently in HELD escrow state",
        sourceDomain: "FINANCE",
        formula: "SUM(deposit_positions.amount WHERE status = 'HELD')",
        unit: "CURRENCY",
        currencyBehavior: "GROUPED_BY_CURRENCY",
        timeBasis: "CURRENT_SNAPSHOT",
        filterDimensions: ["currency"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "reports:financial:view",
        version: 1,
      },
    ],
    [
      "FINANCE_REFUNDS_COMPLETED",
      {
        key: "FINANCE_REFUNDS_COMPLETED",
        displayName: "Completed Customer Refunds",
        description: "Sum of verified refund payouts issued to customers in window",
        sourceDomain: "FINANCE",
        formula: "SUM(refunds.amount WHERE status = 'COMPLETED')",
        unit: "CURRENCY",
        currencyBehavior: "GROUPED_BY_CURRENCY",
        timeBasis: "PAYMENT_VERIFIED",
        filterDimensions: ["currency"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "reports:financial:view",
        version: 1,
      },
    ],
    [
      "FINANCE_TRIAL_BALANCE_DEBITS",
      {
        key: "FINANCE_TRIAL_BALANCE_DEBITS",
        displayName: "Trial Balance Total Debits",
        description: "Sum of all debit postings across the Chart of Accounts for POSTED transactions",
        sourceDomain: "LEDGER",
        formula: "SUM(journal_entries.debit WHERE transaction.status = 'POSTED')",
        unit: "CURRENCY",
        currencyBehavior: "GROUPED_BY_CURRENCY",
        timeBasis: "JOURNAL_POSTED",
        filterDimensions: ["currency"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "reports:financial:view",
        version: 1,
      },
    ],
    [
      "FINANCE_TRIAL_BALANCE_CREDITS",
      {
        key: "FINANCE_TRIAL_BALANCE_CREDITS",
        displayName: "Trial Balance Total Credits",
        description: "Sum of all credit postings across the Chart of Accounts for POSTED transactions",
        sourceDomain: "LEDGER",
        formula: "SUM(journal_entries.credit WHERE transaction.status = 'POSTED')",
        unit: "CURRENCY",
        currencyBehavior: "GROUPED_BY_CURRENCY",
        timeBasis: "JOURNAL_POSTED",
        filterDimensions: ["currency"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "reports:financial:view",
        version: 1,
      },
    ],
    [
      "FINANCE_TRIAL_BALANCE_RECONCILED",
      {
        key: "FINANCE_TRIAL_BALANCE_RECONCILED",
        displayName: "Trial Balance Reconciled",
        description: "Boolean verification that Total Debits equals Total Credits across the tenant ledger",
        sourceDomain: "LEDGER",
        formula: "SUM(debits) == SUM(credits)",
        unit: "BOOLEAN",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "JOURNAL_POSTED",
        filterDimensions: [],
        freshnessMode: "REAL_TIME",
        permissionRequired: "reports:financial:view",
        version: 1,
      },
    ],

    // Vehicle Profitability
    [
      "VEHICLE_REVENUE",
      {
        key: "VEHICLE_REVENUE",
        displayName: "Attributed Vehicle Revenue",
        description: "Rental subtotal and incidental revenues attributed to vehicle asset",
        sourceDomain: "FINANCE",
        formula: "SUM(invoice_lines.amount WHERE vehicleId IS NOT NULL)",
        unit: "CURRENCY",
        currencyBehavior: "GROUPED_BY_CURRENCY",
        timeBasis: "INVOICE_DATE",
        filterDimensions: ["vehicleId", "currency"],
        freshnessMode: "NEAR_REAL_TIME",
        permissionRequired: "reports:financial:view",
        version: 1,
      },
    ],
    [
      "VEHICLE_COSTS",
      {
        key: "VEHICLE_COSTS",
        displayName: "Attributed Vehicle Costs",
        description: "Maintenance work orders, repairs, and investor payout share attributed to vehicle asset",
        sourceDomain: "FINANCE",
        formula: "SUM(maintenance.cost + expenses.amount WHERE vehicleId IS NOT NULL)",
        unit: "CURRENCY",
        currencyBehavior: "GROUPED_BY_CURRENCY",
        timeBasis: "INVOICE_DATE",
        filterDimensions: ["vehicleId", "currency"],
        freshnessMode: "NEAR_REAL_TIME",
        permissionRequired: "reports:financial:view",
        version: 1,
      },
    ],
    [
      "VEHICLE_NET_PROFIT",
      {
        key: "VEHICLE_NET_PROFIT",
        displayName: "Vehicle Net Profitability",
        description: "Attributed revenue minus attributed direct costs per vehicle asset",
        sourceDomain: "FINANCE",
        formula: "VEHICLE_REVENUE - VEHICLE_COSTS",
        unit: "CURRENCY",
        currencyBehavior: "GROUPED_BY_CURRENCY",
        timeBasis: "INVOICE_DATE",
        filterDimensions: ["vehicleId", "currency"],
        freshnessMode: "NEAR_REAL_TIME",
        permissionRequired: "reports:financial:view",
        version: 1,
      },
    ],

    // Owner Settlements
    [
      "OWNER_SETTLEMENT_TOTAL_PAYABLE",
      {
        key: "OWNER_SETTLEMENT_TOTAL_PAYABLE",
        displayName: "Total Owner Settlement Liabilities",
        description: "Accrued payout liabilities due to vehicle owners across approved settlement periods",
        sourceDomain: "OWNER_SETTLEMENTS",
        formula: "SUM(settlements.netPayout WHERE status IN ('APPROVED', 'PAID'))",
        unit: "CURRENCY",
        currencyBehavior: "GROUPED_BY_CURRENCY",
        timeBasis: "SETTLEMENT_APPROVED",
        filterDimensions: ["currency", "ownerId", "status"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "reports:financial:view",
        version: 1,
      },
    ],
    [
      "OWNER_SETTLEMENT_PAID",
      {
        key: "OWNER_SETTLEMENT_PAID",
        displayName: "Paid Owner Settlements",
        description: "Settlements disbursed and closed",
        sourceDomain: "OWNER_SETTLEMENTS",
        formula: "SUM(settlements.netPayout WHERE status = 'PAID')",
        unit: "CURRENCY",
        currencyBehavior: "GROUPED_BY_CURRENCY",
        timeBasis: "SETTLEMENT_APPROVED",
        filterDimensions: ["currency", "ownerId"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "reports:financial:view",
        version: 1,
      },
    ],
    [
      "OWNER_SETTLEMENT_PENDING",
      {
        key: "OWNER_SETTLEMENT_PENDING",
        displayName: "Pending Owner Settlements",
        description: "Settlement batches awaiting approval or bank disbursement",
        sourceDomain: "OWNER_SETTLEMENTS",
        formula: "SUM(settlements.netPayout WHERE status IN ('DRAFT', 'PENDING_APPROVAL', 'APPROVED'))",
        unit: "CURRENCY",
        currencyBehavior: "GROUPED_BY_CURRENCY",
        timeBasis: "SETTLEMENT_APPROVED",
        filterDimensions: ["currency", "ownerId"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "reports:financial:view",
        version: 1,
      },
    ],

    // Maintenance & Compliance
    [
      "MAINTENANCE_TOTAL_COST",
      {
        key: "MAINTENANCE_TOTAL_COST",
        displayName: "Total Maintenance Cost",
        description: "Cumulative expenditures recorded across completed maintenance work orders",
        sourceDomain: "MAINTENANCE",
        formula: "SUM(maintenance.cost WHERE status = 'COMPLETED')",
        unit: "CURRENCY",
        currencyBehavior: "GROUPED_BY_CURRENCY",
        timeBasis: "CURRENT_SNAPSHOT",
        filterDimensions: ["currency", "category", "serviceProvider"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "MAINTENANCE_WORK_ORDERS_COUNT",
      {
        key: "MAINTENANCE_WORK_ORDERS_COUNT",
        displayName: "Maintenance Work Orders",
        description: "Number of workshop service tickets opened",
        sourceDomain: "MAINTENANCE",
        formula: "COUNT(maintenance)",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "CURRENT_SNAPSHOT",
        filterDimensions: ["status", "category"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "COMPLIANCE_VALID_COUNT",
      {
        key: "COMPLIANCE_VALID_COUNT",
        displayName: "Valid Compliant Documents",
        description: "Active fleet documents with full regulatory validity",
        sourceDomain: "COMPLIANCE",
        formula: "COUNT(compliance_records WHERE expiryState = 'VALID')",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "CURRENT_SNAPSHOT",
        filterDimensions: ["requirementType"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "COMPLIANCE_EXPIRING_COUNT",
      {
        key: "COMPLIANCE_EXPIRING_COUNT",
        displayName: "Expiring Fleet Documents",
        description: "Fleet documents expiring within 30 days requiring urgent renewal",
        sourceDomain: "COMPLIANCE",
        formula: "COUNT(compliance_records WHERE expiryState IN ('EXPIRING_SOON', 'URGENT'))",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "CURRENT_SNAPSHOT",
        filterDimensions: ["requirementType"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "COMPLIANCE_EXPIRED_COUNT",
      {
        key: "COMPLIANCE_EXPIRED_COUNT",
        displayName: "Expired Fleet Documents",
        description: "Grounded vehicles with past-due regulatory or insurance documents",
        sourceDomain: "COMPLIANCE",
        formula: "COUNT(compliance_records WHERE expiryState = 'EXPIRED')",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "CURRENT_SNAPSHOT",
        filterDimensions: ["requirementType"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],

    // Customers & Corporate
    [
      "CUSTOMER_TOTAL_COUNT",
      {
        key: "CUSTOMER_TOTAL_COUNT",
        displayName: "Total Registered Customers",
        description: "Total unique retail and individual customer parties",
        sourceDomain: "CUSTOMERS",
        formula: "COUNT(customers)",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "CURRENT_SNAPSHOT",
        filterDimensions: ["verificationStatus"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "CUSTOMER_NEW_COUNT",
      {
        key: "CUSTOMER_NEW_COUNT",
        displayName: "New Customer Acquisitions",
        description: "Customers registered within the temporal window",
        sourceDomain: "CUSTOMERS",
        formula: "COUNT(customers WHERE createdAt BETWEEN [from, to))",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "CURRENT_SNAPSHOT",
        filterDimensions: [],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "CUSTOMER_REPEAT_COUNT",
      {
        key: "CUSTOMER_REPEAT_COUNT",
        displayName: "Repeat Customers",
        description: "Customers with two or more lifetime completed bookings",
        sourceDomain: "CUSTOMERS",
        formula: "COUNT(customers WHERE completedBookingsCount >= 2)",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "CURRENT_SNAPSHOT",
        filterDimensions: [],
        freshnessMode: "NEAR_REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "CORPORATE_ACCOUNT_COUNT",
      {
        key: "CORPORATE_ACCOUNT_COUNT",
        displayName: "Active Corporate Accounts",
        description: "Commercial B2B enterprise client accounts",
        sourceDomain: "CUSTOMERS",
        formula: "COUNT(corporate_accounts WHERE status = 'ACTIVE')",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "CURRENT_SNAPSHOT",
        filterDimensions: [],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],

    // CRM Funnel
    [
      "CRM_LEAD_TOTAL_COUNT",
      {
        key: "CRM_LEAD_TOTAL_COUNT",
        displayName: "Inbound CRM Leads",
        description: "Total prospective client leads received in period",
        sourceDomain: "CRM",
        formula: "COUNT(leads WHERE createdAt BETWEEN [from, to))",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "LEAD_CREATED",
        filterDimensions: ["source", "status", "assignedTo"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "CRM_LEAD_QUALIFIED_COUNT",
      {
        key: "CRM_LEAD_QUALIFIED_COUNT",
        displayName: "Qualified Leads",
        description: "Leads successfully vetted and advanced to qualified status",
        sourceDomain: "CRM",
        formula: "COUNT(leads WHERE status = 'QUALIFIED')",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "LEAD_CREATED",
        filterDimensions: ["source"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "CRM_LEAD_CONVERTED_COUNT",
      {
        key: "CRM_LEAD_CONVERTED_COUNT",
        displayName: "Converted Leads",
        description: "Leads converted into confirmed bookings or active accounts",
        sourceDomain: "CRM",
        formula: "COUNT(leads WHERE status = 'WON')",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "LEAD_CREATED",
        filterDimensions: ["source"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "CRM_LEAD_CONVERSION_RATE",
      {
        key: "CRM_LEAD_CONVERSION_RATE",
        displayName: "Lead-to-Won Conversion Rate",
        description: "Percentage of total inbound leads converted to won status",
        sourceDomain: "CRM",
        formula: "(COUNT(won_leads) / COUNT(total_leads)) * 100",
        unit: "PERCENTAGE",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "LEAD_CREATED",
        filterDimensions: ["source"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "CRM_QUOTE_TOTAL_COUNT",
      {
        key: "CRM_QUOTE_TOTAL_COUNT",
        displayName: "Sales Quotes Issued",
        description: "Commercial quotes dispatched to prospective clients",
        sourceDomain: "CRM",
        formula: "COUNT(quotes WHERE createdAt BETWEEN [from, to))",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "LEAD_CREATED",
        filterDimensions: ["status"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "CRM_QUOTE_SENT_COUNT",
      {
        key: "CRM_QUOTE_SENT_COUNT",
        displayName: "Quotes Sent to Customer",
        description: "Quotes dispatched and awaiting client acceptance",
        sourceDomain: "CRM",
        formula: "COUNT(quotes WHERE status = 'SENT')",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "LEAD_CREATED",
        filterDimensions: [],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "CRM_QUOTE_ACCEPTED_COUNT",
      {
        key: "CRM_QUOTE_ACCEPTED_COUNT",
        displayName: "Quotes Accepted",
        description: "Commercial quotes formally agreed to by client",
        sourceDomain: "CRM",
        formula: "COUNT(quotes WHERE status = 'ACCEPTED')",
        unit: "COUNT",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "LEAD_CREATED",
        filterDimensions: [],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "CRM_QUOTE_CONVERSION_RATE",
      {
        key: "CRM_QUOTE_CONVERSION_RATE",
        displayName: "Quote Acceptance Rate",
        description: "Percentage of issued quotes successfully accepted by customer",
        sourceDomain: "CRM",
        formula: "(COUNT(accepted) / COUNT(sent + accepted + rejected)) * 100",
        unit: "PERCENTAGE",
        currencyBehavior: "NOT_APPLICABLE",
        timeBasis: "LEAD_CREATED",
        filterDimensions: [],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
    [
      "CRM_TOTAL_PIPELINE_VALUE",
      {
        key: "CRM_TOTAL_PIPELINE_VALUE",
        displayName: "Total CRM Pipeline Value",
        description: "Sum of contractual quote values currently active in sales pipeline",
        sourceDomain: "CRM",
        formula: "SUM(quotes.grossTotal WHERE status IN ('DRAFT', 'SENT'))",
        unit: "CURRENCY",
        currencyBehavior: "GROUPED_BY_CURRENCY",
        timeBasis: "LEAD_CREATED",
        filterDimensions: ["currency", "status"],
        freshnessMode: "REAL_TIME",
        permissionRequired: "analytics:metrics:view",
        version: 1,
      },
    ],
  ]);

  public static get(key: MetricKey): MetricDefinition | undefined {
    return MetricRegistry.METRICS.get(key);
  }

  public static getAll(): MetricDefinition[] {
    return Array.from(MetricRegistry.METRICS.values());
  }

  public static getByDomain(domain: string): MetricDefinition[] {
    return Array.from(MetricRegistry.METRICS.values()).filter(
      (m) => m.sourceDomain === domain
    );
  }
}
