// ============================================================================
// CAR HIRE OS — REPORT REGISTRY (Sprint 34: DOM-003 §46-52)
// Canonical catalogue of standard operational, financial and fleet reports
// ============================================================================

import type { ReportDefinition, ReportKey } from "@carhire/types";

export class ReportRegistry {
  private static readonly REPORTS: Map<ReportKey, ReportDefinition> = new Map([
    [
      "REPORT_FLEET_PERFORMANCE",
      {
        key: "REPORT_FLEET_PERFORMANCE",
        title: "Fleet Performance & Utilization Summary",
        description: "Comprehensive vehicle utilization, revenue generation, and downtime by category",
        category: "FLEET",
        sourceDomain: "FLEET",
        allowedFilters: ["category", "ownershipType", "status"],
        allowedGroupings: ["category", "ownershipType"],
        allowedSorts: ["category", "totalVehicles", "utilizationRate", "revenueAttributed"],
        columns: [
          { key: "category", header: "Vehicle Category", type: "string", sortable: true },
          { key: "totalVehicles", header: "Total Vehicles", type: "number", sortable: true, align: "right" },
          { key: "activeVehicles", header: "Active", type: "number", sortable: true, align: "right" },
          { key: "onRentVehicles", header: "On Rent", type: "number", sortable: true, align: "right" },
          { key: "maintenanceVehicles", header: "In Maintenance", type: "number", sortable: true, align: "right" },
          { key: "utilizationRate", header: "Utilization %", type: "percentage", sortable: true, align: "right" },
          { key: "revenueAttributed", header: "Attributed Revenue", type: "currency", sortable: true, align: "right", currencyField: "currency" },
        ],
        permissionsRequired: ["reports:view"],
        supportedExportFormats: ["CSV", "XLSX", "PDF"],
        freshnessMode: "REAL_TIME",
        version: 1,
      },
    ],
    [
      "REPORT_VEHICLE_UTILIZATION",
      {
        key: "REPORT_VEHICLE_UTILIZATION",
        title: "Vehicle-by-Vehicle Utilization Ledger",
        description: "Granular operational track record, rental days, and dispatch hours per asset",
        category: "FLEET",
        sourceDomain: "FLEET",
        allowedFilters: ["vehicleId", "category", "ownershipType"],
        allowedGroupings: ["category"],
        allowedSorts: ["registrationPlate", "category", "rentalCount", "utilizationRate"],
        columns: [
          { key: "registrationPlate", header: "Reg Plate", type: "string", sortable: true },
          { key: "makeModel", header: "Make & Model", type: "string", sortable: true },
          { key: "category", header: "Category", type: "string", sortable: true },
          { key: "rentalCount", header: "Rentals", type: "number", sortable: true, align: "right" },
          { key: "daysOnRoad", header: "Days on Road", type: "number", sortable: true, align: "right" },
          { key: "utilizationRate", header: "Utilization %", type: "percentage", sortable: true, align: "right" },
          { key: "currentStatus", header: "Status", type: "badge", sortable: true, align: "center" },
        ],
        permissionsRequired: ["reports:view"],
        supportedExportFormats: ["CSV", "XLSX", "PDF"],
        freshnessMode: "REAL_TIME",
        version: 1,
      },
    ],
    [
      "REPORT_BOOKING_LIFECYCLE",
      {
        key: "REPORT_BOOKING_LIFECYCLE",
        title: "Reservation & Booking Lifecycle Ledger",
        description: "Full audit log of bookings, confirmation velocity, cancellations, and values",
        category: "BOOKINGS",
        sourceDomain: "BOOKINGS",
        allowedFilters: ["status", "category", "customerType"],
        allowedGroupings: ["status", "category"],
        allowedSorts: ["bookingNumber", "createdAt", "pickupDateTime", "grossTotal"],
        columns: [
          { key: "bookingNumber", header: "Booking No", type: "string", sortable: true },
          { key: "customerName", header: "Customer", type: "string", sortable: true },
          { key: "category", header: "Category", type: "string", sortable: true },
          { key: "pickupDateTime", header: "Pickup Date", type: "date", sortable: true },
          { key: "returnDateTime", header: "Return Date", type: "date", sortable: true },
          { key: "status", header: "Status", type: "badge", sortable: true, align: "center" },
          { key: "grossTotal", header: "Contractual Value", type: "currency", sortable: true, align: "right", currencyField: "currency" },
        ],
        permissionsRequired: ["reports:view"],
        supportedExportFormats: ["CSV", "XLSX", "PDF"],
        freshnessMode: "REAL_TIME",
        version: 1,
      },
    ],
    [
      "REPORT_RENTAL_OPERATIONS",
      {
        key: "REPORT_RENTAL_OPERATIONS",
        title: "Rental & Turnaround Operations Log",
        description: "Operational dispatch metrics: mileage deltas, fuel differentials, late returns",
        category: "RENTALS",
        sourceDomain: "RENTALS",
        allowedFilters: ["state", "category", "vehicleId"],
        allowedGroupings: ["state"],
        allowedSorts: ["rentalNumber", "startedAt", "completedAt", "excessKm"],
        columns: [
          { key: "rentalNumber", header: "Rental No", type: "string", sortable: true },
          { key: "registrationPlate", header: "Vehicle", type: "string", sortable: true },
          { key: "customerName", header: "Renter", type: "string", sortable: true },
          { key: "startedAt", header: "Started At", type: "date", sortable: true },
          { key: "completedAt", header: "Returned At", type: "date", sortable: true },
          { key: "distanceKm", header: "Distance (KM)", type: "number", sortable: true, align: "right" },
          { key: "state", header: "Status", type: "badge", sortable: true, align: "center" },
        ],
        permissionsRequired: ["reports:view"],
        supportedExportFormats: ["CSV", "XLSX", "PDF"],
        freshnessMode: "REAL_TIME",
        version: 1,
      },
    ],
    [
      "REPORT_REVENUE_BILLING",
      {
        key: "REPORT_REVENUE_BILLING",
        title: "Operational Invoicing & Revenue Register",
        description: "Authoritative invoicing audit: subtotal, taxes, discounts, and net billings",
        category: "FINANCE",
        sourceDomain: "FINANCE",
        allowedFilters: ["status", "currency", "invoiceType"],
        allowedGroupings: ["status", "currency"],
        allowedSorts: ["invoiceNumber", "issueDate", "dueDate", "totalAmount"],
        columns: [
          { key: "invoiceNumber", header: "Invoice No", type: "string", sortable: true },
          { key: "customerName", header: "Billed Party", type: "string", sortable: true },
          { key: "issueDate", header: "Issue Date", type: "date", sortable: true },
          { key: "subtotal", header: "Subtotal", type: "currency", sortable: true, align: "right", currencyField: "currency" },
          { key: "taxAmount", header: "Tax", type: "currency", sortable: true, align: "right", currencyField: "currency" },
          { key: "discountAmount", header: "Discount", type: "currency", sortable: true, align: "right", currencyField: "currency" },
          { key: "totalAmount", header: "Gross Total", type: "currency", sortable: true, align: "right", currencyField: "currency" },
          { key: "status", header: "Status", type: "badge", sortable: true, align: "center" },
        ],
        permissionsRequired: ["reports:financial:view"],
        supportedExportFormats: ["CSV", "XLSX", "PDF"],
        freshnessMode: "REAL_TIME",
        version: 1,
      },
    ],
    [
      "REPORT_CASH_RECEIPTS",
      {
        key: "REPORT_CASH_RECEIPTS",
        title: "Verified Cash Receipts & Payment Register",
        description: "Authoritative collections log across M-Pesa, Card and Cash rails",
        category: "FINANCE",
        sourceDomain: "FINANCE",
        allowedFilters: ["provider", "currency", "status"],
        allowedGroupings: ["provider", "currency"],
        allowedSorts: ["paymentNumber", "receivedAt", "amount"],
        columns: [
          { key: "paymentNumber", header: "Receipt No", type: "string", sortable: true },
          { key: "provider", header: "Payment Rail", type: "string", sortable: true },
          { key: "externalReference", header: "Reference", type: "string", sortable: true },
          { key: "receivedAt", header: "Received At", type: "date", sortable: true },
          { key: "payerName", header: "Payer", type: "string", sortable: true },
          { key: "amount", header: "Amount", type: "currency", sortable: true, align: "right", currencyField: "currency" },
          { key: "status", header: "Status", type: "badge", sortable: true, align: "center" },
        ],
        permissionsRequired: ["reports:financial:view"],
        supportedExportFormats: ["CSV", "XLSX", "PDF"],
        freshnessMode: "REAL_TIME",
        version: 1,
      },
    ],
    [
      "REPORT_GENERAL_LEDGER",
      {
        key: "REPORT_GENERAL_LEDGER",
        title: "General Ledger Posted Transaction Journal",
        description: "Immutable double-entry posted debits and credits across Chart of Accounts",
        category: "FINANCE",
        sourceDomain: "LEDGER",
        allowedFilters: ["accountId", "accountCode", "accountType"],
        allowedGroupings: ["accountCode"],
        allowedSorts: ["transactionDate", "accountCode", "debit", "credit"],
        columns: [
          { key: "transactionNumber", header: "Transaction No", type: "string", sortable: true },
          { key: "transactionDate", header: "Posting Date", type: "date", sortable: true },
          { key: "accountCode", header: "Account Code", type: "string", sortable: true },
          { key: "accountName", header: "Account Name", type: "string", sortable: true },
          { key: "debit", header: "Debit", type: "currency", sortable: true, align: "right", currencyField: "currency" },
          { key: "credit", header: "Credit", type: "currency", sortable: true, align: "right", currencyField: "currency" },
          { key: "memo", header: "Description / Memo", type: "string", sortable: false },
        ],
        permissionsRequired: ["reports:financial:view"],
        supportedExportFormats: ["CSV", "XLSX", "PDF"],
        freshnessMode: "REAL_TIME",
        version: 1,
      },
    ],
    [
      "REPORT_TRIAL_BALANCE",
      {
        key: "REPORT_TRIAL_BALANCE",
        title: "Trial Balance & Financial Integrity Audit",
        description: "Summary balances of all accounts proving Debit = Credit double-entry equilibrium",
        category: "FINANCE",
        sourceDomain: "LEDGER",
        allowedFilters: ["currency"],
        allowedGroupings: ["accountType"],
        allowedSorts: ["accountCode", "debitBalance", "creditBalance"],
        columns: [
          { key: "accountCode", header: "Account Code", type: "string", sortable: true },
          { key: "accountName", header: "Account Title", type: "string", sortable: true },
          { key: "accountType", header: "Type", type: "string", sortable: true },
          { key: "debitBalance", header: "Debit Balance", type: "currency", sortable: true, align: "right", currencyField: "currency" },
          { key: "creditBalance", header: "Credit Balance", type: "currency", sortable: true, align: "right", currencyField: "currency" },
        ],
        permissionsRequired: ["reports:financial:view"],
        supportedExportFormats: ["CSV", "XLSX", "PDF"],
        freshnessMode: "REAL_TIME",
        version: 1,
      },
    ],
    [
      "REPORT_RECEIVABLES_AGING",
      {
        key: "REPORT_RECEIVABLES_AGING",
        title: "Accounts Receivable Aging Summary",
        description: "Open invoices categorized into Current, 1-30, 31-60, 61-90, and 90+ days overdue",
        category: "FINANCE",
        sourceDomain: "FINANCE",
        allowedFilters: ["currency", "customerId"],
        allowedGroupings: ["customerName"],
        allowedSorts: ["customerName", "totalOutstanding", "days90Plus"],
        columns: [
          { key: "customerName", header: "Customer / Account", type: "string", sortable: true },
          { key: "current", header: "Current", type: "currency", sortable: true, align: "right", currencyField: "currency" },
          { key: "days1To30", header: "1-30 Days", type: "currency", sortable: true, align: "right", currencyField: "currency" },
          { key: "days31To60", header: "31-60 Days", type: "currency", sortable: true, align: "right", currencyField: "currency" },
          { key: "days61To90", header: "61-90 Days", type: "currency", sortable: true, align: "right", currencyField: "currency" },
          { key: "days90Plus", header: "90+ Days", type: "currency", sortable: true, align: "right", currencyField: "currency" },
          { key: "totalOutstanding", header: "Total Due", type: "currency", sortable: true, align: "right", currencyField: "currency" },
        ],
        permissionsRequired: ["reports:financial:view"],
        supportedExportFormats: ["CSV", "XLSX", "PDF"],
        freshnessMode: "REAL_TIME",
        version: 1,
      },
    ],
    [
      "REPORT_VEHICLE_PROFITABILITY",
      {
        key: "REPORT_VEHICLE_PROFITABILITY",
        title: "Vehicle Asset Unit Economics & Profitability",
        description: "Net asset yield: attributable rental revenue minus maintenance and owner share costs",
        category: "FLEET",
        sourceDomain: "FINANCE",
        allowedFilters: ["category", "ownershipType"],
        allowedGroupings: ["category"],
        allowedSorts: ["registrationPlate", "revenue", "costs", "netProfit"],
        columns: [
          { key: "registrationPlate", header: "Vehicle Reg", type: "string", sortable: true },
          { key: "category", header: "Category", type: "string", sortable: true },
          { key: "revenue", header: "Gross Revenue", type: "currency", sortable: true, align: "right", currencyField: "currency" },
          { key: "costs", header: "Direct Expenses", type: "currency", sortable: true, align: "right", currencyField: "currency" },
          { key: "netProfit", header: "Net Profit", type: "currency", sortable: true, align: "right", currencyField: "currency" },
          { key: "marginPercent", header: "Margin %", type: "percentage", sortable: true, align: "right" },
        ],
        permissionsRequired: ["reports:financial:view"],
        supportedExportFormats: ["CSV", "XLSX", "PDF"],
        freshnessMode: "NEAR_REAL_TIME",
        version: 1,
      },
    ],
    [
      "REPORT_OWNER_SETTLEMENTS",
      {
        key: "REPORT_OWNER_SETTLEMENTS",
        title: "Vehicle Owner Settlement Ledger",
        description: "Investor revenue share accruals, commission deductions, and payout disbursement status",
        category: "FINANCE",
        sourceDomain: "OWNER_SETTLEMENTS",
        allowedFilters: ["ownerId", "status", "currency"],
        allowedGroupings: ["ownerName", "status"],
        allowedSorts: ["periodName", "ownerName", "netPayout", "status"],
        columns: [
          { key: "periodName", header: "Period", type: "string", sortable: true },
          { key: "ownerName", header: "Investor / Owner", type: "string", sortable: true },
          { key: "grossFleetRevenue", header: "Gross Earnings", type: "currency", sortable: true, align: "right", currencyField: "currency" },
          { key: "deductions", header: "Deductions", type: "currency", sortable: true, align: "right", currencyField: "currency" },
          { key: "netPayout", header: "Net Payout", type: "currency", sortable: true, align: "right", currencyField: "currency" },
          { key: "status", header: "Status", type: "badge", sortable: true, align: "center" },
        ],
        permissionsRequired: ["reports:financial:view"],
        supportedExportFormats: ["CSV", "XLSX", "PDF"],
        freshnessMode: "REAL_TIME",
        version: 1,
      },
    ],
    [
      "REPORT_MAINTENANCE_COSTS",
      {
        key: "REPORT_MAINTENANCE_COSTS",
        title: "Fleet Maintenance & Workshop Cost Breakdown",
        description: "Detailed breakdown of preventive servicing, unscheduled repairs, and parts expenditures",
        category: "OPERATIONS",
        sourceDomain: "MAINTENANCE",
        allowedFilters: ["category", "serviceProvider", "status"],
        allowedGroupings: ["category", "serviceProvider"],
        allowedSorts: ["workOrderNumber", "completedDate", "totalCost"],
        columns: [
          { key: "workOrderNumber", header: "Work Order", type: "string", sortable: true },
          { key: "registrationPlate", header: "Vehicle", type: "string", sortable: true },
          { key: "serviceType", header: "Service Type", type: "string", sortable: true },
          { key: "serviceProvider", header: "Workshop Vendor", type: "string", sortable: true },
          { key: "completedDate", header: "Date Completed", type: "date", sortable: true },
          { key: "totalCost", header: "Total Cost", type: "currency", sortable: true, align: "right", currencyField: "currency" },
          { key: "status", header: "Status", type: "badge", sortable: true, align: "center" },
        ],
        permissionsRequired: ["reports:view"],
        supportedExportFormats: ["CSV", "XLSX", "PDF"],
        freshnessMode: "REAL_TIME",
        version: 1,
      },
    ],
    [
      "REPORT_COMPLIANCE_STATUS",
      {
        key: "REPORT_COMPLIANCE_STATUS",
        title: "Regulatory Compliance & Document Expiry Audit",
        description: "Comprehensive registry of roadworthiness, insurance, speed governors, and PSV licenses",
        category: "OPERATIONS",
        sourceDomain: "COMPLIANCE",
        allowedFilters: ["expiryState", "requirementType"],
        allowedGroupings: ["expiryState", "requirementType"],
        allowedSorts: ["registrationPlate", "expiryDate", "expiryState"],
        columns: [
          { key: "registrationPlate", header: "Vehicle", type: "string", sortable: true },
          { key: "requirementName", header: "Compliance Document", type: "string", sortable: true },
          { key: "documentNumber", header: "Certificate / Policy No", type: "string", sortable: true },
          { key: "expiryDate", header: "Expiry Date", type: "date", sortable: true },
          { key: "daysRemaining", header: "Days Left", type: "number", sortable: true, align: "right" },
          { key: "expiryState", header: "Status", type: "badge", sortable: true, align: "center" },
        ],
        permissionsRequired: ["reports:view"],
        supportedExportFormats: ["CSV", "XLSX", "PDF"],
        freshnessMode: "REAL_TIME",
        version: 1,
      },
    ],
    [
      "REPORT_CRM_FUNNEL",
      {
        key: "REPORT_CRM_FUNNEL",
        title: "Commercial Sales Pipeline & Conversion Velocity",
        description: "Full sales velocity analysis: Inbound Leads -> Qualified -> Quotes -> Won Bookings",
        category: "CRM",
        sourceDomain: "CRM",
        allowedFilters: ["source", "status", "assignedTo"],
        allowedGroupings: ["source", "status"],
        allowedSorts: ["leadNumber", "createdAt", "pipelineStage", "potentialValue"],
        columns: [
          { key: "leadNumber", header: "Lead ID", type: "string", sortable: true },
          { key: "contactName", header: "Prospect Name", type: "string", sortable: true },
          { key: "source", header: "Channel Source", type: "string", sortable: true },
          { key: "pipelineStage", header: "Stage", type: "string", sortable: true },
          { key: "potentialValue", header: "Estimated Value", type: "currency", sortable: true, align: "right", currencyField: "currency" },
          { key: "status", header: "Status", type: "badge", sortable: true, align: "center" },
        ],
        permissionsRequired: ["reports:view"],
        supportedExportFormats: ["CSV", "XLSX", "PDF"],
        freshnessMode: "REAL_TIME",
        version: 1,
      },
    ],
  ]);

  public static get(key: ReportKey): ReportDefinition | undefined {
    return ReportRegistry.REPORTS.get(key);
  }

  public static getAll(): ReportDefinition[] {
    return Array.from(ReportRegistry.REPORTS.values());
  }

  public static getByCategory(category: string): ReportDefinition[] {
    return Array.from(ReportRegistry.REPORTS.values()).filter(
      (r) => r.category === category
    );
  }
}
