// ============================================================================
// CAR HIRE OS — OPERATIONAL RUNBOOK REGISTRY (SPRINT 42)
// Standardized runbooks for 25+ failure modes with canonical diagnostic & remediation workflows
// ============================================================================

import { RunbookDefinition } from "../types";

export const CANONICAL_RUNBOOKS: RunbookDefinition[] = [
  {
    id: "RB-001-API-5XX-SURGE",
    title: "API 5xx Server Error Surge Mitigation",
    failureMode: "Elevated HTTP 5xx responses (> 0.1% or > 10 errors / min)",
    symptoms: [
      "Alert 'API Server Error Rate Surge' firing in Alert Engine",
      "Customer checkouts or tenant dashboard reporting 'Internal Server Error'",
      "HTTP request histogram shows elevated 500/503 status code distribution",
    ],
    probableCauses: [
      "Unhandled exception introduced in recent release deployment",
      "PostgreSQL connection exhaustion or query timeout",
      "Redis broker connection drop causing synchronous pipeline crash",
      "External third-party API timeout blocking synchronous worker thread",
    ],
    severity: "SEV-1_CRITICAL",
    ownerRole: "PLATFORM_OPERATIONS",
    escalationPath: ["Primary On-Call", "Backend Core Team", "Head of Engineering"],
    strictProhibitions: [
      "NEVER modify database rows manually via raw SQL to bypass application logic",
      "NEVER disable authentication middleware to troubleshoot routing errors",
      "NEVER restart all API instances simultaneously without staggering",
    ],
    prerequisites: ["Access to container logs", "Release tag and commit SHA from /api/metadata"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Triage Error Pattern & Context",
        action: "Query recent error logs grouped by context and error.name.",
        commandSnippet: "pnpm run test:sprint42 --grep 'logs'",
        verificationQuestion: "Are errors originating from a single endpoint or cluster-wide?",
        expectedResult: "Identified whether failure is isolated to a specific handler or systemic.",
      },
      {
        stepNumber: 2,
        title: "Assess Deployment Provenance",
        action: "Check deployment timestamp against when 5xx surge began.",
        verificationQuestion: "Did error rate begin within 10 minutes of a new release deployment?",
        expectedResult: "If correlated, proceed immediately to step 3; otherwise step 4.",
      },
      {
        stepNumber: 3,
        title: "Execute Rollback (if deployment correlated)",
        action: "Trigger automated rollback workflow to previous verified image tag.",
        commandSnippet: "gh workflow run rollback.yml -f target_release_id=PREVIOUS_RELEASE_ID",
        verificationQuestion: "Did error rate drop back below candidate operational threshold?",
        expectedResult: "5xx rate returns to 0 within 2 minutes of traffic routing to previous tag.",
      },
      {
        stepNumber: 4,
        title: "Check Database Pool & Connectivity",
        action: "Inspect database connection pool metrics and active queries.",
        verificationQuestion: "Is the pool saturated with waiting clients?",
        expectedResult: "Confirmed whether PostgreSQL is the root cause.",
      },
    ],
    verificationProcedure: [
      "Verify /api/health/live returns HTTP 200",
      "Verify /api/health/ready returns HTTP 200 with DB status UP",
      "Confirm alert alert-api-5xx-surge transitions to RESOLVED",
    ],
    postIncidentActions: [
      "Generate root-cause analysis (RCA) document within 24 hours",
      "Add automated regression test covering the triggering payload",
    ],
  },
  {
    id: "RB-002-DB-POOL-EXHAUSTION",
    title: "PostgreSQL Connection Pool Exhaustion Mitigation",
    failureMode: "Connection pool has zero idle connections and waiting client queue is growing",
    symptoms: [
      "Alert 'PostgreSQL Connection Pool Exhaustion' firing",
      "API latency spikes across all routes requiring database queries",
      "Error logs contain 'Connection acquisition timed out after 10000ms'",
    ],
    probableCauses: [
      "Long-running unindexed analytics or reporting query blocking connections",
      "Database transaction left uncommitted or unclosed in error path",
      "Sudden surge in concurrent user requests exceeding configured max pool limit",
    ],
    severity: "SEV-1_CRITICAL",
    ownerRole: "DATABASE_ENGINEERING",
    escalationPath: ["Database On-Call", "Lead Database Architect", "Head of Engineering"],
    strictProhibitions: [
      "NEVER arbitrarily restart PostgreSQL database without draining connections",
      "NEVER increase pool size beyond max PostgreSQL server max_connections capacity",
    ],
    prerequisites: ["Database connection string with administrative query permissions"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Inspect pg_stat_activity for Long-Running Queries",
        action: "Run query: SELECT pid, now() - query_start AS duration, query, state FROM pg_stat_activity WHERE state != 'idle' ORDER BY duration DESC LIMIT 5;",
        verificationQuestion: "Are there queries executing longer than 30 seconds?",
        expectedResult: "Identified offending query blocking connection slots.",
      },
      {
        stepNumber: 2,
        title: "Terminate Long-Running Orphaned Queries",
        action: "SELECT pg_terminate_backend(pid) for identified runaway non-system backend PID.",
        verificationQuestion: "Did waiting connection count decrease?",
        expectedResult: "Idle connections reappear in pool; waiting queue empties.",
      },
    ],
    verificationProcedure: [
      "Verify carhire_db_pool_connections_waiting drops to 0",
      "Verify carhire_db_pool_connections_idle is >= 2",
    ],
    postIncidentActions: [
      "Add query timeout (statement_timeout) to problematic endpoints",
      "Add missing database index or route heavy query to replica",
    ],
  },
  {
    id: "RB-003-DB-DEADLOCK-SPIKE",
    title: "Database Deadlock Spike Mitigation",
    failureMode: "Elevated transaction deadlock exceptions in concurrent bookings/rentals",
    symptoms: [
      "Alert 'Database Transaction Deadlocks Detected' firing",
      "Booking checkout or vehicle status update fails with 409 Conflict / 500 error",
    ],
    probableCauses: [
      "Two transactions acquiring locks on same vehicles or bookings in opposite order",
      "Missing canonical row locking order (e.g. not sorting IDs before SELECT FOR UPDATE)",
    ],
    severity: "SEV-2_HIGH",
    ownerRole: "DATABASE_ENGINEERING",
    escalationPath: ["Backend On-Call", "Database Architect"],
    strictProhibitions: [
      "NEVER disable transactions to avoid deadlocks",
    ],
    prerequisites: ["Application error logs"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Inspect Deadlock Details in PostgreSQL Log",
        action: "Examine deadlock graph in Postgres log to see the two colliding statements.",
        verificationQuestion: "What tables and rows were being concurrently updated?",
        expectedResult: "Pinpointed the two colliding transactions.",
      },
      {
        stepNumber: 2,
        title: "Verify Advisory Lock Discipline",
        action: "Check whether the transaction code properly uses canonical resource sorting before lock.",
        verificationQuestion: "Are locks acquired in strict ascending ID order?",
        expectedResult: "Identified missing ordering sort.",
      },
    ],
    verificationProcedure: ["Confirm deadlock rate drops back to 0"],
    postIncidentActions: ["Fix resource lock ordering in repository code and release patch"],
  },
  {
    id: "RB-004-MIGRATION-FAILURE",
    title: "Database Migration Failure & Rollback",
    failureMode: "Deployment migration script fails or stalls with advisory lock error",
    symptoms: [
      "CI/CD deployment step 'db-migrate' fails with non-zero exit code",
      "Readiness probe /api/health/ready fails",
    ],
    probableCauses: [
      "Non-idempotent migration script executing against existing schema",
      "Lock acquisition timeout due to concurrent schema modification",
    ],
    severity: "SEV-1_CRITICAL",
    ownerRole: "DATABASE_ENGINEERING",
    escalationPath: ["Database On-Call", "DevOps Lead"],
    strictProhibitions: [
      "NEVER drop existing tables or columns during forward migration",
    ],
    prerequisites: ["Migration log output"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Check Advisory Lock Status",
        action: "Verify if another migration runner is holding advisory lock 0x4341524849524531.",
        verificationQuestion: "Is an orphaned migration process active?",
        expectedResult: "Identified whether migration process is locked.",
      },
    ],
    verificationProcedure: ["Verify migration engine reports all pending migrations executed cleanly"],
    postIncidentActions: ["Audit migration script for idempotency"],
  },
  {
    id: "RB-005-REDIS-PARTITION",
    title: "Redis Broker Partition / Disconnect Mitigation",
    failureMode: "Redis unreachable; queue processing degraded or running in fallback mode",
    symptoms: [
      "Alert 'Redis Broker Offline / Partitioned' firing",
      "Worker health shows Redis status 'disconnected'",
    ],
    probableCauses: ["Redis container restarted", "Network ACL / firewall rule change", "OOM kill"],
    severity: "SEV-1_CRITICAL",
    ownerRole: "PLATFORM_OPERATIONS",
    escalationPath: ["Platform On-Call", "DevOps Engineer"],
    strictProhibitions: ["NEVER flush Redis cache without evaluating active BullMQ queue loss"],
    prerequisites: ["Redis CLI or management portal access"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Check Redis Process Status",
        action: "Inspect Redis pod/container status and system memory usage.",
        verificationQuestion: "Is Redis running and accepting connections on port 6379?",
        expectedResult: "Redis status confirmed.",
      },
    ],
    verificationProcedure: ["Verify Redis health probe returns 'connected' and latency < 10ms"],
    postIncidentActions: ["Review Redis memory policy (maxmemory-policy noeviction for BullMQ)"],
  },
  {
    id: "RB-006-QUEUE-STALL",
    title: "Queue Depth Surge / Queue Stall",
    failureMode: "BullMQ queue waiting count increasing without active worker consumption",
    symptoms: ["Queue depth > 500", "Worker CPU at 0% while waiting queue climbs"],
    probableCauses: ["Worker paused or lost BullMQ lock", "All workers blocked on external resource"],
    severity: "SEV-2_HIGH",
    ownerRole: "PLATFORM_OPERATIONS",
    escalationPath: ["Platform On-Call"],
    strictProhibitions: ["NEVER delete queue jobs to clear backlog"],
    prerequisites: ["Platform Admin Command Center access"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Check Queue Pause State",
        action: "Inspect whether queue is accidentally paused.",
        verificationQuestion: "Is queue.isPaused() true?",
        expectedResult: "Unpause queue if paused.",
      },
    ],
    verificationProcedure: ["Waiting count starts decreasing as workers process backlog"],
    postIncidentActions: ["Tune worker concurrency parameters"],
  },
  {
    id: "RB-007-QUEUE-AGE-BREACH",
    title: "Oldest Queue Job Age SLA Breach",
    failureMode: "Oldest waiting job age exceeds candidate operational target (> 120s)",
    symptoms: ["Alert 'Queue Latency / Oldest Job Age SLA Breach' firing"],
    probableCauses: ["Worker under-provisioned for current traffic", "Single slow job blocking queue concurrency"],
    severity: "SEV-2_HIGH",
    ownerRole: "PLATFORM_OPERATIONS",
    escalationPath: ["Platform On-Call"],
    strictProhibitions: ["NEVER skip jobs to lower average age"],
    prerequisites: ["Worker metrics dashboard"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Inspect Slowest Job Names",
        action: "Review workerJobDurationSeconds histogram across job types.",
        verificationQuestion: "Which job name is taking the longest to execute?",
        expectedResult: "Identified slow job category.",
      },
    ],
    verificationProcedure: ["Confirm oldest waiting job age drops under 60 seconds"],
    postIncidentActions: ["Optimize query efficiency within the offending job handler"],
  },
  {
    id: "RB-008-DLQ-ACCUMULATION",
    title: "Dead-Letter Queue (DLQ) Accumulation",
    failureMode: "Jobs failing all retry attempts and moving into dead-letter storage",
    symptoms: ["Alert dlqEntriesTotal > 0", "Background platform reports DLQ items present"],
    probableCauses: ["Downstream provider outage", "Corrupt payload schema"],
    severity: "SEV-2_HIGH",
    ownerRole: "PLATFORM_OPERATIONS",
    escalationPath: ["Platform On-Call", "Domain Engineer"],
    strictProhibitions: ["NEVER delete DLQ entries without inspecting failure reasons"],
    prerequisites: ["DeadLetterService access"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Inspect DLQ Entry Payloads & Stacktraces",
        action: "Read DLQ entries via Platform Admin or CLI.",
        verificationQuestion: "Is failure due to temporary transient error or code bug?",
        expectedResult: "Root cause categorized.",
      },
      {
        stepNumber: 2,
        title: "Replay DLQ Entries",
        action: "Trigger deadLetterService.replayJob(id) once downstream service is restored.",
        verificationQuestion: "Did replayed job complete successfully?",
        expectedResult: "Job processes and clears from DLQ.",
      },
    ],
    verificationProcedure: ["Confirm DLQ count returns to 0"],
    postIncidentActions: ["Fix validation or provider error handling"],
  },
  {
    id: "RB-009-WORKER-ABSENCE",
    title: "Critical Background Worker Absence",
    failureMode: "Zero worker instances running",
    symptoms: ["Alert 'Critical Background Worker Cluster Absence' firing", "No jobs processed"],
    probableCauses: ["Worker process crashed on startup", "K8s/ECS task definition misconfigured"],
    severity: "SEV-1_CRITICAL",
    ownerRole: "PLATFORM_OPERATIONS",
    escalationPath: ["Platform On-Call", "Infrastructure Lead"],
    strictProhibitions: ["NEVER run background jobs directly on synchronous API instances"],
    prerequisites: ["Container logs"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Restart Worker Container",
        action: "Restart worker process or deployment pod.",
        commandSnippet: "pnpm dev:worker",
        verificationQuestion: "Does worker register and report healthy?",
        expectedResult: "Worker instances active metric >= 1.",
      },
    ],
    verificationProcedure: ["carhire_worker_instances_active >= 1"],
    postIncidentActions: ["Implement container liveness auto-restart if absent"],
  },
  {
    id: "RB-010-SCHEDULER-STALLED",
    title: "Canonical Scheduler Heartbeat Stalled",
    failureMode: "Scheduler stopped ticking recurring recurring cron jobs",
    symptoms: ["Outbox relay, booking expiry, and billing checks cease executing"],
    probableCauses: ["Node.js event loop freeze", "Scheduler instance crashed"],
    severity: "SEV-1_CRITICAL",
    ownerRole: "PLATFORM_OPERATIONS",
    escalationPath: ["Platform On-Call"],
    strictProhibitions: ["NEVER run duplicate uncoordinated scheduler instances"],
    prerequisites: ["Worker log output"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Restart Scheduler",
        action: "Trigger scheduler restart via WorkerManager.",
        verificationQuestion: "Is scheduler.getStatus().isRunning true?",
        expectedResult: "Scheduler emits ticks every interval.",
      },
    ],
    verificationProcedure: ["carhire_scheduler_last_tick_timestamp updates within 60s"],
    postIncidentActions: ["Add scheduler watchdog timer"],
  },
  {
    id: "RB-011-OUTBOX-LAG",
    title: "Transactional Outbox Relay Lagging",
    failureMode: "Undispatched domain events accumulating in database outbox table",
    symptoms: ["Alert 'Outbox Event Relay Lagging' firing", "Downstream projections desynchronized"],
    probableCauses: ["sched.outbox-relay job failing to connect to transport", "Outbox batch size too small"],
    severity: "SEV-2_HIGH",
    ownerRole: "PLATFORM_OPERATIONS",
    escalationPath: ["Platform On-Call"],
    strictProhibitions: ["NEVER mark outbox rows as published without actually publishing them"],
    prerequisites: ["Outbox metrics"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Trigger Outbox Processing Command",
        action: "Execute cmd.process-outbox manually via worker queue.",
        verificationQuestion: "Does undispatched event count decrease?",
        expectedResult: "Outbox events drained and published.",
      },
    ],
    verificationProcedure: ["carhire_outbox_undispatched_events < 10"],
    postIncidentActions: ["Increase outbox batch processing frequency"],
  },
  {
    id: "RB-012-PAYMENT-PROVIDER-OUTAGE",
    title: "Payment Gateway Degraded / Provider Outage",
    failureMode: "M-Pesa or card gateway returning 500s or timing out on STK push",
    symptoms: ["Payment initiation failures climb", "Payment processing latency histogram spikes"],
    probableCauses: ["Safaricom Daraja API maintenance or upstream telecom outage"],
    severity: "SEV-1_CRITICAL",
    ownerRole: "BILLING_FINANCE",
    escalationPath: ["Finance On-Call", "Platform Lead"],
    strictProhibitions: ["NEVER mark bookings confirmed without verified payment confirmation"],
    prerequisites: ["Provider status dashboard"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Enable Degradation Banner for Tenants",
        action: "Notify tenant operators that M-Pesa gateway is currently degraded.",
        verificationQuestion: "Is tenant notification banner visible?",
        expectedResult: "Tenants use manual bank transfer fallback if needed.",
      },
    ],
    verificationProcedure: ["Monitor provider response code and latency return to normal"],
    postIncidentActions: ["Conduct reconciliation once gateway is restored"],
  },
  {
    id: "RB-013-PAYMENT-WEBHOOK-SIGNATURE-SURGE",
    title: "Payment Webhook Signature Failure Surge",
    failureMode: "High rate of webhook signature verification failures",
    symptoms: ["Alert 'Payment Webhook Signature Failure Surge' firing"],
    probableCauses: ["Payment gateway webhook secret was rotated without updating app config", "Malicious spoofing attempt"],
    severity: "SEV-1_CRITICAL",
    ownerRole: "SECURITY_OPERATIONS",
    escalationPath: ["Security On-Call", "Finance Lead"],
    strictProhibitions: ["NEVER bypass signature verification to accept webhooks"],
    prerequisites: ["Webhook endpoint logs"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Check Webhook Source IP",
        action: "Verify whether requests originate from official gateway IP range.",
        verificationQuestion: "Is source IP within authorized provider CIDR?",
        expectedResult: "If unauthorized, block at WAF. If authorized, verify secret key.",
      },
      {
        stepNumber: 2,
        title: "Verify Gateway Passkey / Secret",
        action: "Compare MPESA_PASSKEY / webhook secret in secret manager with gateway portal.",
        verificationQuestion: "Do secrets match?",
        expectedResult: "Sync secret if rotated.",
      },
    ],
    verificationProcedure: ["Incoming valid webhooks verify with HTTP 200"],
    postIncidentActions: ["Enforce dual-custody secret rotation procedure"],
  },
  {
    id: "RB-014-PAYMENT-UNKNOWN-BACKLOG",
    title: "Payment Status UNKNOWN Backlog Accumulation",
    failureMode: "Payments stuck in UNKNOWN status awaiting reconciliation",
    symptoms: ["carhire_payment_unknown_backlog > 5"],
    probableCauses: ["Webhook missed due to transient network interruption"],
    severity: "SEV-2_HIGH",
    ownerRole: "BILLING_FINANCE",
    escalationPath: ["Finance Operations"],
    strictProhibitions: ["NEVER mark payments completed without gateway query confirmation"],
    prerequisites: ["Payment reconciliation tool"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Run Payment Query Reconciliation Batch",
        action: "Execute reconciliation query command against gateway.",
        verificationQuestion: "Did gateway return status (SUCCESS or FAILED)?",
        expectedResult: "Transaction transitioned out of UNKNOWN state.",
      },
    ],
    verificationProcedure: ["carhire_payment_unknown_backlog drops to 0"],
    postIncidentActions: ["Review webhook retry delivery window with provider"],
  },
  {
    id: "RB-015-NOTIFICATION-BACKLOG",
    title: "Notification Provider Delivery Backlog",
    failureMode: "SMS / Email delivery lagging or failing",
    symptoms: ["notificationQueueLagSeconds > 300"],
    probableCauses: ["SMS gateway rate limit exceeded", "Provider API credit exhaustion"],
    severity: "SEV-3_MEDIUM",
    ownerRole: "PLATFORM_OPERATIONS",
    escalationPath: ["Support Operations"],
    strictProhibitions: ["NEVER drop customer notification emails"],
    prerequisites: ["SMS provider balance"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Check Provider Account Credits",
        action: "Verify account balance in provider console.",
        verificationQuestion: "Are account credits sufficient?",
        expectedResult: "Top up credits if depleted.",
      },
    ],
    verificationProcedure: ["Notification delivery lag returns to < 10s"],
    postIncidentActions: ["Set up automated low-balance alerting on provider balance"],
  },
  {
    id: "RB-016-FILE-SCANNER-BACKLOG",
    title: "File Storage Antivirus Scanner Backlog",
    failureMode: "Uploaded customer documents waiting in unverified queue",
    symptoms: ["filesScanPending > 50"],
    probableCauses: ["Antivirus scanner daemon overloaded"],
    severity: "SEV-3_MEDIUM",
    ownerRole: "SECURITY_OPERATIONS",
    escalationPath: ["Security Operations"],
    strictProhibitions: ["NEVER serve unverified files directly to public users"],
    prerequisites: ["Storage scanner worker metrics"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Scale Scanner Workers",
        action: "Increase file scanner worker concurrency.",
        verificationQuestion: "Is scanner processing files?",
        expectedResult: "Pending scan count decreases.",
      },
    ],
    verificationProcedure: ["filesScanPending < 5"],
    postIncidentActions: ["Tune file scan timeout settings"],
  },
  {
    id: "RB-017-MEDIA-TRANSCODING-STALL",
    title: "Media Image Transcoding Queue Stalled",
    failureMode: "Vehicle photo thumbnail generation stuck",
    symptoms: ["mediaProcessingJobsActive elevated without completions"],
    probableCauses: ["Sharp image library crash on corrupted image file"],
    severity: "SEV-3_MEDIUM",
    ownerRole: "PLATFORM_OPERATIONS",
    escalationPath: ["Backend Operations"],
    strictProhibitions: ["NEVER upload unvalidated image binaries to asset storage"],
    prerequisites: ["Media processing job logs"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Quarantine Corrupt Image File",
        action: "Identify failing job and quarantine corrupted payload to DLQ.",
        verificationQuestion: "Did next media job resume?",
        expectedResult: "Media pipeline resumes normal processing.",
      },
    ],
    verificationProcedure: ["Media jobs active drops and thumbnails appear in UI"],
    postIncidentActions: ["Improve image format pre-validation in upload controller"],
  },
  {
    id: "RB-018-DOMAIN-DNS-STALL",
    title: "Tenant Custom Domain Verification Stalled",
    failureMode: "Custom domain SSL certificate generation or CNAME check failing",
    symptoms: ["domainVerificationPending > 10"],
    probableCauses: ["Tenant configured incorrect CNAME or DNS provider rate limit"],
    severity: "SEV-3_MEDIUM",
    ownerRole: "PLATFORM_OPERATIONS",
    escalationPath: ["Platform Support"],
    strictProhibitions: ["NEVER route traffic to unverified custom domains"],
    prerequisites: ["Domain management console"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Perform DNS Lookup on Domain",
        action: "Run dig CNAME domain.com to verify customer record.",
        verificationQuestion: "Does CNAME point to carhire-cname-target?",
        expectedResult: "Advise customer if DNS record is missing or incorrect.",
      },
    ],
    verificationProcedure: ["Domain verifies and displays green status in Tenant Admin"],
    postIncidentActions: ["Improve DNS troubleshooting instructions in tenant UI"],
  },
  {
    id: "RB-019-ANALYTICS-PROJECTION-LAG",
    title: "Analytics Read-Model Projection Lag",
    failureMode: "Analytics dashboard reporting outdated figures",
    symptoms: ["analyticsProjectionLagSeconds > 300"],
    probableCauses: ["Heavy analytical query lock contention or projection worker lag"],
    severity: "SEV-3_MEDIUM",
    ownerRole: "PLATFORM_OPERATIONS",
    escalationPath: ["Analytics Engineer"],
    strictProhibitions: ["NEVER overwrite projection tables with unverified data"],
    prerequisites: ["Analytics worker metrics"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Trigger Incremental Analytics Projection",
        action: "Trigger incremental projection update command.",
        verificationQuestion: "Does lag return to < 60s?",
        expectedResult: "Analytics numbers update to current timestamp.",
      },
    ],
    verificationProcedure: ["dataAsOf timestamp displays current within 2 minutes"],
    postIncidentActions: ["Index event stream aggregate IDs"],
  },
  {
    id: "RB-020-SAAS-BILLING-FAILURE",
    title: "SaaS Automated Billing Batch Job Failure",
    failureMode: "Monthly tenant SaaS subscription billing run fails",
    symptoms: ["saasBillingFailuresTotal > 0"],
    probableCauses: ["Payment gateway API error during recurring card charge"],
    severity: "SEV-2_HIGH",
    ownerRole: "BILLING_FINANCE",
    escalationPath: ["Finance On-Call"],
    strictProhibitions: ["NEVER double-bill tenants by blindly re-running batch without idempotency check"],
    prerequisites: ["SaaS billing logs"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Verify Batch Idempotency State",
        action: "Check saas_billing_runs table to see if run was partially completed.",
        verificationQuestion: "Is run marked IN_PROGRESS or FAILED?",
        expectedResult: "Run idempotent resume.",
      },
    ],
    verificationProcedure: ["All due tenant invoices generated with correct ledger entries"],
    postIncidentActions: ["Review failure reason with billing gateway"],
  },
  {
    id: "RB-021-AUTH-BRUTE-FORCE",
    title: "Authentication Brute Force Surge Mitigation",
    failureMode: "High rate of failed logins indicating credential stuffing",
    symptoms: ["securityAuthFailuresTotal spikes > 50 / min"],
    probableCauses: ["Automated bot attack targeting /api/auth/login"],
    severity: "SEV-1_CRITICAL",
    ownerRole: "SECURITY_OPERATIONS",
    escalationPath: ["Security On-Call", "DevOps Engineer"],
    strictProhibitions: ["NEVER disable rate limiters"],
    prerequisites: ["Security logs"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Identify Attacking IP Ranges",
        action: "Group auth failures by remote IP.",
        verificationQuestion: "Are attacks concentrated on specific IPs?",
        expectedResult: "Apply temporary IP block in reverse proxy or WAF.",
      },
    ],
    verificationProcedure: ["Auth failure rate returns to normal baseline"],
    postIncidentActions: ["Enforce CAPTCHA on repeated login failures"],
  },
  {
    id: "RB-022-TENANT-ISOLATION-MISMATCH",
    title: "Cross-Tenant Context Isolation Breach Blocked",
    failureMode: "Unauthorized cross-tenant resource access attempted",
    symptoms: ["Alert 'Cross-Tenant Context Isolation Breach Blocked' firing"],
    probableCauses: ["Session token tampering", "Tenant ID parameter mismatch in client URL"],
    severity: "SEV-1_CRITICAL",
    ownerRole: "SECURITY_OPERATIONS",
    escalationPath: ["Security On-Call", "Lead Architect", "CISO"],
    strictProhibitions: ["NEVER allow cross-tenant query without verified support impersonation session"],
    prerequisites: ["Audit log with correlation ID"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Review Security Audit Record",
        action: "Inspect targeted tenant ID vs authenticated token tenant ID.",
        verificationQuestion: "Did middleware block the request?",
        expectedResult: "Confirmed request was blocked with HTTP 403 Forbidden.",
      },
      {
        stepNumber: 2,
        title: "Revoke Compromised User Token",
        action: "Revoke JWT or session of the initiating user immediately.",
        verificationQuestion: "Is session invalidated in Redis token blacklist?",
        expectedResult: "Subsequent requests rejected with 401 Unauthorized.",
      },
    ],
    verificationProcedure: ["Verify no cross-tenant data was returned in response payload"],
    postIncidentActions: ["Conduct full security audit of the affected endpoint"],
  },
  {
    id: "RB-023-STORAGE-CAPACITY-BREACH",
    title: "Storage Volume Capacity Breach",
    failureMode: "Disk storage volume exceeds 85% utilization",
    symptoms: ["Storage capacity warning alert"],
    probableCauses: ["Log files not rotated or uncleaned temp files"],
    severity: "SEV-2_HIGH",
    ownerRole: "PLATFORM_OPERATIONS",
    escalationPath: ["DevOps On-Call"],
    strictProhibitions: ["NEVER delete active database files or live customer uploads"],
    prerequisites: ["Server disk usage command"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Trigger Orphaned File Cleanup Job",
        action: "Run cmd.cleanup-orphan-files job to delete orphaned temp files.",
        verificationQuestion: "Did disk utilization drop below 80%?",
        expectedResult: "Temporary space reclaimed.",
      },
    ],
    verificationProcedure: ["df -h shows disk usage < 80%"],
    postIncidentActions: ["Expand volume size in cloud infrastructure"],
  },
  {
    id: "RB-024-HEAP-EXHAUSTION",
    title: "Node.js Heap Exhaustion / Memory Leak",
    failureMode: "Process heap constantly climbing without GC reclamation",
    symptoms: ["carhire_process_heap_bytes approaching container memory limit"],
    probableCauses: ["Unbounded in-memory cache or event listener leak"],
    severity: "SEV-1_CRITICAL",
    ownerRole: "PLATFORM_OPERATIONS",
    escalationPath: ["Backend Lead"],
    strictProhibitions: ["NEVER disable memory limits"],
    prerequisites: ["Heap dump tooling"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Perform Staggered Process Restart",
        action: "Perform rolling restart of API container instances one by one.",
        verificationQuestion: "Does memory drop to baseline without dropping traffic?",
        expectedResult: "Fresh instances handle traffic with low heap.",
      },
    ],
    verificationProcedure: ["Heap usage stabilizes below 500MB"],
    postIncidentActions: ["Analyze heap snapshot to identify memory leak source"],
  },
  {
    id: "RB-025-ROLLBACK-EXECUTION",
    title: "Canonical Production Rollback Execution Procedure",
    failureMode: "New release introduces critical degradation requiring immediate reversion",
    symptoms: ["P0/P1 incident declared following a new release promotion"],
    probableCauses: ["Bug in new release binary or incompatible configuration"],
    severity: "SEV-1_CRITICAL",
    ownerRole: "PLATFORM_OPERATIONS",
    escalationPath: ["Incident Commander", "Release Manager", "Head of Engineering"],
    strictProhibitions: [
      "NEVER rollback database schema if it would destroy newly created live business data",
      "NEVER bypass canary validation on rollback target",
    ],
    prerequisites: ["Previous release artifact image digest from release registry"],
    mitigationSteps: [
      {
        stepNumber: 1,
        title: "Declare Incident & Halt Active Promotion",
        action: "Pause any running CD deployment pipelines.",
        verificationQuestion: "Is pipeline execution halted?",
        expectedResult: "No further automated deployments occur.",
      },
      {
        stepNumber: 2,
        title: "Trigger Rollback Workflow",
        action: "Deploy previous stable immutable image digest.",
        commandSnippet: "gh workflow run rollback.yml -f target_release_id=RELEASE_TAG",
        verificationQuestion: "Does /api/metadata report previous releaseId?",
        expectedResult: "Traffic routes cleanly to previous stable release.",
      },
      {
        stepNumber: 3,
        title: "Verify Post-Rollback System Health",
        action: "Check /api/health returns HTTP 200 with status 'ok'.",
        verificationQuestion: "Are all critical checks UP?",
        expectedResult: "System health restored to HEALTHY.",
      },
    ],
    verificationProcedure: [
      "All active alerts transition to RESOLVED",
      "Core booking and checkout flows verified via automated synthetic probe",
    ],
    postIncidentActions: [
      "Conduct post-mortem review",
      "Block release tag from further promotion until fix is verified in staging",
    ],
  },
];

export class RunbookRegistry {
  private static instance: RunbookRegistry;
  private runbooks = new Map<string, RunbookDefinition>();

  private constructor() {
    for (const rb of CANONICAL_RUNBOOKS) {
      this.runbooks.set(rb.id, rb);
    }
  }

  public static getInstance(): RunbookRegistry {
    if (!RunbookRegistry.instance) {
      RunbookRegistry.instance = new RunbookRegistry();
    }
    return RunbookRegistry.instance;
  }

  public getAll(): RunbookDefinition[] {
    return Array.from(this.runbooks.values());
  }

  public getById(id: string): RunbookDefinition | undefined {
    return this.runbooks.get(id);
  }
}
