// ============================================================================
// CAR HIRE OS — PLATFORM METRIC REGISTRY (Sprint 35: DOM-003, DEV-004)
// Canonical catalogue of all SaaS platform business, subscription, and financial metrics
// ============================================================================

import type { PlatformMetricDefinition, PlatformMetricKey } from "@carhire/types";

export class PlatformMetricRegistry {
  private static readonly METRICS: Map<PlatformMetricKey, PlatformMetricDefinition> = new Map([
    // Recurring Revenue & Run Rate
    [
      "SAAS_MRR_TOTAL",
      {
        key: "SAAS_MRR_TOTAL",
        name: "Total Monthly Recurring Revenue (MRR)",
        category: "REVENUE",
        description: "Normalized monthly recurring subscription revenue across all active paid tenant accounts",
        formula: "sum(MRR) = SUM(CASE WHEN interval = 'MONTHLY' THEN amount ELSE amount / 12 END WHERE status IN ('ACTIVE', 'RENEWAL_DUE', 'GRACE_PERIOD'))",
        sourceDomain: "SAAS_SUBSCRIPTIONS",
        unit: "CURRENCY",
        grain: "DAILY",
        aggregationType: "SUM",
        version: "1.0.0",
        currencyDependent: true,
        isActive: true,
      },
    ],
    [
      "SAAS_ARR_TOTAL",
      {
        key: "SAAS_ARR_TOTAL",
        name: "Total Annualized Run Rate (ARR)",
        category: "REVENUE",
        description: "Annualized projection of current active subscription run rate",
        formula: "MRR * 12",
        sourceDomain: "SAAS_SUBSCRIPTIONS",
        unit: "CURRENCY",
        grain: "DAILY",
        aggregationType: "SNAPSHOT_LATEST",
        version: "1.0.0",
        currencyDependent: true,
        isActive: true,
      },
    ],
    [
      "SAAS_MRR_NEW",
      {
        key: "SAAS_MRR_NEW",
        name: "New Business MRR",
        category: "REVENUE",
        description: "Recurring revenue added from new tenant subscriptions converted during period",
        formula: "SUM(mrrDelta WHERE movementType = 'NEW')",
        sourceDomain: "MRR_MOVEMENTS",
        unit: "CURRENCY",
        grain: "MONTHLY",
        aggregationType: "SUM",
        version: "1.0.0",
        currencyDependent: true,
        isActive: true,
      },
    ],
    [
      "SAAS_MRR_EXPANSION",
      {
        key: "SAAS_MRR_EXPANSION",
        name: "Expansion MRR",
        category: "REVENUE",
        description: "Additional recurring revenue from existing subscribers upgrading plan tiers or purchasing add-ons",
        formula: "SUM(mrrDelta WHERE movementType = 'EXPANSION')",
        sourceDomain: "MRR_MOVEMENTS",
        unit: "CURRENCY",
        grain: "MONTHLY",
        aggregationType: "SUM",
        version: "1.0.0",
        currencyDependent: true,
        isActive: true,
      },
    ],
    [
      "SAAS_MRR_CONTRACTION",
      {
        key: "SAAS_MRR_CONTRACTION",
        name: "Contraction MRR",
        category: "REVENUE",
        description: "Reduction in recurring revenue from existing subscribers downgrading plan tiers",
        formula: "SUM(ABS(mrrDelta) WHERE movementType = 'CONTRACTION')",
        sourceDomain: "MRR_MOVEMENTS",
        unit: "CURRENCY",
        grain: "MONTHLY",
        aggregationType: "SUM",
        version: "1.0.0",
        currencyDependent: true,
        isActive: true,
      },
    ],
    [
      "SAAS_MRR_CHURN",
      {
        key: "SAAS_MRR_CHURN",
        name: "Churned MRR",
        category: "REVENUE",
        description: "Lost recurring revenue from cancelled, expired, or non-renewed subscriptions",
        formula: "SUM(ABS(mrrDelta) WHERE movementType = 'CHURN')",
        sourceDomain: "MRR_MOVEMENTS",
        unit: "CURRENCY",
        grain: "MONTHLY",
        aggregationType: "SUM",
        version: "1.0.0",
        currencyDependent: true,
        isActive: true,
      },
    ],
    [
      "SAAS_MRR_REACTIVATION",
      {
        key: "SAAS_MRR_REACTIVATION",
        name: "Reactivation MRR",
        category: "REVENUE",
        description: "Recurring revenue recovered from previously churned or suspended tenants who resubscribe",
        formula: "SUM(mrrDelta WHERE movementType = 'REACTIVATION')",
        sourceDomain: "MRR_MOVEMENTS",
        unit: "CURRENCY",
        grain: "MONTHLY",
        aggregationType: "SUM",
        version: "1.0.0",
        currencyDependent: true,
        isActive: true,
      },
    ],
    [
      "SAAS_MRR_NET_DELTA",
      {
        key: "SAAS_MRR_NET_DELTA",
        name: "Net MRR Delta",
        category: "REVENUE",
        description: "Net periodic change in monthly recurring revenue",
        formula: "(SAAS_MRR_NEW + SAAS_MRR_EXPANSION + SAAS_MRR_REACTIVATION) - (SAAS_MRR_CONTRACTION + SAAS_MRR_CHURN)",
        sourceDomain: "MRR_MOVEMENTS",
        unit: "CURRENCY",
        grain: "MONTHLY",
        aggregationType: "SUM",
        version: "1.0.0",
        currencyDependent: true,
        isActive: true,
      },
    ],
    [
      "SAAS_ARPU",
      {
        key: "SAAS_ARPU",
        name: "Average Revenue Per Account (ARPU)",
        category: "REVENUE",
        description: "Average monthly subscription revenue per active paid tenant",
        formula: "SAAS_MRR_TOTAL / SAAS_ACTIVE_PAID_TENANTS",
        sourceDomain: "PLATFORM_ANALYTICS",
        unit: "CURRENCY",
        grain: "DAILY",
        aggregationType: "RATIO",
        version: "1.0.0",
        currencyDependent: true,
        isActive: true,
      },
    ],
    [
      "SAAS_LTV",
      {
        key: "SAAS_LTV",
        name: "Customer Lifetime Value (LTV)",
        category: "REVENUE",
        description: "Estimated gross revenue generated by a tenant account over its lifetime",
        formula: "SAAS_ARPU / (SAAS_LOGO_CHURN_RATE / 100)",
        sourceDomain: "PLATFORM_ANALYTICS",
        unit: "CURRENCY",
        grain: "MONTHLY",
        aggregationType: "RATIO",
        version: "1.0.0",
        currencyDependent: true,
        isActive: true,
      },
    ],

    // Subscriber Counts & Distribution
    [
      "SAAS_TOTAL_TENANTS",
      {
        key: "SAAS_TOTAL_TENANTS",
        name: "Total Provisioned Tenants",
        category: "SUBSCRIBERS",
        description: "Total number of tenant workspaces ever provisioned on the platform",
        formula: "COUNT(tenants)",
        sourceDomain: "TENANCY",
        unit: "COUNT",
        grain: "DAILY",
        aggregationType: "COUNT",
        version: "1.0.0",
        currencyDependent: false,
        isActive: true,
      },
    ],
    [
      "SAAS_ACTIVE_PAID_TENANTS",
      {
        key: "SAAS_ACTIVE_PAID_TENANTS",
        name: "Active Paid Tenants",
        category: "SUBSCRIBERS",
        description: "Tenant workspaces with active paid subscription contracts contributing to MRR",
        formula: "COUNT(subscriptions WHERE status IN ('ACTIVE', 'RENEWAL_DUE', 'GRACE_PERIOD') AND isPaidPlan = true)",
        sourceDomain: "SAAS_SUBSCRIPTIONS",
        unit: "COUNT",
        grain: "DAILY",
        aggregationType: "COUNT",
        version: "1.0.0",
        currencyDependent: false,
        isActive: true,
      },
    ],
    [
      "SAAS_TRIAL_TENANTS",
      {
        key: "SAAS_TRIAL_TENANTS",
        name: "Trial Tenants",
        category: "SUBSCRIBERS",
        description: "Tenant workspaces in free trial evaluation status",
        formula: "COUNT(subscriptions WHERE status = 'TRIAL')",
        sourceDomain: "SAAS_SUBSCRIPTIONS",
        unit: "COUNT",
        grain: "DAILY",
        aggregationType: "COUNT",
        version: "1.0.0",
        currencyDependent: false,
        isActive: true,
      },
    ],
    [
      "SAAS_RENEWAL_DUE_TENANTS",
      {
        key: "SAAS_RENEWAL_DUE_TENANTS",
        name: "Renewal Due Tenants",
        category: "SUBSCRIBERS",
        description: "Active subscriptions within renewal notification window",
        formula: "COUNT(subscriptions WHERE status = 'RENEWAL_DUE')",
        sourceDomain: "SAAS_SUBSCRIPTIONS",
        unit: "COUNT",
        grain: "DAILY",
        aggregationType: "COUNT",
        version: "1.0.0",
        currencyDependent: false,
        isActive: true,
      },
    ],
    [
      "SAAS_GRACE_PERIOD_TENANTS",
      {
        key: "SAAS_GRACE_PERIOD_TENANTS",
        name: "Grace Period Tenants",
        category: "SUBSCRIBERS",
        description: "Tenants past renewal due date but within 7-day courtesy access window",
        formula: "COUNT(subscriptions WHERE status = 'GRACE_PERIOD')",
        sourceDomain: "SAAS_SUBSCRIPTIONS",
        unit: "COUNT",
        grain: "DAILY",
        aggregationType: "COUNT",
        version: "1.0.0",
        currencyDependent: false,
        isActive: true,
      },
    ],
    [
      "SAAS_SUSPENDED_TENANTS",
      {
        key: "SAAS_SUSPENDED_TENANTS",
        name: "Suspended Tenants",
        category: "SUBSCRIBERS",
        description: "Tenants locked out of operational access due to non-payment or policy breach",
        formula: "COUNT(subscriptions WHERE status = 'SUSPENDED')",
        sourceDomain: "SAAS_SUBSCRIPTIONS",
        unit: "COUNT",
        grain: "DAILY",
        aggregationType: "COUNT",
        version: "1.0.0",
        currencyDependent: false,
        isActive: true,
      },
    ],
    [
      "SAAS_CANCELLED_TENANTS",
      {
        key: "SAAS_CANCELLED_TENANTS",
        name: "Cancelled / Churned Tenants",
        category: "SUBSCRIBERS",
        description: "Tenant workspaces whose subscriptions were terminated",
        formula: "COUNT(subscriptions WHERE status IN ('CANCELLED', 'EXPIRED'))",
        sourceDomain: "SAAS_SUBSCRIPTIONS",
        unit: "COUNT",
        grain: "DAILY",
        aggregationType: "COUNT",
        version: "1.0.0",
        currencyDependent: false,
        isActive: true,
      },
    ],

    // Retention & Churn Rates
    [
      "SAAS_LOGO_CHURN_RATE",
      {
        key: "SAAS_LOGO_CHURN_RATE",
        name: "Logo Churn Rate",
        category: "CHURN_RETENTION",
        description: "Percentage of paid subscriber accounts lost over the measurement window",
        formula: "(LostTenantsInPeriod / StartPeriodPaidTenants) * 100",
        sourceDomain: "PLATFORM_ANALYTICS",
        unit: "PERCENT",
        grain: "MONTHLY",
        aggregationType: "RATE",
        version: "1.0.0",
        currencyDependent: false,
        isActive: true,
      },
    ],
    [
      "SAAS_GROSS_REVENUE_CHURN_RATE",
      {
        key: "SAAS_GROSS_REVENUE_CHURN_RATE",
        name: "Gross Revenue Churn Rate",
        category: "CHURN_RETENTION",
        description: "Percentage of starting MRR lost to cancellations and downgrades",
        formula: "((SAAS_MRR_CHURN + SAAS_MRR_CONTRACTION) / StartPeriodMRR) * 100",
        sourceDomain: "PLATFORM_ANALYTICS",
        unit: "PERCENT",
        grain: "MONTHLY",
        aggregationType: "RATE",
        version: "1.0.0",
        currencyDependent: false,
        isActive: true,
      },
    ],
    [
      "SAAS_NET_REVENUE_RETENTION",
      {
        key: "SAAS_NET_REVENUE_RETENTION",
        name: "Net Revenue Retention (NRR)",
        category: "CHURN_RETENTION",
        description: "Percentage of recurring revenue retained from existing cohort including expansion, contraction, and churn",
        formula: "((StartMRR + Expansion - Contraction - Churn) / StartMRR) * 100",
        sourceDomain: "PLATFORM_ANALYTICS",
        unit: "PERCENTAGE",
        grain: "MONTHLY",
        aggregationType: "RATE",
        version: "1.0.0",
        currencyDependent: false,
        isActive: true,
      },
    ],
    [
      "SAAS_TRIAL_CONVERSION_RATE",
      {
        key: "SAAS_TRIAL_CONVERSION_RATE",
        name: "Trial-to-Paid Conversion Rate",
        category: "CHURN_RETENTION",
        description: "Percentage of trial workspaces that convert into paid subscriptions",
        formula: "(ConvertedTrialTenants / TotalTrialsCompleted) * 100",
        sourceDomain: "PLATFORM_ANALYTICS",
        unit: "PERCENT",
        grain: "MONTHLY",
        aggregationType: "RATE",
        version: "1.0.0",
        currencyDependent: false,
        isActive: true,
      },
    ],
    [
      "SAAS_AVERAGE_TIME_TO_CONVERT_DAYS",
      {
        key: "SAAS_AVERAGE_TIME_TO_CONVERT_DAYS",
        name: "Average Days to Convert",
        category: "CHURN_RETENTION",
        description: "Mean number of days between trial workspace creation and first paid subscription activation",
        formula: "AVG(paidActivatedAt - trialCreatedAt)",
        sourceDomain: "PLATFORM_ANALYTICS",
        unit: "DAYS",
        grain: "MONTHLY",
        aggregationType: "AVG",
        version: "1.0.0",
        currencyDependent: false,
        isActive: true,
      },
    ],

    // Billing Health & Invoicing
    [
      "SAAS_INVOICED_REVENUE",
      {
        key: "SAAS_INVOICED_REVENUE",
        name: "Total SaaS Invoiced Revenue",
        category: "BILLING_HEALTH",
        description: "Total gross amount of platform software billing invoices issued",
        formula: "SUM(total WHERE status != 'VOID')",
        sourceDomain: "SAAS_BILLING",
        unit: "CURRENCY",
        grain: "MONTHLY",
        aggregationType: "SUM",
        version: "1.0.0",
        currencyDependent: true,
        isActive: true,
      },
    ],
    [
      "SAAS_COLLECTED_CASH",
      {
        key: "SAAS_COLLECTED_CASH",
        name: "Total Collected SaaS Cash",
        category: "BILLING_HEALTH",
        description: "Actual subscription cash payments collected and settled through Stripe or M-Pesa",
        formula: "SUM(amountPaid WHERE status = 'PAID')",
        sourceDomain: "SAAS_BILLING",
        unit: "CURRENCY",
        grain: "MONTHLY",
        aggregationType: "SUM",
        version: "1.0.0",
        currencyDependent: true,
        isActive: true,
      },
    ],
    [
      "SAAS_OUTSTANDING_AR",
      {
        key: "SAAS_OUTSTANDING_AR",
        name: "Outstanding Accounts Receivable",
        category: "BILLING_HEALTH",
        description: "Total unpaid open balance due from tenant subscribers",
        formula: "SUM(amountDue WHERE status IN ('OPEN', 'OVERDUE'))",
        sourceDomain: "SAAS_BILLING",
        unit: "CURRENCY",
        grain: "DAILY",
        aggregationType: "SUM",
        version: "1.0.0",
        currencyDependent: true,
        isActive: true,
      },
    ],
    [
      "SAAS_OVERDUE_INVOICES_COUNT",
      {
        key: "SAAS_OVERDUE_INVOICES_COUNT",
        name: "Overdue Invoices Count",
        category: "BILLING_HEALTH",
        description: "Count of unpaid subscription invoices past their payment due date",
        formula: "COUNT(saasInvoices WHERE dueAt < NOW() AND status = 'OPEN')",
        sourceDomain: "SAAS_BILLING",
        unit: "COUNT",
        grain: "DAILY",
        aggregationType: "COUNT",
        version: "1.0.0",
        currencyDependent: false,
        isActive: true,
      },
    ],
    [
      "SAAS_PAYMENT_FAILURE_RATE",
      {
        key: "SAAS_PAYMENT_FAILURE_RATE",
        name: "Recurring Payment Failure Rate",
        category: "BILLING_HEALTH",
        description: "Percentage of automated payment attempts that failed on first try",
        formula: "(FailedPaymentAttempts / TotalPaymentAttempts) * 100",
        sourceDomain: "PAYMENT_ATTEMPTS",
        unit: "PERCENT",
        grain: "MONTHLY",
        aggregationType: "RATE",
        version: "1.0.0",
        currencyDependent: false,
        isActive: true,
      },
    ],
    [
      "SAAS_DSO_DAYS",
      {
        key: "SAAS_DSO_DAYS",
        name: "Days Sales Outstanding (DSO)",
        category: "BILLING_HEALTH",
        description: "Average number of days taken by tenant accounts to settle SaaS subscription invoices",
        formula: "(SAAS_OUTSTANDING_AR / TotalCreditSales) * NumberOfDays",
        sourceDomain: "PLATFORM_ANALYTICS",
        unit: "DAYS",
        grain: "MONTHLY",
        aggregationType: "RATIO",
        version: "1.0.0",
        currencyDependent: false,
        isActive: true,
      },
    ],

    // Entitlement & Quota Adoption
    [
      "SAAS_FLEET_CAPACITY_QUOTA_TOTAL",
      {
        key: "SAAS_FLEET_CAPACITY_QUOTA_TOTAL",
        name: "Total Contracted Fleet Quota",
        category: "ENTITLEMENT_USAGE",
        description: "Aggregate sum of maximum vehicle quotas allotted across all active subscriptions",
        formula: "SUM(plan.maxVehicles WHERE sub.status = 'ACTIVE')",
        sourceDomain: "ENTITLEMENTS",
        unit: "COUNT",
        grain: "DAILY",
        aggregationType: "SUM",
        version: "1.0.0",
        currencyDependent: false,
        isActive: true,
      },
    ],
    [
      "SAAS_FLEET_CAPACITY_USED",
      {
        key: "SAAS_FLEET_CAPACITY_USED",
        name: "Total Vehicles Registered Across Tenants",
        category: "ENTITLEMENT_USAGE",
        description: "Total count of vehicles created across all active tenant fleets",
        formula: "COUNT(vehicles WHERE tenant.isSubActive = true)",
        sourceDomain: "FLEET",
        unit: "COUNT",
        grain: "DAILY",
        aggregationType: "COUNT",
        version: "1.0.0",
        currencyDependent: false,
        isActive: true,
      },
    ],
    [
      "SAAS_FLEET_UTILIZATION_PERCENT",
      {
        key: "SAAS_FLEET_UTILIZATION_PERCENT",
        name: "Fleet Capacity Utilization Rate",
        category: "ENTITLEMENT_USAGE",
        description: "Percentage of aggregate contracted vehicle quota currently consumed by tenant operators",
        formula: "(SAAS_FLEET_CAPACITY_USED / SAAS_FLEET_CAPACITY_QUOTA_TOTAL) * 100",
        sourceDomain: "ENTITLEMENTS",
        unit: "PERCENT",
        grain: "DAILY",
        aggregationType: "RATE",
        version: "1.0.0",
        currencyDependent: false,
        isActive: true,
      },
    ],
    [
      "SAAS_SEATS_QUOTA_TOTAL",
      {
        key: "SAAS_SEATS_QUOTA_TOTAL",
        name: "Total Contracted Team Member Seats",
        category: "ENTITLEMENT_USAGE",
        description: "Aggregate sum of user member seats allotted across all active subscriptions",
        formula: "SUM(plan.maxMembers WHERE sub.status = 'ACTIVE')",
        sourceDomain: "ENTITLEMENTS",
        unit: "COUNT",
        grain: "DAILY",
        aggregationType: "SUM",
        version: "1.0.0",
        currencyDependent: false,
        isActive: true,
      },
    ],
    [
      "SAAS_SEATS_USED",
      {
        key: "SAAS_SEATS_USED",
        name: "Total Team Member Seats Used",
        category: "ENTITLEMENT_USAGE",
        description: "Total count of active tenant memberships across the platform",
        formula: "COUNT(tenantMemberships WHERE status = 'ACTIVE')",
        sourceDomain: "TENANCY",
        unit: "COUNT",
        grain: "DAILY",
        aggregationType: "COUNT",
        version: "1.0.0",
        currencyDependent: false,
        isActive: true,
      },
    ],
    [
      "SAAS_ADVANCED_FEATURE_ADOPTION_RATE",
      {
        key: "SAAS_ADVANCED_FEATURE_ADOPTION_RATE",
        name: "Advanced Features Adoption Rate",
        category: "ENTITLEMENT_USAGE",
        description: "Percentage of active tenants utilizing advanced tier features (e.g. Double-Entry Ledger, Custom Domains)",
        formula: "(TenantsWithAdvancedFeaturesActive / TotalActiveTenants) * 100",
        sourceDomain: "ENTITLEMENTS",
        unit: "PERCENT",
        grain: "MONTHLY",
        aggregationType: "RATE",
        version: "1.0.0",
        currencyDependent: false,
        isActive: true,
      },
    ],
  ]);

  static getAll(): PlatformMetricDefinition[] {
    return Array.from(this.METRICS.values());
  }

  static get(key: PlatformMetricKey): PlatformMetricDefinition | undefined {
    return this.METRICS.get(key);
  }

  static getByCategory(category: string): PlatformMetricDefinition[] {
    const cat = category.toUpperCase();
    if (cat === "TENANTS") {
      return Array.from(this.METRICS.values()).filter((m) => m.category === "SUBSCRIBERS");
    }
    return Array.from(this.METRICS.values()).filter((m) => m.category === cat);
  }

  static has(key: string): key is PlatformMetricKey {
    return this.METRICS.has(key as PlatformMetricKey);
  }

  static count(): number {
    return this.METRICS.size;
  }
}
