import React, { useState } from "react";
import { ArrowRight, CheckCircle2, ClipboardCheck, FileSignature, FileText, KeyRound, Loader2, Send, ShieldCheck, X } from "lucide-react";
import { apiClient, type ApiResponse } from "../lib/api-client";
import { permits, type AccessPortal } from "../lib/access-context";

export type ContractAction = "send" | "sign" | "amend";
export type HandoverAction = "arrive" | "documents" | "inspection" | "signature" | "keys" | "complete";

export const inputClass="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-900 outline-none transition focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100 disabled:bg-slate-50 disabled:text-slate-400";
export const primary="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-emerald-700 disabled:cursor-not-allowed disabled:opacity-50";
export const secondary="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50";
export const warning="inline-flex items-center justify-center gap-2 rounded-xl border border-amber-200 bg-white px-4 py-2.5 text-sm font-semibold text-amber-700 hover:bg-amber-50 disabled:cursor-not-allowed disabled:opacity-50";

export async function unwrap<T>(response:ApiResponse<T>|Promise<ApiResponse<T>>):Promise<T>{const r=await response;if(r.error)throw new Error(r.error.message);return r.data as T;}
export function human(v?:string|null){return v?v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase()):"—";}
export function dateTime(v?:string|null){if(!v)return "—";const d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleString():"—";}
function localInput(v?:string|null){if(!v)return "";const d=new Date(v);if(!Number.isFinite(d.getTime()))return "";const p=(n:number)=>String(n).padStart(2,"0");return d.getFullYear()+"-"+p(d.getMonth()+1)+"-"+p(d.getDate())+"T"+p(d.getHours())+":"+p(d.getMinutes());}
export function money(v:any,currency="KES"){const n=Number(v);if(!Number.isFinite(n))return "—";try{return new Intl.NumberFormat(undefined,{style:"currency",currency,maximumFractionDigits:2}).format(n);}catch{return currency+" "+n.toLocaleString();}}
function statusClass(v?:string){if(["SIGNED","ACTIVE","COMPLETED","HANDOVER_COMPLETED"].includes(v||""))return "border-emerald-200 bg-emerald-50 text-emerald-700";if(["GENERATED","SENT","SCHEDULED","CUSTOMER_ARRIVED","DOCUMENT_VERIFIED","PRE_RENTAL_INSPECTION","SIGNATURE","KEY_HANDOVER"].includes(v||""))return "border-amber-200 bg-amber-50 text-amber-700";return "border-slate-200 bg-slate-100 text-slate-600";}
export function Status({value}:{value?:string}){return <span className={"inline-flex rounded-full border px-2 py-0.5 text-[10px] font-bold tracking-wide "+statusClass(value)}>{human(value)}</span>;}
export function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-1 text-xs font-semibold text-slate-600"><span>{label}</span>{children}</label>;}
export function Info({label,value}:{label:string;value:any}){return <div><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 break-words text-sm font-medium text-slate-800">{value===null||value===undefined||value===""?"—":String(value)}</p></div>;}
export function ErrorBox({text}:{text:string}){return <div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{text}</div>;}
export function Notice({text}:{text:string}){return <div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{text}</div>;}
export function Metric({label,value}:{label:string;value:any}){return <div className="rounded-2xl border bg-white p-4 shadow-sm"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>;}
export function Modal({title,subtitle,onClose,children,max="max-w-4xl"}:{title:string;subtitle?:string;onClose:()=>void;children:React.ReactNode;max?:string}){return <div className="fixed inset-0 z-50 bg-slate-950/55 backdrop-blur-sm sm:p-5" role="dialog" aria-modal="true"><div className={"ml-auto flex h-full w-full flex-col overflow-hidden bg-white shadow-2xl sm:rounded-3xl "+max}><header className="flex items-start justify-between border-b p-5 sm:p-6"><div><h2 className="text-xl font-bold">{title}</h2>{subtitle&&<p className="mt-1 text-sm text-slate-500">{subtitle}</p>}</div><button onClick={onClose} aria-label="Close" className="rounded-full p-2 hover:bg-slate-100"><X size={19}/></button></header><div className="flex-1 overflow-y-auto p-5 sm:p-6">{children}</div></div></div>;}

export function ContractRegister({contracts,bookings,customers,vehicles,onOpen}:{contracts:any[];bookings:any[];customers:any[];vehicles:any[];onOpen:(id:string)=>void}){
 if(!contracts.length)return <div className="rounded-2xl border border-dashed bg-white p-14 text-center text-sm text-slate-500">No Contracts match the current server filters.</div>;
 return <div className="grid gap-3">{contracts.map(c=>{const b=bookings.find(x=>x.id===c.bookingId),customer=customers.find(x=>x.id===c.customerId),v=vehicles.find(x=>x.id===c.vehicleId),currency=c.pricingSnapshot?.currency||c.termsSnapshot?.currency||"KES";return <button key={c.id} onClick={()=>onOpen(c.id)} className="grid w-full gap-4 rounded-2xl border bg-white p-4 text-left shadow-sm transition hover:border-emerald-300 hover:shadow-md md:grid-cols-[1.2fr_1fr_1fr_auto] md:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-sm font-bold">{c.contractNumber}</span><Status value={c.status}/><span className="text-[10px] font-semibold text-slate-400">Contract v{c.contractVersion}</span></div><p className="mt-2 text-sm font-semibold">{customer?.fullName||c.termsSnapshot?.customerFullName||c.customerId}</p><p className="text-xs text-slate-500">{v?v.registrationPlate+" · "+v.make+" "+v.model:c.termsSnapshot?.vehicleRegistrationPlate}</p></div><div><Info label="Booking" value={b?.bookingNumber||c.bookingId}/><p className="mt-2 text-xs text-slate-500">{dateTime(c.termsSnapshot?.pickupAt)} → {dateTime(c.termsSnapshot?.returnAt)}</p></div><div className="grid grid-cols-2 gap-3"><Info label="Gross total" value={money(c.termsSnapshot?.grossTotal,currency)}/><Info label="Current signatures" value={(c.signatures||[]).filter((s:any)=>s.contractVersion===c.contractVersion).length}/><Info label="Generated" value={dateTime(c.generatedAt)}/><Info label="Signed" value={dateTime(c.signedAt)}/></div><ArrowRight className="hidden text-slate-300 md:block"/></button>;})}</div>;
}

export function HandoverRegister({handovers,bookings,customers,vehicles,contracts,onOpen}:{handovers:any[];bookings:any[];customers:any[];vehicles:any[];contracts:any[];onOpen:(id:string)=>void}){
 if(!handovers.length)return <div className="rounded-2xl border border-dashed bg-white p-14 text-center text-sm text-slate-500">No Handover workflows match the current server filters.</div>;
 return <div className="grid gap-3">{handovers.map(h=>{const b=bookings.find(x=>x.id===h.bookingId),c=contracts.find(x=>x.id===h.contractId),customer=customers.find(x=>x.id===h.customerId),v=vehicles.find(x=>x.id===h.vehicleId);return <button key={h.id} onClick={()=>onOpen(h.id)} className="grid w-full gap-4 rounded-2xl border bg-white p-4 text-left shadow-sm transition hover:border-emerald-300 hover:shadow-md md:grid-cols-[1.2fr_1fr_1fr_auto] md:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-sm font-bold">{h.handoverNumber}</span><Status value={h.status}/></div><p className="mt-2 text-sm font-semibold">{customer?.fullName||h.customerId}</p><p className="text-xs text-slate-500">{v?v.registrationPlate+" · "+v.make+" "+v.model:h.vehicleId}</p></div><div><Info label="Booking" value={b?.bookingNumber||h.bookingId}/><Info label="Contract" value={c?.contractNumber||h.contractId}/></div><div className="grid grid-cols-2 gap-3"><Info label="Scheduled" value={dateTime(h.scheduledAt)}/><Info label="Odometer" value={(h.checkoutOdometer??0)+" km"}/><Info label="Fuel" value={(h.checkoutFuelLevel??0)+"%"}/><Info label="Completed" value={dateTime(h.completedAt)}/></div><ArrowRight className="hidden text-slate-300 md:block"/></button>;})}</div>;
}

function History({title,rows,render}:{title:string;rows:any[];render:(x:any)=>React.ReactNode}){return <section className="rounded-2xl border p-5"><h3 className="font-bold">{title}</h3>{!rows.length?<p className="mt-3 text-sm text-slate-500">No records.</p>:<div className="mt-4 space-y-2">{rows.map((x,i)=><div key={x.id||i} className="rounded-xl bg-slate-50 p-3">{render(x)}</div>)}</div>}</section>;}

export function ContractDossier({contract,booking,customer,vehicle,driver,portal,onAction,onSchedule}:{contract:any;booking:any;customer:any;vehicle:any;driver:any;portal:AccessPortal;onAction:(a:ContractAction)=>void;onSchedule:()=>void}){
 const can=(p:string)=>permits(portal,p),currency=contract.pricingSnapshot?.currency||contract.termsSnapshot?.currency||"KES",currentSigs=(contract.signatures||[]).filter((s:any)=>s.contractVersion===contract.contractVersion),t=contract.termsSnapshot,p=contract.pricingSnapshot;
 return <div className="space-y-5"><section className="rounded-2xl bg-slate-950 p-5 text-white"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-lg font-bold">{contract.contractNumber}</span><Status value={contract.status}/><span className="text-xs text-slate-400">Contract v{contract.contractVersion}</span></div><p className="mt-2 text-sm text-slate-300">{customer?.fullName||t?.customerFullName} · {vehicle?vehicle.registrationPlate+" "+vehicle.make+" "+vehicle.model:t?.vehicleRegistrationPlate}</p></div><div className="lg:text-right"><p className="text-xs text-slate-400">Agreed gross total</p><p className="text-2xl font-bold">{money(t?.grossTotal,currency)}</p></div></div></section>
 <section className="grid gap-4 rounded-2xl border p-5 sm:grid-cols-2 lg:grid-cols-4"><Info label="Booking" value={booking?.bookingNumber||contract.bookingId}/><Info label="Customer" value={customer?.fullName||contract.customerId}/><Info label="Primary Driver" value={driver?.fullName||contract.primaryDriverId}/><Info label="Vehicle" value={vehicle?vehicle.registrationPlate+" · "+vehicle.make+" "+vehicle.model:contract.vehicleId}/><Info label="Pickup" value={dateTime(t?.pickupAt)}/><Info label="Return" value={dateTime(t?.returnAt)}/><Info label="Pickup location" value={t?.pickupLocation}/><Info label="Return location" value={t?.returnLocation}/></section>
 <section className="rounded-2xl border p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><h3 className="font-bold">Contract commands</h3><p className="mt-1 text-xs text-slate-500">Every command operates on the current version and retains historical evidence.</p></div><div className="flex flex-wrap gap-2">{can("contract.generate")&&contract.status==="GENERATED"&&<button onClick={()=>onAction("send")} className={secondary}><Send size={14}/>Dispatch</button>}{can("contract.sign")&&["GENERATED","SENT","SIGNED"].includes(contract.status)&&<button onClick={()=>onAction("sign")} className={primary}><FileSignature size={14}/>Record signature</button>}{can("contract.generate")&&["GENERATED","SENT","SIGNED"].includes(contract.status)&&<button onClick={()=>onAction("amend")} className={warning}>Create amended version</button>}{can("rental.start")&&["GENERATED","SENT","SIGNED"].includes(contract.status)&&<button onClick={onSchedule} className={secondary}><ClipboardCheck size={14}/>Schedule Handover</button>}</div></div></section>
 <section className="grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border p-5"><h3 className="font-bold">Frozen terms snapshot</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><Info label="Template" value={(t?.templateId||"—")+" · "+(t?.templateVersion||"—")}/><Info label="Governing law" value={t?.governingLaw}/><Info label="Billable days" value={t?.billableDays}/><Info label="Deposit" value={money(t?.depositAmount,t?.currency||"KES")}/><Info label="Free km/day" value={t?.freeKmPerDay}/><Info label="Excess km rate" value={money(t?.excessKmRate,t?.currency||"KES")}/></div><div className="mt-4"><p className="text-xs font-bold">Special terms</p>{t?.specialTerms?.length?<ul className="mt-2 list-disc space-y-1 pl-5 text-xs text-slate-600">{t.specialTerms.map((x:string,i:number)=><li key={i}>{x}</li>)}</ul>:<p className="mt-2 text-xs text-slate-500">No additional special terms.</p>}</div></section>
 <section className="rounded-2xl border p-5"><h3 className="font-bold">Frozen PricingSnapshot</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><Info label="Snapshot" value={p?.snapshotId}/><Info label="Rate Plan" value={(p?.ratePlanName||"—")+" · "+(p?.ratePlanCode||"—")}/><Info label="Base rental" value={money(p?.baseRentalAmount,p?.currency||"KES")}/><Info label="Tax" value={money(p?.tax?.taxAmount,p?.currency||"KES")}/><Info label="Gross total" value={money(p?.grossRentalTotal,p?.currency||"KES")}/><Info label="Security deposit" value={money(p?.securityDeposit?.amount,p?.currency||"KES")}/></div></section></section>
 <section className="grid gap-5 xl:grid-cols-2"><History title="Signatures" rows={contract.signatures||[]} render={(s:any)=><div><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-semibold">{s.signerName}</span><span className="text-[10px] text-slate-500">{human(s.signerType)} · {human(s.signatureMethod)}</span>{s.contractVersion===contract.contractVersion&&<span className="rounded bg-emerald-100 px-1.5 py-0.5 text-[10px] font-bold text-emerald-700">CURRENT VERSION</span>}</div><p className="mt-1 text-xs text-slate-500">v{s.contractVersion} · Ref {s.signatureReference} · {dateTime(s.signedAt)}</p></div>}/><History title="Status history" rows={contract.statusHistory||[]} render={(h:any)=><div><div className="flex gap-2"><Status value={h.toStatus}/><span className="text-xs text-slate-500">{human(h.fromStatus)} → {human(h.toStatus)}</span></div><p className="mt-1 text-xs text-slate-500">{h.reason||"No reason"} · {dateTime(h.occurredAt)}</p></div>}/></section>
 <History title="Contract version history" rows={contract.versions||[]} render={(v:any)=><div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between"><span className="text-sm font-semibold">Version {v.version}{v.isCurrent?" · Current":""}</span><span className="text-xs text-slate-500">{v.changeReason||"Initial generation"} · {dateTime(v.createdAt)}</span></div>}/>
 {currentSigs.length===0&&contract.status==="SIGNED"&&<ErrorBox text="The Contract reports SIGNED but no signature is attached to the current Contract version. Handover signature confirmation will be blocked by the server."/>}</div>;
}

const steps=["SCHEDULED","CUSTOMER_ARRIVED","DOCUMENT_VERIFIED","PRE_RENTAL_INSPECTION","SIGNATURE","KEY_HANDOVER","HANDOVER_COMPLETED"];

export function HandoverDossier({handover,booking,contract,vehicle,customer,driver,readiness,portal,onAction,onRefreshReadiness,onOpenRentals}:{handover:any;booking:any;contract:any;vehicle:any;customer:any;driver:any;readiness:any;portal:AccessPortal;onAction:(a:HandoverAction)=>void;onRefreshReadiness:()=>void;onOpenRentals:()=>void}){
 const can=(p:string)=>permits(portal,p),index=steps.indexOf(handover.status);
 const next:Record<string,{kind:HandoverAction;label:string;permission:string}>={SCHEDULED:{kind:"arrive",label:"Record Customer Arrival",permission:"rental.start"},CUSTOMER_ARRIVED:{kind:"documents",label:"Verify Documents",permission:"rental.start"},DOCUMENT_VERIFIED:{kind:"inspection",label:"Attach Completed Inspection",permission:"inspection.create"},PRE_RENTAL_INSPECTION:{kind:"signature",label:"Confirm Contract Signature",permission:"contract.sign"},SIGNATURE:{kind:"keys",label:"Handover Keys",permission:"rental.start"},KEY_HANDOVER:{kind:"complete",label:"Complete Handover",permission:"rental.start"}};
 const action=next[handover.status];
 return <div className="space-y-5"><section className="rounded-2xl bg-slate-950 p-5 text-white"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-lg font-bold">{handover.handoverNumber}</span><Status value={handover.status}/></div><p className="mt-2 text-sm text-slate-300">{customer?.fullName||handover.customerId} · {vehicle?vehicle.registrationPlate+" "+vehicle.make+" "+vehicle.model:handover.vehicleId}</p></div><div className="lg:text-right"><p className="text-xs text-slate-400">Scheduled</p><p className="font-semibold">{dateTime(handover.scheduledAt)}</p></div></div></section>
 <section className="overflow-x-auto rounded-2xl border bg-white p-4"><div className="flex min-w-[850px] items-start gap-2">{steps.map((s,i)=><React.Fragment key={s}><div className="flex w-28 flex-col items-center text-center"><div className={"grid h-8 w-8 place-items-center rounded-full border text-xs font-bold "+(i<=index?"border-emerald-600 bg-emerald-600 text-white":"border-slate-200 bg-white text-slate-400")}>{i<index?<CheckCircle2 size={15}/>:i+1}</div><p className={"mt-2 text-[10px] font-semibold "+(i<=index?"text-slate-800":"text-slate-400")}>{human(s)}</p></div>{i<steps.length-1&&<div className={"mt-4 h-px flex-1 "+(i<index?"bg-emerald-500":"bg-slate-200")}/>}</React.Fragment>)}</div></section>
 <section className="grid gap-4 rounded-2xl border p-5 sm:grid-cols-2 lg:grid-cols-4"><Info label="Booking" value={booking?.bookingNumber||handover.bookingId}/><Info label="Contract" value={contract?.contractNumber||handover.contractId}/><Info label="Customer" value={customer?.fullName||handover.customerId}/><Info label="Primary Driver" value={driver?.fullName||handover.primaryDriverId}/><Info label="Vehicle" value={vehicle?vehicle.registrationPlate+" · "+vehicle.make+" "+vehicle.model:handover.vehicleId}/><Info label="Inspection" value={handover.inspectionId}/><Info label="Checkout odometer" value={(handover.checkoutOdometer??0)+" km"}/><Info label="Checkout fuel" value={(handover.checkoutFuelLevel??0)+"%"}/></section>
 <section className="rounded-2xl border p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><h3 className="font-bold">Sequential checkpoint</h3><p className="mt-1 text-xs text-slate-500">The next action comes from the server state machine. Checkpoints cannot be skipped.</p></div><div>{action&&can(action.permission)?<button onClick={()=>onAction(action.kind)} className={primary}><CheckCircle2 size={15}/>{action.label}</button>:handover.status==="HANDOVER_COMPLETED"?<span className="inline-flex items-center gap-2 rounded-xl bg-emerald-50 px-4 py-2 text-sm font-semibold text-emerald-700"><ShieldCheck size={16}/>Physical Handover complete</span>:<span className="text-xs text-slate-500">Your role cannot perform the next checkpoint.</span>}</div></div></section>
 <section className="grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border p-5"><h3 className="font-bold">Checkpoint evidence</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><Info label="Customer arrived" value={dateTime(handover.customerArrivedAt)}/><Info label="Documents verified" value={dateTime(handover.documentsVerifiedAt)}/><Info label="Inspection completed" value={dateTime(handover.inspectionCompletedAt)}/><Info label="Signature confirmed" value={dateTime(handover.signatureCompletedAt)}/><Info label="Keys handed over" value={dateTime(handover.keyHandedOverAt)}/><Info label="Handover completed" value={dateTime(handover.completedAt)}/></div></section><RentalReadiness readiness={readiness} completed={handover.status==="HANDOVER_COMPLETED"} onRefresh={onRefreshReadiness} onOpen={onOpenRentals}/></section>
 <History title="Handover status history" rows={handover.statusHistory||[]} render={(h:any)=><div><div className="flex gap-2"><Status value={h.toStatus}/><span className="text-xs text-slate-500">{human(h.fromStatus)} → {human(h.toStatus)}</span></div><p className="mt-1 text-xs text-slate-500">{h.reason||"No reason"} · {dateTime(h.occurredAt)}</p></div>}/></div>;
}

function RentalReadiness({readiness,completed,onRefresh,onOpen}:{readiness:any;completed:boolean;onRefresh:()=>void;onOpen:()=>void}){
 return <section className="rounded-2xl border p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">Rental start boundary</h3><p className="mt-1 text-xs text-slate-500">Read-only verification. This workspace cannot start the Rental.</p></div>{completed&&<button onClick={onRefresh} className={secondary}>Recheck</button>}</div>{!completed?<p className="mt-4 text-sm text-slate-500">Complete every Handover checkpoint first.</p>:!readiness?<p className="mt-4 text-sm text-slate-500">Rental readiness has not been returned yet.</p>:<div className="mt-4 space-y-3"><div className={"rounded-xl p-3 text-sm font-semibold "+(readiness.isReady?"bg-emerald-50 text-emerald-800":"bg-amber-50 text-amber-800")}>{readiness.isReady?"Ready to proceed to Rentals":"Rental start is still blocked"}</div><div className="grid gap-2 sm:grid-cols-2"><Ready label="Contract signed" value={readiness.contractSigned}/><Ready label="Documents verified" value={readiness.documentsVerified}/><Ready label="Inspection completed" value={readiness.inspectionCompleted}/><Ready label="Vehicle operational" value={readiness.vehicleOperational}/><Ready label="Allocation valid" value={readiness.allocationValid}/></div>{readiness.blockers?.length>0&&<ul className="list-disc pl-5 text-xs text-rose-700">{readiness.blockers.map((x:string,i:number)=><li key={i}>{x}</li>)}</ul>}{readiness.isReady&&<button onClick={onOpen} className={primary}>Open Rentals<ArrowRight size={14}/></button>}</div>}</section>;
}
function Ready({label,value}:{label:string;value:boolean}){return <div className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2 text-xs"><span>{label}</span><span className={value?"font-bold text-emerald-700":"font-bold text-rose-700"}>{value?"Ready":"Blocked"}</span></div>;}

export function GenerateContractModal({bookings,customers,vehicles,onClose,onSave}:{bookings:any[];customers:any[];vehicles:any[];onClose:()=>void;onSave:(dto:any)=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[idempotencyKey]=useState(()=>crypto.randomUUID());
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const d=new FormData(e.currentTarget);try{await onSave({bookingId:String(d.get("bookingId")),templateVersion:String(d.get("templateVersion")||"1.0.0"),specialTerms:String(d.get("specialTerms")||"").split("\n").map(x=>x.trim()).filter(Boolean),idempotencyKey});}catch(err:any){setError(err.message);}finally{setBusy(false);}}
 return <Modal title="Generate Contract" subtitle="Only confirmed Bookings with a frozen PricingSnapshot and no current Contract are eligible." onClose={onClose}>{error&&<ErrorBox text={error}/>}<form onSubmit={submit} className="mt-4 grid gap-4"><Field label="Confirmed Booking *"><select required name="bookingId" className={inputClass}><option value="">Choose Booking</option>{bookings.map(b=>{const c=customers.find(x=>x.id===b.customerId),v=vehicles.find(x=>x.id===b.assignedVehicleId);return <option key={b.id} value={b.id}>{b.bookingNumber} · {c?.fullName||b.customerId} · {v?.registrationPlate||b.assignedVehicleId}</option>;})}</select></Field><Field label="Template version"><input name="templateVersion" defaultValue="1.0.0" className={inputClass}/></Field><Field label="Additional special terms (one per line)"><textarea name="specialTerms" rows={5} className={inputClass}/></Field>{!bookings.length&&<ErrorBox text="No eligible confirmed Booking is available. Confirm a Booking first, or amend the existing Contract instead of creating a duplicate."/>}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className={secondary}>Cancel</button><button disabled={busy||!bookings.length} className={primary}>{busy?<Loader2 size={14} className="animate-spin"/>:<FileText size={14}/>}Generate</button></div></form></Modal>;
}

export function ScheduleHandoverModal({bookings,contracts,customers,vehicles,onClose,onSave}:{bookings:any[];contracts:any[];customers:any[];vehicles:any[];onClose:()=>void;onSave:(dto:any)=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[idempotencyKey]=useState(()=>crypto.randomUUID());
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const d=new FormData(e.currentTarget);try{await onSave({bookingId:String(d.get("bookingId")),scheduledAt:d.get("scheduledAt")?new Date(String(d.get("scheduledAt"))).toISOString():undefined,notes:String(d.get("notes")||"").trim()||undefined,idempotencyKey});}catch(err:any){setError(err.message);}finally{setBusy(false);}}
 return <Modal title="Schedule Handover" subtitle="The server binds this workflow to the current Contract and the Booking's confirmed assigned Vehicle." onClose={onClose}>{error&&<ErrorBox text={error}/>}<form onSubmit={submit} className="mt-4 grid gap-4"><Field label="Eligible Booking *"><select required name="bookingId" className={inputClass}><option value="">Choose Booking</option>{bookings.map(b=>{const c=customers.find(x=>x.id===b.customerId),v=vehicles.find(x=>x.id===b.assignedVehicleId),ctr=contracts.filter(x=>x.bookingId===b.id&&!["ACTIVE","COMPLETED","ARCHIVED"].includes(x.status)).sort((a,z)=>z.contractVersion-a.contractVersion)[0];return <option key={b.id} value={b.id}>{b.bookingNumber} · {ctr?.contractNumber} · {c?.fullName||b.customerId} · {v?.registrationPlate||b.assignedVehicleId}</option>;})}</select></Field><Field label="Scheduled time"><input name="scheduledAt" type="datetime-local" className={inputClass}/></Field><Field label="Notes"><textarea name="notes" rows={4} className={inputClass}/></Field>{!bookings.length&&<ErrorBox text="No Booking is eligible for a new Handover. A confirmed Booking, current Contract and no active Handover are required."/>}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className={secondary}>Cancel</button><button disabled={busy||!bookings.length} className={primary}>Schedule</button></div></form></Modal>;
}
