import React, { useState } from "react";
import { CheckCircle2, FileSignature, Loader2, Send, ShieldCheck } from "lucide-react";
import { apiClient } from "../lib/api-client";
import {
  ErrorBox, Field, Modal, Status, dateTime, inputClass, primary, secondary, warning, unwrap,
  type ContractAction, type HandoverAction
} from "./ContractHandoverPanels";

export function ContractActionModal({kind,contract,customer,driver,onClose,onSave}:{kind:ContractAction;contract:any;customer:any;driver:any;onClose:()=>void;onSave:(dto:any)=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState("");
 async function submit(e:React.FormEvent<HTMLFormElement>){
  e.preventDefault();setBusy(true);setError("");const d=new FormData(e.currentTarget);
  try{
   if(kind==="send")await onSave({deliveryMethod:String(d.get("deliveryMethod")),recipientEmail:String(d.get("recipientEmail")||"").trim()||undefined,recipientPhone:String(d.get("recipientPhone")||"").trim()||undefined});
   if(kind==="sign")await onSave({signerType:String(d.get("signerType")),signerId:String(d.get("signerId")),signerName:String(d.get("signerName")),signatureMethod:String(d.get("signatureMethod")),signatureReference:String(d.get("signatureReference"))});
   if(kind==="amend")await onSave({changeReason:String(d.get("changeReason")),termsSnapshot:{specialTerms:String(d.get("specialTerms")||"").split("\n").map(x=>x.trim()).filter(Boolean)}});
  }catch(err:any){setError(err.message);}finally{setBusy(false);}
 }
 if(kind==="send")return <Modal title="Dispatch Contract" subtitle="This records a dispatch request/event. External provider delivery is not claimed without downstream delivery evidence." onClose={onClose}>{error&&<ErrorBox text={error}/>}<form onSubmit={submit} className="mt-4 grid gap-4"><Field label="Method"><select name="deliveryMethod" className={inputClass}>{["EMAIL","SMS","WHATSAPP","IN_PERSON"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Recipient email"><input name="recipientEmail" defaultValue={customer?.email||""} type="email" className={inputClass}/></Field><Field label="Recipient phone"><input name="recipientPhone" defaultValue={customer?.phone||""} className={inputClass}/></Field><div className="flex justify-end gap-2"><button type="button" onClick={onClose} className={secondary}>Cancel</button><button disabled={busy} className={primary}><Send size={14}/>Record dispatch</button></div></form></Modal>;
 if(kind==="sign")return <Modal title="Record Contract signature" subtitle={"Signature evidence is bound to current Contract version "+contract.contractVersion+"."} onClose={onClose}>{error&&<ErrorBox text={error}/>}<form onSubmit={submit} className="mt-4 grid gap-4"><Field label="Signer type"><select name="signerType" className={inputClass}>{["CUSTOMER","PRIMARY_DRIVER","OPERATOR","CORPORATE_REP","GUARANTOR"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Signer ID"><input required name="signerId" defaultValue={customer?.id||driver?.id||""} className={inputClass}/></Field><Field label="Signer name"><input required name="signerName" defaultValue={customer?.fullName||driver?.fullName||""} className={inputClass}/></Field><Field label="Signature method"><select name="signatureMethod" className={inputClass}>{["ELECTRONIC_OTP","DRAWN_CANVAS","BIOMETRIC","MANUAL_UPLOAD"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Signature reference *"><input required name="signatureReference" placeholder="Verified OTP ref, signature file ref, biometric ref…" className={inputClass}/></Field><div className="flex justify-end gap-2"><button type="button" onClick={onClose} className={secondary}>Cancel</button><button disabled={busy} className={primary}><FileSignature size={14}/>Record signature</button></div></form></Modal>;
 return <Modal title="Create amended Contract version" subtitle="The new current version returns to GENERATED and must be dispatched/signed again." onClose={onClose}>{error&&<ErrorBox text={error}/>}<form onSubmit={submit} className="mt-4 grid gap-4"><Field label="Change reason *"><textarea required name="changeReason" className={inputClass}/></Field><Field label="Current special terms — edit deliberately"><textarea name="specialTerms" rows={8} defaultValue={(contract.termsSnapshot?.specialTerms||[]).join("\n")} className={inputClass}/></Field><div className="flex justify-end gap-2"><button type="button" onClick={onClose} className={secondary}>Cancel</button><button disabled={busy} className={warning}>Create new version</button></div></form></Modal>;
}

export function HandoverActionModal({kind,handover,contract,inspections,onClose,onSave}:{kind:HandoverAction;handover:any;contract:any;inspections:any[];onClose:()=>void;onSave:(dto:any)=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[inspectionReadiness,setInspectionReadiness]=useState<Record<string,any>>({});
 async function inspect(id:string){if(!id)return;try{const r:any=await unwrap(apiClient.inspections.getReadiness(id));setInspectionReadiness(prev=>({...prev,[id]:r}));}catch(e:any){setError(e.message);}}
 async function submit(e:React.FormEvent<HTMLFormElement>){
  e.preventDefault();setBusy(true);setError("");const d=new FormData(e.currentTarget);
  try{
   if(kind==="arrive")await onSave({arrivedAt:d.get("arrivedAt")?new Date(String(d.get("arrivedAt"))).toISOString():undefined,notes:String(d.get("notes")||"").trim()||undefined});
   if(kind==="documents")await onSave({driverLicenseVerified:d.get("driverLicenseVerified")==="on",idDocumentVerified:d.get("idDocumentVerified")==="on",verifiedBy:String(d.get("verifiedBy")||"Staff"),notes:String(d.get("notes")||"").trim()||undefined});
   if(kind==="inspection"){const id=String(d.get("inspectionId"));const insp=inspections.find(x=>x.id===id);if(!insp)throw new Error("Choose a completed PRE_RENTAL Inspection.");const ready=inspectionReadiness[id];if(ready&&!ready.isReady)throw new Error("Selected Inspection readiness is blocked: "+(ready.blockers||[]).join("; "));await onSave({inspectionId:id,odometer:insp.odometer,fuelLevel:insp.fuelLevel,passed:true,notes:String(d.get("notes")||"").trim()||undefined});}
   if(kind==="signature")await onSave({contractSigned:true,signatureReference:String(d.get("signatureReference")||"").trim()||undefined,notes:String(d.get("notes")||"").trim()||undefined});
   if(kind==="keys")await onSave({checkoutOdometer:Number(d.get("checkoutOdometer")),checkoutFuelLevel:Number(d.get("checkoutFuelLevel")),handedOverTo:String(d.get("handedOverTo")),keyTagNumber:String(d.get("keyTagNumber")||"").trim()||undefined,notes:String(d.get("notes")||"").trim()||undefined});
   if(kind==="complete")await onSave({checkoutOdometer:handover.checkoutOdometer,checkoutFuelLevel:handover.checkoutFuelLevel,notes:String(d.get("notes")||"").trim()||undefined});
  }catch(err:any){setError(err.message);}finally{setBusy(false);}
 }
 const title:Record<HandoverAction,string>={arrive:"Record Customer Arrival",documents:"Verify Identity & Driver Documents",inspection:"Attach Completed Pre-Rental Inspection",signature:"Confirm Current Contract Signature",keys:"Physical Key Handover",complete:"Complete Handover"};
 return <Modal title={title[kind]} subtitle="This advances exactly one canonical Handover checkpoint." onClose={onClose}>{error&&<ErrorBox text={error}/>}<form onSubmit={submit} className="mt-4 grid gap-4">
  {kind==="arrive"&&<><Field label="Arrival time"><input name="arrivedAt" type="datetime-local" className={inputClass}/></Field><Field label="Notes"><textarea name="notes" className={inputClass}/></Field></>}
  {kind==="documents"&&<><label className="flex items-center gap-2 rounded-xl border p-3 text-sm"><input required type="checkbox" name="driverLicenseVerified"/>Driver licence physically/authoritatively verified</label><label className="flex items-center gap-2 rounded-xl border p-3 text-sm"><input required type="checkbox" name="idDocumentVerified"/>National ID / passport physically/authoritatively verified</label><Field label="Verified by"><input required name="verifiedBy" defaultValue="Dispatch Staff" className={inputClass}/></Field><Field label="Notes"><textarea name="notes" className={inputClass}/></Field></>}
  {kind==="inspection"&&<><div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800"><strong>Real Inspection required.</strong> Only completed PRE_RENTAL Inspections for this Booking and Vehicle are offered.</div><Field label="Completed PRE_RENTAL Inspection *"><select required name="inspectionId" className={inputClass} onChange={e=>void inspect(e.target.value)}><option value="">Choose Inspection</option>{inspections.map(i=><option key={i.id} value={i.id}>{i.inspectionNumber} · {i.odometer} km · {i.fuelLevel}% · {dateTime(i.completedAt)}</option>)}</select></Field>{!inspections.length&&<ErrorBox text="No completed PRE_RENTAL Inspection exists for this Booking/Vehicle. Complete the canonical Inspection workflow first; Handover will not bypass it."/>}{Object.entries(inspectionReadiness).map(([id,r]:any)=><div key={id} className={"rounded-xl p-3 text-xs "+(r.isReady?"bg-emerald-50 text-emerald-800":"bg-rose-50 text-rose-800")}>{r.isReady?"Inspection readiness passed.":"Inspection readiness blockers: "+(r.blockers||[]).join("; ")}</div>)}<Field label="Checkpoint notes"><textarea name="notes" className={inputClass}/></Field></>}
  {kind==="signature"&&<><div className="rounded-xl bg-slate-50 p-4 text-sm"><div className="flex items-center gap-2"><Status value={contract?.status}/><span className="font-semibold">{contract?.contractNumber||handover.contractId}</span></div><p className="mt-2 text-xs text-slate-500">The server independently verifies that the linked Contract is SIGNED and its current version has signature evidence.</p></div><Field label="Checkpoint reference"><input name="signatureReference" className={inputClass}/></Field><Field label="Notes"><textarea name="notes" className={inputClass}/></Field></>}
  {kind==="keys"&&<><Field label="Checkout odometer *"><input required name="checkoutOdometer" type="number" min={handover.checkoutOdometer||0} defaultValue={handover.checkoutOdometer||0} className={inputClass}/></Field><Field label="Checkout fuel % *"><input required name="checkoutFuelLevel" type="number" min="0" max="100" defaultValue={handover.checkoutFuelLevel??100} className={inputClass}/></Field><Field label="Keys handed to *"><input required name="handedOverTo" className={inputClass}/></Field><Field label="Key tag number"><input name="keyTagNumber" className={inputClass}/></Field><Field label="Notes"><textarea name="notes" className={inputClass}/></Field></>}
  {kind==="complete"&&<><div className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800"><ShieldCheck size={18} className="mb-2"/>This seals physical Handover. It does not create or start a Rental.</div><Field label="Final notes"><textarea name="notes" className={inputClass}/></Field></>}
  <div className="flex justify-end gap-2"><button type="button" onClick={onClose} className={secondary}>Cancel</button><button disabled={busy||(kind==="inspection"&&!inspections.length)} className={primary}>{busy?<Loader2 size={14} className="animate-spin"/>:<CheckCircle2 size={14}/>}Confirm checkpoint</button></div>
 </form></Modal>;
}
